South Carolina Senior Exemption draft
PolicyEngine/policyengine-us pull request #2126
Opened 2023-04-13 18:36 UTC by hua7450

Fixes #2120

Co-authored-by: Pinyan <pxu12@users.noreply.github.com>

Thanks for contributing! Please remove any top-level sections that do not apply to your changes.

- [ ] `make format && make documentation` has been run.

# New variable

- [ ] Label field added
- [ ] Documentation field added
- [ ] Unit field added
- [ ] Default value field added if relevant
- [ ] Variable name follows conventions
- [ ] Unit test(s) added
- [ ] Integration test(s) added if relevant
- [ ] Issues this PR fixes linked

## What's changed

Description of the changes here.

# Bug fix

- [ ] Regression test added
- [ ] Regression test passing

## What this fixes and how it's fixed

Description of how this fix works goes here. Link any issues this PR fixes.

2023-06-02 04:24 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/exemptions/senior/age_threshold.yaml
> +description: South Carolina provides an up to  $15,000 exemption for filers above age 65 (and additional $15,000 if spouse above 65)
```suggestion
description: South Carolina allows filers above this age to be eligible for the senior exemption.
```

2023-06-02 04:24 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/exemptions/senior/age_threshold.yaml
> +  type: single_amount
```suggestion
  unit: year
```

2023-06-02 04:24 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/exemptions/senior/age_threshold.yaml
> +  label: SC senior exemption age threshold
```suggestion
  label: South Carolina senior exemption age threshold
```

2023-06-02 04:24 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/exemptions/senior/age_threshold.yaml
> +  label: SC senior exemption age threshold
and other

2023-06-02 04:26 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/exemptions/senior/amount.yaml
> +description: South Carolina exemption amount per qualifying person (individual and possibly spouse)
```suggestion
description: South Carolina provides the following senior exemption amount for self.
```

2023-06-02 04:26 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/exemptions/senior/amount.yaml
Add a second spouse_amount.yaml parameter file to represent the spouse amount allowed under the senior exemption -> incorporate in variable

2023-06-02 04:28 UTC, PavelMakarchuk requested changes
Let me know if you have questions

2023-06-07 05:11 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/sc/tax/income/exemptions/sc_senior_exemption.py
> +        return max(
```suggestion
        return max_(
```

2023-06-07 05:11 UTC, PavelMakarchuk reviewed
.

2023-06-07 15:10 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/exemptions/senior/age_threshold.yaml
need 2021 values

2023-06-07 15:10 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/exemptions/senior/spouse_amount.yaml
need 2021 values for all parameters

2023-06-07 15:22 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/exemptions/senior/spouse_amount.yaml
> +  label: South Carolina senior exemption amount
```suggestion
  label: South Carolina senior exemption spouse amount
```

2023-06-07 15:23 UTC, PavelMakarchuk reviewed
minor change

2023-06-12 02:55 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/exemptions/senior/age_threshold.yaml
> +  type: single_amount
```suggestion
```

2023-06-20 21:32 UTC, MaxGhenis requested changes

2023-06-20 21:32 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/sc/tax/income/exemptions/sc_senior_exemption.py
> +        # Calculate senior exemption. The exemption can not be less than 0. Add head and spouse together.
I wasn't sure about this until looking at the law, so added a comment and split it up for readability.
```suggestion
        # Calculate senior exemption. The exemption can not be less than 0. Add head and spouse together.
        # Per the legal code, this applies separately:
        # "(2) In the case of married taxpayers who file a joint federal income tax return, the reduction required by item (1) applies to each individual separately"
        head_exemption = max_(
            head_eligible * p.amount - head_deductions, 0
        )
        spouse_exemption = max_(
            spouse_eligible * p.spouse_amount - spouse_deductions, 0
        )
        return head_exemption + spouse_exemption
```

2023-06-20 21:32 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/sc/tax/income/exemptions/sc_military_retirement_income_deduction.py
> +class sc_military_retirement_income_deduction(Variable):
Same for retirement income
```suggestion
class sc_military_retirement_income_deduction_head(Variable):
```

2023-06-20 21:32 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/sc/tax/income/exemptions/sc_military_retirement_income_deduction.py
> +    label = "South Carolina military retirement income deduction for self"
```suggestion
    label = "South Carolina military retirement income deduction for head"
```

2023-06-20 21:32 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/sc/tax/income/exemptions/sc_senior_exemption.py
> +        retirement_income_deduction = tax_unit(
same for spouse
```suggestion
        head_deductions = add(tax_unit, period, ["sc_retirement_income_deduction_head", "sc_military_retirement_income_deduction_head"])
```

2023-06-29 03:05 UTC, MaxGhenis approved these changes

2023-07-03 01:54 UTC, merged