Merge branch 'master' of https://github.com/PolicyEngine/policyengine-us into ll_oh_senior_citizen
PolicyEngine/policyengine-us pull request #2178
Opened 2023-04-25 02:30 UTC by Linfeng-ll

adding child and dependent care credits and senior citizen credits.

2023-04-27 17:36 UTC, nmrodelo requested changes
Added formatting changes, updated changelog to reflect that two variables are being added ( we forgot to add senior citizen credit as its own PR). Unable to update version on my end, @MaxGhenis could you get that? Alternatively, @Linfeng-ll , if you have time before we meet tonight to update that would be great.

2023-05-02 04:41 UTC, MaxGhenis reviewed
is this ready for review? if so please mark it as such (currently in draft) and i'll take a closer look

2023-05-02 04:41 UTC, MaxGhenis commented on =0.1.7
> +Requirement already satisfied: yaml-changelog in /opt/conda/envs/policyengine/lib/python3.9/site-packages (0.3.0)
remove file

2023-06-28 17:38 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/child/agi_upper_limit.yaml
> +description: Ohio CDCC AGI Limit
```suggestion
description: Ohio limits its CDCC amount at this AGI threshold.
```

2023-06-28 17:38 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/child/agi_upper_limit.yaml
> +  label: OH Child Care and Dependent Care Credit
```suggestion
  label: OH Child Care and Dependent Care Credit income threshold
```

2023-06-28 17:38 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/child/agi_upper_limit.yaml
> +  reference:
add legal code reference

2023-06-28 17:39 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/child/cdcc_fraction.yaml
> +description: Ohio Federal CDCC Match Percentage
```suggestion
description: Ohio matched the federal CDCC at this rate.
```

2023-06-28 17:39 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/child/cdcc_fraction.yaml
> +  label: OH Child Care and Dependent Care Credit
```suggestion
  label: Ohio Child Care and Dependent Care Credit match rate
```

2023-06-28 17:41 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/senior_citizen/age_threshold.yaml
> +description: OH Senior Citizen Credit Age Threshold
```suggestion
description: Ohio provides the Senior Citizen Credit to filers at or above this age threshold.
```

2023-06-28 17:41 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/senior_citizen/age_threshold.yaml
> +  label: OH Senior Citizen Credit
```suggestion
  label: Ohio Senior Citizen Credit age threshold
```

2023-06-28 17:41 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/senior_citizen/age_threshold.yaml
> +  unit: years
```suggestion
  unit: year
```

2023-06-28 17:42 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/oh_senior_citizen_credits.py
> +    label = "Ohio senior citizen credits"
```suggestion
    label = "Ohio senior citizen credit"
```

2023-06-28 17:43 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Added Ohio Child Care and Dependent Care Credit
```suggestion
    - Added Ohio Child Care and Dependent Care Credit.
```

2023-06-28 17:43 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Added Ohio Senior Citizen Credit
```suggestion
    - Added Ohio Senior Citizen Credit.
```

2023-07-07 02:52 UTC, MaxGhenis requested changes

2023-07-09 02:38 UTC, MaxGhenis requested changes

2023-07-09 02:38 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/oh/tax/income/credits/oh_child_dependent_care_credits.py
> +        agi_upper_limit = parameters(
Then access `p.x` in the `{oh,us}_eligible` statements below, directly. For this and other parameters.
```suggestion
        p =   parameters(period).gov.states.oh.tax.income.credits.child
```

2023-07-09 02:38 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/oh/tax/income/credits/oh_child_dependent_care_credits.py
> +
Please add comments

2023-07-09 02:38 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/child/agi_partial_credit_limit.yaml
Replace these three parameters with a single scale parameter:
* [-np.inf, 20_000) -> 1
* [20_000, 40_000) -> 0.25
* [40_000, np.inf] -> 0

2023-07-09 02:38 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/senior_citizen/agi_cap.yaml
Rename to `agi_limit.yaml` for consistency with child credit

2023-07-09 02:38 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/states/oh/tax/income/credits/oh_senior_citizen_credits.yaml
> +    oh_has_not_taken_oh_lump_sum_credits: 1
should be bool

2023-07-09 02:38 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/senior_citizen/agi_cap.yaml
similarly replace this and credit_amount with a single scale parameter

2023-07-18 17:31 UTC, PavelMakarchuk approved these changes

2023-07-19 04:01 UTC, MaxGhenis requested changes

2023-07-19 04:01 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/oh/tax/income/credits/oh_child_dependent_care_credits.py
> +class oh_child_dependent_care_credits(Variable):
```suggestion
class oh_cdcc(Variable):
```

2023-07-19 04:01 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/oh/tax/income/credits/oh_child_dependent_care_credits.py
> +    label = "Ohio senior citizen credits"
```suggestion
    label = "Ohio child and dependent care credit"
```

2023-07-19 04:01 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/oh/tax/income/credits/oh_senior_citizen_credits.py
> +class oh_senior_citizen_credits(Variable):
```suggestion
class oh_senior_citizen_credit(Variable):
```

2023-07-19 19:21 UTC, MaxGhenis approved these changes

2023-07-19 19:22 UTC, merged