oh_non_public_school_credits
PolicyEngine/policyengine-us pull request #2212
Opened 2023-04-28 18:13 UTC by Linfeng-ll

Add oh_non_public_school_credits variable and test files

2023-06-28 17:47 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Added Ohio Non public school credit
```suggestion
    - Ohio Non public school credit.
```

2023-06-28 17:48 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/non_public_tuition/agi_credit_amount.yaml
> +description: OH Nonchartered, Nonpublic, School Tuition Credit AGI Credit Amount
```suggestion
description: Ohio provides this Nonchartered, Nonpublic, School Tuition Credit AGI Credit amount.
```

2023-06-28 17:48 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/non_public_tuition/agi_credit_amount.yaml
> +  label: OH Non Public School Credit
```suggestion
  label: Ohio Non Public School Credit amount
```

2023-06-28 17:49 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/oh_non_public_school_credits.py
> +        "Ohio Nonchartered, Nonpublic, School Tuition Credit AGI Credit Rates"
```suggestion
        "Ohio Nonchartered, Nonpublic, School Tuition Credit AGI Credit"
```

2023-07-06 18:11 UTC, PavelMakarchuk commented on changelog_entry.yaml
need to run `git pull origin master`

2023-07-11 03:30 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/non_public_tuition/agi_credit_amount.yaml
> +
add 2022 tax form as well (should be 3 references total)

2023-07-11 19:08 UTC, MaxGhenis requested changes

2023-07-11 19:08 UTC, MaxGhenis commented on policyengine_us/variables/household/demographic/person/non_public_school_tuition.py
Move to `household/expense/education/`

2023-07-11 19:08 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/states/oh/tax/income/credits/oh_non_public_school_credits.yaml
> +- name: AGI less that 50_000
Only need underscores in values
```suggestion
- name: AGI less than $50,000
```

2023-07-11 19:08 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/oh/tax/income/credits/oh_non_public_school_credits.py
> +        agi = tax_unit("oh_agi", period)
The law says it's based on federal AGI
```suggestion
        agi = tax_unit("adjusted_gross_income", period)
```

2023-07-11 19:08 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/non_public_tuition/agi_credit_amount.yaml
> +description: Ohio provides this Nonchartered, Nonpublic, School Tuition Credit AGI Credit amount.
```suggestion
description: Ohio caps the Nonchartered, Nonpublic, School Tuition Credit at this amount, depending on federal adjusted gross income.
```

2023-07-11 19:08 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/oh/tax/income/credits/oh_non_public_school_credits.py
> +        tuitions = sum(person("non_public_school_tuition", period))
Please add unit tests to ensure it's being capped by tuition expenses (as it currently isn't)
```suggestion
        tuition = tax_unit.sum(person("non_public_school_tuition", period))
        cap = rates.calc(agi)
        return min_(tuition, cap)
```

2023-07-11 21:23 UTC, MaxGhenis requested changes

2023-07-11 21:23 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/states/oh/tax/income/credits/oh_non_public_school_credits.yaml
>  - name: AGI greater that 50_000 case 1
also reformat per above (and the below one too)

2023-07-11 21:23 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/oh/tax/income/credits/oh_non_public_school_credits.py
>          rates = parameters(
This isn't a rate.
```suggestion
        p = parameters(
```

2023-07-11 21:23 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/oh/tax/income/credits/oh_non_public_school_credits.py
> +        ).gov.states.oh.tax.income.credits.non_public_tuition
```suggestion
        ).gov.states.oh.tax.income.credits
```

2023-07-11 21:23 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/oh/tax/income/credits/oh_non_public_school_credits.py
> +        cap = rates.calc(agi)
```suggestion
        cap = p.non_public_tuition.calc(agi)
```

2023-07-13 05:05 UTC, MaxGhenis approved these changes

2023-07-13 05:06 UTC, merged