Arkansas standard deduction
PolicyEngine/policyengine-us pull request #2237
Opened 2023-05-05 18:43 UTC by Kevintowne

Fixes #2208

2023-05-23 05:47 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ar/tax/income/deductions/standard/ar_standard_deduction.py
If AGI is below the standard dedcution -> the deduction is equal to AGI; 
Could you please include this into the formula
https://www.dfa.arkansas.gov/images/uploads/incomeTaxOffice/2022_AR1000F_and_AR1000NR_Instructions.pdf#page=14

2023-05-23 06:10 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ar/tax/income/deductions/standard/ar_standard_deduction.py
We also need to include the possibility that the married household is filing separately or jointly

2023-05-29 20:06 UTC, Kevintowne commented on policyengine_us/variables/gov/states/ar/tax/income/deductions/standard/ar_standard_deduction.py
Got it. Thank you for your comments. I'm working on it.

2023-05-29 20:06 UTC, Kevintowne commented on policyengine_us/variables/gov/states/ar/tax/income/deductions/standard/ar_standard_deduction.py
Got it.

2023-06-12 03:20 UTC, MaxGhenis requested changes

2023-06-12 03:20 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ar/tax/income/deductions/standard.yaml
> +    href: https://advance.lexis.com/container/?pdmfid=1000516&crid=1b7c59fc-ee50-4b71-9f32-869742d3b94c&func=LN.Advance.ContentView.getFullToc&nodeid=ABAAAFAAC&typeofentry=Breadcrumb&config=00JAA3ZTU
Direct link to section
```suggestion
    href: https://advance.lexis.com/documentpage/?pdmfid=1000516&crid=8a0a4a46-62e0-41b6-8539-42452c3a9e46&nodeid=ABAAAFAACAAFABG&nodepath=%2FROOT%2FABA%2FABAAAF%2FABAAAFAAC%2FABAAAFAACAAF%2FABAAAFAACAAFABG&level=5&haschildren=&populated=false&title=26-51-430.+Deductions+%E2%80%94+Standard+deduction+%E2%80%94+Definition.&config=00JAA2ZjZiM2VhNS0wNTVlLTQ3NzUtYjQzYy0yYWZmODJiODRmMDYKAFBvZENhdGFsb2fXiYCnsel0plIgqpYkw9PK&pddocfullpath=%2Fshared%2Fdocument%2Fstatutes-legislation%2Furn%3AcontentItem%3A649P-FBD0-R03K-54BT-00008-00&ecomp=7gf5kkk&prid=4b6d04eb-5f42-47a5-b744-f8596299a894
```

2023-06-12 03:20 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ar/tax/income/deductions/standard.yaml
> +  2022-01-01: 4_540
Since you cite the law
```suggestion
  # $4,400 in 2015 + COLA, rounded by $10.
  2022-01-01: 4_540
```

2023-06-12 03:20 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ar/tax/income/deductions/standard.yaml
> +  2022-01-01: 2_270
```suggestion
    # $2,200 in 2015 + COLA, rounded by $10.
  2022-01-01: 2_270
```

2023-07-17 20:33 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/deductions/standard.yaml
> +
add 2021 tax form reference

2023-07-25 14:48 UTC, PavelMakarchuk commented on CHANGELOG.md
run `git pull upstream master`

2023-07-25 14:49 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ar/tax/income/deductions/itemized/ar_itemized_deductions.yaml
We only need to test the varibale inputs from the created .py file

2023-07-25 14:49 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ar/tax/income/deductions/itemized/ar_itemized_deductions.yaml
This tests the Cal itemized deduction

2023-07-30 23:18 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/deductions/standard.yaml
> +description: Arkansas provides a standard deduction of this amount.
```suggestion
description: Arkansas provides a standard deduction of this amount, based on filing status.
```

2023-07-30 23:18 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/deductions/standard.yaml
> +  - title: Arkansas 2022 Individual Income Tax Forms and Instructions
add pages to references - all tax forms

2023-07-30 23:18 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ar/tax/income/deductions/itemized/ar_itemized_deductions.yaml
> +- name: Single filer with high AGI and large charitable_deduction
```suggestion
- name: Single filer with high AGI and large charitable deduction
```

2023-07-30 23:18 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ar/tax/income/deductions/itemized/ar_itemized_deductions.yaml
> +- name: Single filer with low AGI and large charitable_deduction
```suggestion
- name: Single filer with low AGI and large charitable deduction
```

2023-08-03 20:18 UTC, PavelMakarchuk approved these changes

2023-08-04 21:19 UTC, MaxGhenis approved these changes

2023-08-04 21:19 UTC, merged