write South Carolina Two wage earner credit code
PolicyEngine/policyengine-us pull request #2309
Opened 2023-05-23 19:23 UTC by hua7450

Fixes #2307

Co-authored-by: Pinyan <pxu12@users.noreply.github.com>

Thanks for contributing! Please remove any top-level sections that do not apply to your changes.

- [ ] `make format && make documentation` has been run.

# New variable

- [ ] Label field added
- [ ] Documentation field added
- [ ] Unit field added
- [ ] Default value field added if relevant
- [ ] Variable name follows conventions
- [ ] Unit test(s) added
- [ ] Integration test(s) added if relevant
- [ ] Issues this PR fixes linked

## What's changed

Description of the changes here.

# Bug fix

- [ ] Regression test added
- [ ] Regression test passing

## What this fixes and how it's fixed

Description of how this fix works goes here. Link any issues this PR fixes.

2023-06-07 05:21 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - South Carolina two wage eraner credits.
```suggestion
    - South Carolina two wage eraner credit.
```

2023-06-07 05:21 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    fixed:
```suggestion
    added:
```

2023-06-07 05:21 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/two_wage_earner/rates.yaml
> +description:
add

2023-06-07 05:21 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/two_wage_earner/rates.yaml
> +# threshold value is bottom of the tax bracket; thresholds are <=
```suggestion
```

2023-06-07 05:23 UTC, PavelMakarchuk commented on =0.1.7
run `make format`

2023-06-07 05:23 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/sc/tax/income/credits/sc_income_head.py
need test

2023-06-07 05:24 UTC, PavelMakarchuk reviewed
comment

2023-06-07 15:37 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/sc/tax/income/credits/sc_ira_deduction_head.py
use [this](taxable_income_deductions) instead of head and spouse sc_deduction

2023-06-20 21:07 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - South Carolina two wage eraner credit.
```suggestion
    - South Carolina two wage earner credit.
```

2023-06-20 21:08 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/two_wage_earner/earned_income.yaml
> +    - wages #not sure
wages and tips included in employment income

2023-06-20 21:08 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/two_wage_earner/earned_income.yaml
> +    - commisions #not found
```suggestion
   # - commisions 
```

2023-06-20 21:08 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/two_wage_earner/earned_income.yaml
> +    - sub_pay #not found
```suggestion
   # - sub_pay 
```

2023-06-20 21:09 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/two_wage_earner/earned_income_spouse.yaml
> +    - wages_spouse #not sure
same format for not found variables

2023-06-20 21:10 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/sc/tax/income/credits/two_wage_earner/sc_two_wage_earner_credits.yaml
> +  absolute_error_margin: 0
```suggestion
```

2023-06-20 21:10 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/sc/tax/income/credits/two_wage_earner/sc_two_wage_earner_credits.yaml
> +  absolute_error_margin: 0
don't need if 0

2023-06-20 21:11 UTC, PavelMakarchuk commented on =0.1.7
run `make format` and `git pull upstream master`

2023-06-20 21:12 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/two_wage_earner/earned_income_spouse.yaml
add legislative source + in other yaml files

2023-06-20 21:17 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/two_wage_earner/rates.yaml
> +description: The tax rate of two wage earner credits in South Carolina.
```suggestion
description: South Carolina provides these rates under the two wage earner credit.
```

2023-07-03 18:15 UTC, MaxGhenis requested changes

2023-07-03 18:15 UTC, MaxGhenis commented on =0.1.7
remove

2023-07-03 18:15 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/two_wage_earner/earned_income.yaml
> +    - state_or_federal_salary
I think this is included in `employment_income`

2023-07-03 18:15 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/two_wage_earner/rates.yaml
> +
remove extra spaces (one line is ok)

2023-07-03 18:15 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/two_wage_earner/rates.yaml
> +    - title: SC Legal Code |  Section 12-6-3330
```suggestion
    # Legal code set it to $50,000, then amended it to $30,000 in 2017.
    # Now adjusted for inflation.
    - title: SC Legal Code |  Section 12-6-3330
```

2023-07-03 18:15 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/sc/tax/income/credits/two_wage_earner/sc_two_wage_earner_credits.py
> +        person = tax_unit.members
I think we can do this with fewer intermediate variables. Also note we use `eligible` to mean eligibility (bool).
```suggestion
        # Determine eligibility. Must be a joint filer.
        filing_status = tax_unit("filing_status", period)
        eligible = filing_status == filing_status.possible_values.JOINT
        # Find relevant gross income of head and spouse.
        person = tax_unit.members
        income = person("sc_gross_earned_income_head", period)
        head_income = income * person("is_tax_unit_head", period)
        spouse_income = income * person("is_tax_unit_spouse", period)
        # Determine lesser of head and spouse income.
        lesser_head_spouse_income = min_(head_income, spouse_income)
        # Calculate credit based on rate.
        p = parameters(
            period
        ).gov.states.sc.tax.income.credits.two_wage_earner
        credit_if_eligible = p.rate.calc(lesser_head_spouse_income)
        return credit_if_eligible * eligible
```

2023-07-03 18:15 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/two_wage_earner/rates.yaml
rename `rate.yaml` since only one

2023-07-07 02:55 UTC, MaxGhenis approved these changes
all set once you run `git pull upstream master`

2023-07-10 16:37 UTC, closed without merging