South Carolina CDCC
PolicyEngine/policyengine-us pull request #2387
Opened 2023-06-03 01:44 UTC by hua7450

2023-06-07 05:16 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/cdcc/amount.yaml
> +description: South Carolina child and dependent care credit amount.
```suggestion
description: South Carolina provides this amount under the child and dependent care credit.
```

2023-06-07 05:16 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/cdcc/amount.yaml
> +  2022-01-01: 210
need to add 2021 value as well

2023-06-07 05:16 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/cdcc/amount.yaml
> +  label: South Carolina child and dependent care credit amount.
```suggestion
  label: South Carolina child and dependent care credit amount
```

2023-06-07 05:17 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/cdcc/rate.yaml
> +description: South Carolina matches this share of the federal Child and Dependent Care Credit
```suggestion
description: South Carolina matches this share of the federal Child and Dependent Care Credit.
```

2023-06-07 05:17 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/cdcc/amount.yaml
> +  2022-01-01: 210
+ other parameter files

2023-06-07 05:18 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/sc/tax/income/credits/sc_cdcc.yaml
test with no eligible dependent

2023-06-07 05:20 UTC, PavelMakarchuk reviewed
comments

2023-06-07 05:20 UTC, PavelMakarchuk reviewed
comments

2023-06-07 05:20 UTC, PavelMakarchuk reviewed
comments

2023-06-12 03:10 UTC, MaxGhenis requested changes
can you add legal code references

2023-06-12 03:10 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/sc/tax/income/credits/cdcc/sc_cdcc.py
> +        # Get federal child care expenses
This isn't a federally defined value.
```suggestion
        # Get child care expenses.
```

2023-06-12 03:10 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/sc/tax/income/credits/cdcc/sc_cdcc.py
> +        federal_cdce = tax_unit("tax_unit_childcare_expenses", period)
```suggestion
        childcare_expenses = tax_unit("tax_unit_childcare_expenses", period)
```

2023-06-12 03:10 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/sc/tax/income/credits/cdcc/sc_cdcc.py
> +        return (
Break up for clarity
```suggestion
        max_match = childcare_expenses * p.rate
        cap = p.amount * count_cdcc_eligible
        return eligible * min_(max_match, cap)
```

2023-06-12 03:10 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/sc/tax/income/credits/cdcc/sc_cdcc.py
> +        # # Married filing separate are ineligible.
```suggestion
        # Married filing separate are ineligible.
```

2023-06-13 10:10 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/cdcc/amount.yaml
> +    - title: Child and Dependent Care Credit
```suggestion
    - title: SC-1040 2021
```

2023-06-22 13:13 UTC, MaxGhenis requested changes

2023-06-22 13:13 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/cdcc/amount.yaml
> +    - title: South Carolina Legal Code | SECTION 12-6-3380
$210 is not in the legal code. Please make sure to only cite relevant references.

2023-06-22 13:13 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/cdcc/rate.yaml
This is the only number in the legal code, which means the other parameters can be deleted and you can instead cite parameters from the federal CDCC, which the SC law references.

You can then take the `cdcc.py` formula and simplify it to remove the applicable percentage reduction, as the law prescribes.

2023-06-26 18:19 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/cdcc/rate.yaml
[I see.](https://dor.sc.gov/forms-site/Forms/IITPacket_2021.pdf#page=21) Tax forms must implement the law, so that indicates that another part of the law skips the 2021 federal CDCC reform.

I couldn't find exactly where this was, but Section 12-6-40 governs state-federal conformity, and [this bill](https://www.scstatehouse.gov/sess124_2021-2022/prever/5057_20220503.docx) mentions the CDCC decoupling. I think what happened was that the legal code previously "pinned" to the IRC as of 2020-12-31, and that bill moved the pin to 2021-12-31. If the legal code had a historical view, we'd be able to see how it was pinned at the time that 2021 state tax laws governed the forms.

Here's another variable that uses decoupling: https://github.com/PolicyEngine/policyengine-us/blob/6d0b7f25fd5e08ab7853ffaa6a9de2515aac4010/policyengine_us/variables/gov/states/md/tax/income/agi/subtractions/md_dependent_care_subtraction.py#L31

2023-06-29 02:59 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/states/sc/tax/income/credits/sc_cdcc.yaml
>  - name: One cdcc eligible person, with $4000 spending on federal child care expense
could you also add a unit test for 2022 exceeding the cap? to ensure the offset works as intended

2023-07-03 02:12 UTC, MaxGhenis requested changes

2023-07-03 02:12 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/sc/tax/income/credits/cdcc/sc_cdcc.py
> +        p = parameters(period).gov.states.sc.tax.income.credits.cdcc
```suggestion
        p_sc = parameters(period).gov.states.sc.tax.income.credits.cdcc
```

2023-07-03 02:12 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/sc/tax/income/credits/cdcc/sc_cdcc.py
> +        p2 = parameters(period).gov.irs.credits.cdcc
```suggestion
        p_us = parameters(period).gov.irs.credits.cdcc
```

2023-07-03 02:12 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/sc/tax/income/credits/cdcc/sc_cdcc.py
> +        max_match = childcare_expenses * p.rate
to simplify
```suggestion
        capped_expenses = min_(childcare_expenses, sc_max_care_expense * count_cdcc_eligible)
        return eligible * capped_expenses * p.rate
```

2023-07-03 03:50 UTC, MaxGhenis approved these changes

2023-07-03 04:00 UTC, merged