South Carolina EITC
PolicyEngine/policyengine-us pull request #2396
Opened 2023-06-05 19:25 UTC by hua7450

2023-06-07 05:12 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/eitc/rate.yaml
> +    title: South Carlina Earned income tax credit
```suggestion
   -  title: South Carlina Earned income tax credit 
```

2023-06-07 05:13 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/eitc/rate.yaml
> +description: South Carolina provides this rate to match the federal EITC.
```suggestion
description: South Carolina matches the federal EITC at this rate.
```

2023-06-07 05:13 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/eitc/rate.yaml
> +  2018-01-01: 0.2083
start with oldest value at the top

2023-06-07 05:13 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/eitc/rate.yaml
> +  unit: year
```suggestion
  unit: /1
```

2023-06-07 05:14 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/sc/tax/income/credits/eitc/sc_eitc.yaml
need unique test case names to represent simulated situation

2023-06-07 05:14 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/sc/tax/income/credits/eitc/sc_eitc.py
> +    reference = "https://dor.sc.gov/about/forms"
need exact form reference

2023-06-07 05:15 UTC, PavelMakarchuk requested changes
comments

2023-06-11 23:54 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/eitc/rate.yaml
> +  - title: South Carlina Earned income tax credit
need 2022 reference

2023-06-11 23:55 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/eitc/rate.yaml
> +  - title: South Carlina Earned income tax credit
```suggestion
  - title: South Carlina Schedule TC-60 2021
```

2023-06-22 13:02 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/eitc/rate.yaml
> +  - title: South Carlina Schedule TC-60 2021 (2021)
```suggestion
  - title: South Carolina Schedule TC-60 2021 (2021)
```

2023-06-22 13:03 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/eitc/rate.yaml
> +  reference:
Can you add a legal code reference?

2023-06-22 13:04 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/eitc/rate.yaml
> +  2018-01-01: 0.2083
These values need references right? Legal code may suffice.

2023-06-26 17:25 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/sc/tax/income/credits/eitc/rate.yaml
> +  2022-01-01: 1.0417
Per law
```suggestion
  2022-01-01: 1.0417
  2023-01-01: 1.25
```

2023-06-28 15:32 UTC, PavelMakarchuk reviewed
need to run `git pull upstream master`

2023-06-29 03:07 UTC, MaxGhenis approved these changes

2023-06-29 03:07 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/sc/tax/income/credits/eitc/sc_eitc.py
> +import numpy as np
The `model_api` import includes `np`
```suggestion
```

2023-07-03 01:41 UTC, merged