Indiana Earned Income Credit
PolicyEngine/policyengine-us pull request #2479
Opened 2023-06-22 19:42 UTC by SirMalamute

Fixes #2478

2023-07-17 19:38 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/credits/eitc/in_is_child_eligible_eitc.py
> +        is_24 = person("age", period) < 24
19 & 24 need to be parameters

2023-07-17 19:38 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/credits/eitc/in_is_child_eligible_eitc.py
> +class is_child_eligible_eitc(Variable):
```suggestion
class in_eitc_eligible_child(Variable):
```

2023-07-17 19:38 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/credits/eitc/in_is_child_eligible_eitc.py
> +    defined_for = StateCode.ID
```suggestion
    defined_for = StateCode.IN
```

2023-07-17 19:38 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/credits/eitc/in_eitc.py
> +class in_eitc(Variable):
```suggestion
class in_eic(Variable):
```

2023-07-17 19:39 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eitc/child_income_bracket_eligibility.yaml
change folder name to eic -> all folders

2023-07-17 19:39 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eitc/match.yaml
> +description: Indiana EIC is 10% of Federal EIC
```suggestion
description: Indiana matches this percentage of the federal EITC.
```

2023-07-17 19:40 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eitc/match.yaml
> +    2022-01-01: 0.1
need 2021 value

2023-07-17 19:40 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eitc/match.yaml
> +  label: Indiana unified elderly tax credit married one aged
```suggestion
  label: Indiana eic match
```

2023-07-17 19:40 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eitc/match.yaml
> +      href: https://forms.in.gov/Download.aspx?id=15432
need 2021 reference

2023-07-17 19:40 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eitc/child_income_bracket_eligibility.yaml
> +    - title: Indiana Earned Income Credit 2022
need 2021 reference

2023-07-17 19:41 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eitc/child_income_bracket_eligibility.yaml
> +  label: Indiana unified elderly tax credit married one aged
```suggestion
  label: Indiana eic income eligibility
```

2023-07-17 19:42 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/credits/eitc/in_is_child_eligible_eitc.py
need test case here as well

2023-07-17 19:43 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eitc/child_income_bracket_eligibility.yaml
> +description: Indiana has income eligibility for EIC, based on the number of children. AGI (Indiana modified, but usually federal) needs to be less than these values depending on num. of children.
```suggestion
description: Indiana provides the EIC for filers with income below this threshold, based on number of children.
```

2023-07-20 19:05 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/age_child.yaml
need to add chnagelog

2023-07-20 19:08 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/age_child.yaml
> +description: Age threshold to be eligible for as a qualifying child in IN EIC without being a full time student
```suggestion
description: Indiana provides the EIC for filers with children below this age threshold.
```

2023-07-20 19:08 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/age_child.yaml
> +description: Age threshold to be eligible for as a qualifying child in IN EIC without being a full time student
same in other age yaml

2023-07-20 19:08 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/age_child.yaml
> +    - title: Qualifying Child Rules | IRS
add a reference from indiana

2023-07-20 19:09 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/age_child.yaml
> +    - title: Qualifying Child Rules | IRS
both yaml

2023-07-20 19:09 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/age_child.yaml
> +  label: IN EIC Qualifying Child
```suggestion
  label: Indiana EIC non-student child age threshold 
```

2023-07-20 19:10 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/age_child.yaml
make a folder called `age` with 2 files in it

2023-07-20 19:10 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/income_threshold.yaml
> +    - title: Indiana Earned Income Credit 2022
add a legal reference

2023-07-20 19:12 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/income_threshold.yaml
> +    - title: Indiana Earned Income Credit 2022
all yaml files

2023-07-20 19:16 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/credits/eitc/in_eic_eligible_child.py
need to create a unit test for this variable as well

2023-07-30 23:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/age/age_child.yaml
> +description: Age threshold to be eligible for as a qualifying child in IN EIC without being a full time student
```suggestion
description: Indiana provides the EITC for filers with children below this age threshold.
```

2023-07-30 23:53 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/age/age_full_time_student.yaml
> +description: Age threshold to be eligible for as a qualifying child in IN EIC as a full time student
```suggestion
description: Indiana provides the EITC for filers with children who are full-time students below this age threshold.
```

2023-07-30 23:53 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/age/age_child.yaml
> +  label: Indiana provides the EIC for filers with children who are not full time students below this age threshold.
```suggestion
  label: Indiana EIC child age threshold
```

2023-07-30 23:54 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/age/age_full_time_student.yaml
> +  label: Indiana provides the EIC for filers with children who are full time students below this age threshold.
```suggestion
  label: Indiana EITC full-time student age threshold
```

2023-07-30 23:54 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/age/age_child.yaml
rename to child.yaml

2023-07-30 23:54 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/age/age_full_time_student.yaml
rename to full_time_student.yaml

2023-07-30 23:54 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/income_threshold.yaml
> +  label: Indiana eic income eligibility
```suggestion
  label: Indiana EITC income eligibility 
```

2023-07-30 23:55 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/income_threshold.yaml
> +    - title: Indiana Earned Income Credit 2021
need page for the tax form where we can find the value

2023-07-30 23:55 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/match.yaml
> +  label: Indiana eic match
```suggestion
  label: Indiana EITC match
```

2023-07-30 23:55 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eic/income_threshold.yaml
> +    - title: Indiana Earned Income Credit 2021
all yaml files

2023-07-30 23:55 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/credits/eitc/in_eic_eligible_child.py
> +class in_eic_eligible_child(Variable):
```suggestion
class in_eitc_eligible_child(Variable):
```

2023-07-30 23:55 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/credits/eitc/in_eic_eligible_child.py
> +    label = "Child-level eligiblity for parents filing Indiana EIC"
```suggestion
    label = "Child-level eligiblity for parents filing Indiana EITC"
```

2023-07-30 23:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/credits/eitc/in_eic.py
> +class in_eic(Variable):
```suggestion
class in_eitc(Variable):
```

2023-07-30 23:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/credits/eitc/in_eic.py
need to switch all names to EITC - as it is a branch of the earned income tax credit - for uniformity across the model

2023-07-30 23:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/credits/eitc/in_eic.py
> +    label = "Indiana EIC"
```suggestion
    label = "Indiana EITC"
```

2023-08-01 23:23 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/in/tax/income/credits/eitc/in_eitc_eligible_child.yaml
> +- name: Over 18 and not disabled and student
need to add state_code: IN to all tests

2023-08-01 23:24 UTC, PavelMakarchuk commented on changelog_entry.yaml
after all changes are done, need to run `make format`

2023-08-01 23:24 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/credits/eitc/in_eitc.py
> +    label = "Indiana EIC"
```suggestion
    label = "Indiana EITC"
```

2023-08-03 16:20 UTC, MaxGhenis requested changes

2023-08-03 16:20 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/in/tax/income/credits/eitc/age/child.yaml
The form looks like it uses the federal EITC definition. Please find the Indiana legal code to confirm, and if so, we can delete these parameters and point to `is_eitc_qualifying_child`

2023-08-03 16:26 UTC, MaxGhenis requested changes
Per the [legal code](https://iga.in.gov/laws/2022/ic/titles/6#6-3.1-21), we can represent this program with only the 10% match parameter. Please remove other parameters and examine the state legal code before developing in the future to avoid unnecessary work.

2023-08-03 19:23 UTC, PavelMakarchuk approved these changes

2023-08-03 20:33 UTC, MaxGhenis commented
Please resolve all outstanding comment threads and tag me for a review

2023-08-03 20:35 UTC, PavelMakarchuk commented
> Per the [legal code](https://iga.in.gov/laws/2022/ic/titles/6#6-3.1-21), we can represent this program with only the 10% match parameter. Please remove other parameters and examine the state legal code before developing in the future to avoid unnecessary work.

resolved

2023-08-03 20:35 UTC, PavelMakarchuk commented
> Please resolve all outstanding comment threads and tag me for a review

all has been resolved

2023-08-04 21:14 UTC, MaxGhenis requested changes
I may have spoke too soon previously. This looks like it matches an earlier iteration of the federal EITC. Please move `in_eitc.yaml` under a new folder `eitc` (matching the variable folder structure) and add some integration tests to `eitc/integration.yaml` going through a sample filer's IN EITC calculation based on the tax form.

If we need to use an old version of the federal EITC, we'll want to place this PR on hold until we can add historical EITC rules (which it would be great if you could do, in another PR). From there we have tools for accessing previous years' logic.

2023-08-10 16:09 UTC, MaxGhenis commented
Hi @SirMalamute - since this ended up being a trickier one I'm going to suggest we close it in favor of @martinholmer's #2815. Thanks for your work here!

2023-08-10 16:09 UTC, closed without merging