Linfeng-ll/issue2429
PolicyEngine/policyengine-us pull request #2542
Opened 2023-06-30 01:36 UTC by Linfeng-ll

Add New Mexico low income comprehensive tax rebate.

2023-07-13 21:36 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nm/tax/rebates/low_income_rebate/exemption_amount1.yaml
> +      2022-01-01: 32_501
we need to add the 2021 values and [source](https://klvg4oyd4j.execute-api.us-west-2.amazonaws.com/prod/PublicFiles/34821a9573ca43e7b06dfad20f5183fd/608063af-0c4c-4f28-ba42-cf40e04557ca/PITbook2021.pdf)

2023-07-13 21:37 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nm/tax/rebates/low_income_rebate/exemption_amount1.yaml
> +description: New Mexico low income comprehensive tax rebate when tax unit qualify 1 exemption
```suggestion
description: New Mexico provides the following low income comprehensive tax rebate for filers with one exemption.
```

2023-07-13 21:37 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nm/tax/rebates/low_income_rebate/exemption_amount1.yaml
> +description: New Mexico low income comprehensive tax rebate when tax unit qualify 1 exemption
Similar format in other yaml files

2023-07-13 21:38 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nm/tax/rebates/low_income_rebate/exemption_amount1.yaml
> +  label: New Mexico Income Tax Rebate with 1 exemption
```suggestion
  label: New Mexico comprehensive low income tax rebate one exemption amount
```

2023-07-13 21:40 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nm/tax/rebates/low_income_rebate/exemption_amount1.yaml
> +  label: New Mexico Income Tax Rebate with 1 exemption
similar format in other yaml files

2023-07-13 21:40 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nm/tax/rebates/low_income_rebate/exemption_amount1.yaml
make `amount` folder and rename file to `one_exemption.yaml`

2023-07-13 21:40 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nm/tax/rebates/low_income_rebate/exemption_amount1.yaml
same with other yaml files

2023-07-13 21:41 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nm/tax/income/nm_number_of_exemption.py
we can just use the class `exemptions`

2023-07-13 21:42 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nm/tax/income/rebates/nm_low_income_comprehensive_tax_rebate.py
> +        return where(filing_status == statuses, rebate / 2, rebate)
make the "2" a parameter and call `divisor`

2023-07-18 02:15 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nm/tax/rebates/low_income_rebate/amount/five_exemptions.yaml
> +      href: https://klvg4oyd4j.execute-api.us-west-2.amazonaws.com/prod/PublicFiles/34821a9573ca43e7b06dfad20f5183fd/1afc56af-ea90-4d48-82e5-1f9aeb43255a/PITbook2022.pdf#page=58
could you add one [legal code ](https://casetext.com/regulation/new-mexico-administrative-code/title-3-taxation/chapter-3-personal-income-taxes)reference

2023-07-18 02:15 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nm/tax/rebates/low_income_rebate/amount/five_exemptions.yaml
> +      href: https://klvg4oyd4j.execute-api.us-west-2.amazonaws.com/prod/PublicFiles/34821a9573ca43e7b06dfad20f5183fd/1afc56af-ea90-4d48-82e5-1f9aeb43255a/PITbook2022.pdf#page=58
all yaml files

2023-07-18 22:44 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nm/tax/rebates/low_income_rebate/amount/five_exemptions.yaml
> +      href: https://casetext.com/regulation/new-mexico-administrative-code/title-3-taxation/chapter-3-personal-income-taxes/part-13-tax-rebates-and-credits/section-33136-objective
I dont think that this link is the actual legal code reference

2023-07-18 22:44 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nm/tax/rebates/low_income_rebate/amount/five_exemptions.yaml
> +      href: https://casetext.com/regulation/new-mexico-administrative-code/title-3-taxation/chapter-3-personal-income-taxes/part-13-tax-rebates-and-credits/section-33136-objective
all yaml files

2023-07-20 03:29 UTC, PavelMakarchuk approved these changes

2023-07-20 03:52 UTC, MaxGhenis requested changes

2023-07-20 03:52 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/nm/tax/rebates/low_income_rebate/divisor.yaml
> +  label: New Mexico low income rebate divisor
```suggestion
  label: New Mexico low income rebate divisor for married filing separately
```

2023-07-20 03:52 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/nm/tax/rebates/low_income_rebate/divisor.yaml
> +description: New Mexico low income comprehensive tax rebate for married couple filling separately
```suggestion
description: New Mexico divides its low income comprehensive tax rebate by this number for married filing separately filers.
```

2023-07-20 03:52 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/nm/tax/income/rebates/nm_low_income_comprehensive_tax_rebate.py
> +        exemption_num = tax_unit("exemptions", period)
We avoid `_num` because it's ambiguous between a count and an index.
```suggestion
        exemptions = tax_unit("exemptions", period)
```

2023-07-20 03:52 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/nm/tax/income/rebates/nm_low_income_comprehensive_tax_rebate.py
> +        agi = tax_unit("adjusted_gross_income", period)
This is based on a modified form AGI specific to this program, not federal AGI. I'd suggest making a placeholder variable for this for now and adding it in a separate PR.

2023-07-20 03:52 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/nm/tax/rebates/low_income_rebate/amount/six_exemptions.yaml
> +description: New Mexico provides the following low income comprehensive tax rebate for filers with six exemptions.
```suggestion
description: New Mexico provides the following low income comprehensive tax rebate for filers with six or more exemptions.
```

2023-07-20 03:52 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/nm/tax/income/rebates/nm_low_income_comprehensive_tax_rebate.py
> +        statuses = filing_status.possible_values.SEPARATE
```suggestion
        divisor = where(filing_status == filing_status.SEPARATE, p.divisor, 1)
        return rebate / divisor
```

2023-07-21 03:54 UTC, MaxGhenis approved these changes

2023-07-21 03:54 UTC, merged