Add Ohio Joint Filing Credit
PolicyEngine/policyengine-us pull request #3086
Opened 2023-09-26 02:00 UTC by mylittlebecca

Fix #3057

2023-09-26 02:05 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/oh_joint_filing_credit.py
> +        print(income)
delete prints

2023-09-26 02:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/oh_joint_filing_credit.py
> +class oh_joint_filing_credit(Variable):
make a oh_joint_filing_credit_eligible.py with 
qualify_income & qualify_status

2023-09-26 02:14 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/oh/tax/income/credits/oh_joint_filing_credit.yaml
> +        oh_income_tax_exempt: 10_000
need to add state code OH

2023-09-27 14:21 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/oh_income_tax_before_refundable_credits.py
no test

2023-09-27 14:21 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/joint_filing_credit/oh_joint_filing_credit_eligible.py
> +    value_type = float
```suggestion
    value_type = bool
```

2023-09-27 14:22 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/joint_filing_credit/oh_joint_filing_credit_eligible.py
> +        qualify_income = (head_income >= p.income_base) & (
```suggestion
        income_eligible = (head_income >= p.income_base) & (
```

2023-09-27 14:22 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/joint_filing_credit/oh_joint_filing_credit_eligible.py
> +        qualify_status = filing_status == filing_status.possible_values.JOINT
```suggestion
        status_eligible = filing_status == filing_status.possible_values.JOINT
```

2023-09-27 14:24 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/joint_filing_credit/income_base.yaml
> +  label: Ohio joint filing credit base qualifying income
```suggestion
  label: Ohio joint filing credit income threshold
```

2023-09-27 14:24 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/joint_filing_credit/rate.yaml
> +  label: Ohio joint filing credit income threshold
```suggestion
  label: Ohio joint filing credit rate
```

2023-09-27 14:25 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/joint_filing_credit/rate.yaml
> +  rate_unit: /1
```suggestion
  amount_unit: /1
```

2023-09-28 01:44 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/joint_filing_credit/income_threshold.yaml
> +description: Ohio qualifies the joint filing credit for head and spouse each with Ohio adjusted gross income above this amount.
```suggestion
description: Ohio qualifies filer for the joint filing credit with adjusted gross income above this amount. 
```

2023-09-28 01:52 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/joint_filing_credit/oh_joint_filing_credit.py
> +    reference = "https://codes.ohio.gov/ohio-revised-code/section-5747.05"
cant open link

2023-09-28 01:52 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/joint_filing_credit/oh_joint_filing_credit.py
> +        magi_less_exepmtion = oh_agi - exemption
cap at 0

2023-09-28 02:09 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/joint_filing_credit/oh_joint_filing_credit_eligible.py
> +    label = "Eligible for Ohio Joint Filing Credit"
```suggestion
    label = "Eligible for the Ohio Joint Filing Credit"
```

2023-10-02 19:34 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/joint_filing_credit/income_threshold.yaml
> +description: Ohio qualifies filer for the joint filing credit with adjusted gross income at or above this amount.
```suggestion
description: Ohio qualifies filers for the joint filing credit with adjusted gross income at or above this amount. 
```

2023-10-02 19:36 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/joint_filing_credit/oh_joint_filing_credit_eligible.py
> +        income = person("employment_income", period)
does it also include self-employment income?

2023-10-02 23:26 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/joint_filing_credit/oh_joint_filing_credit_eligible.py
> +        income = person("employment_income", period)
need to recreate 
oh_agi -> oh_alternative_agi
irs_gross_income -> oh_irs_gross_income
adjusted_gross_income -> oh_adjusted_gross_income

in the irs_gross_income we want to use a for loop for the income sources to exclude the income types as said on the form

2023-10-05 21:46 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/oh_exemption.py
> +class oh_exemption(Variable):
```suggestion
class oh_exemptions(Variable):
```

2023-10-05 21:46 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/oh_exemption.py
> +    label = "Ohio exemption"
```suggestion
    label = "Ohio exemptions"
```

2023-10-05 21:51 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/adjusted_gross_income/oh_adjusted_gross_income.py
> +class oh_adjusted_gross_income(Variable):
```suggestion
class oh_alternative_adjusted_gross_income(Variable):
```

2023-10-05 21:51 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/adjusted_gross_income/oh_adjusted_gross_income.py
> +    label = "Ohio Alternative Adjusted gross income"
```suggestion
    label = "Ohio Alternative Adjusted gross income for the joint filing credit"
```

2023-10-05 21:52 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/adjusted_gross_income/oh_alternative_agi.py
> +    label = "Ohio alternative adjusted gross income"
```suggestion
    label = "Ohio alternative adjusted gross income for the joint filing credit"
```

2023-10-05 21:52 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/adjusted_gross_income/oh_irs_gross_income.py
> +    label = "Ohio Gross income"
```suggestion
    label = "Ohio Gross income for the joint filing credit"
```

2023-10-05 21:52 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/adjusted_gross_income/oh_adjusted_gross_income.py
move these three files in the joint_filing_credit folder

2023-10-05 21:52 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/adjusted_gross_income/oh_adjusted_gross_income.py
same with the tests

2023-10-05 21:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/joint_filing_credit/income_threshold.yaml
> +description: Ohio qualifies filers for the joint filing credit with adjusted gross income at or above this amount.
```suggestion
description: Ohio qualifies filers for the joint filing credit with alternative adjusted gross income at or above this amount. 
```

2023-10-05 21:59 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/adjusted_gross_income/oh_alternative_agi.py
> +    adds = [
can you make a list parameter - same for the subtracts part

2023-10-09 15:39 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/joint_filing_credit/oh_alternative_agi.py
I dont think we need this as well as the alternative additions and subtractions - I thought we only need alternative gross income and federal agi? - Let me know if I am wrong

2023-11-04 00:42 UTC, PavelMakarchuk commented on changelog_entry.yaml
could you fix the merge conflicts? And re request my review

2023-11-27 17:12 UTC, PavelMakarchuk commented on changelog_entry.yaml
tests don't pass

2023-11-27 17:42 UTC, PavelMakarchuk requested changes

2023-11-27 17:42 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/joint_filing_credit/oh_irs_gross_income.py
> +    label = "Ohio gross income for the joint filing credit"
```suggestion
    label = "Ohio gross income replicated for the Ohio joint filing credit"
```

2023-11-27 17:42 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/joint_filing_credit/oh_alternative_agi.py
> +    adds = ["oh_alternative_agi_additions"]
does this not add adjusted_gross_income?

2023-11-27 17:42 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/joint_filing_credit/oh_alternative_adjusted_gross_income.py
make a folder called income for all the income types related to agi and gross income

2023-11-27 23:43 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/oh_income_tax_before_non_refundable_credits.py
> +class oh_income_tax_before_non_refundable_credits(Variable):
need to change the tests and other variables accordingly

2023-11-30 22:08 UTC, PavelMakarchuk requested changes

2023-11-30 22:08 UTC, PavelMakarchuk commented on changelog_entry.yaml
need a make format

2023-11-30 22:08 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/joint_filing_credit/oh_joint_filing_credit_eligible.py
> +    label = "Eligible for the Ohio Joint Filing Credit"
```suggestion
    label = "Eligible for the Ohio joint filing credit"
```

2023-11-30 22:08 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/credits/joint_filing_credit/rate.yaml
> +  type: single_amount
```suggestion
  type: single_amount
  period: year
```

2023-12-24 04:09 UTC, PavelMakarchuk approved these changes

2023-12-24 04:23 UTC, PavelMakarchuk commented
failed checks relate to labor supply responses.py

2023-12-24 23:15 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/credits/joint_filing_credit/oh_joint_filing_credit.py
> +        # the addition of the business income deduction, which is currently not included in the model,
Filed #3527

2023-12-24 23:34 UTC, MaxGhenis approved these changes

2023-12-24 23:34 UTC, merged