add oh 529 plan deduction
PolicyEngine/policyengine-us pull request #3132
Opened 2023-10-06 11:27 UTC by Linfeng-ll

add oh 529 plan deduction

2023-10-06 14:11 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/deductions/oh_529_plan_deduction.py
> +        deduction_529 = min_(contribution_529, p.plan_529_deduction_threshold)
```suggestion
        capped_amount = min_(contribution_529, p.plan_529_deduction_threshold)
```

2023-10-06 14:11 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/deductions/oh_529_plan_deduction.py
> +        contribution_529 = tax_unit("investment_in_529_plan", period)
```suggestion
        contribution_amount = tax_unit("investment_in_529_plan", period)
```

2023-10-06 14:11 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/deductions/oh_529_plan_deduction.py
> +    label = "Contributions to an Ohio 529 plan deduction"
```suggestion
    label = "Ohio contributions to 529 plan deduction"
```

2023-10-06 14:11 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/deductions/plan_529_deduction_threshold.yaml
make a folder called `529_plan` and then a file called `max_amount`

2023-10-06 14:12 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/deductions/plan_529_deduction_threshold.yaml
> +  label: Ohio 529 plan deduction threshold
```suggestion
  label: Ohio 529 plan contribution deduction max amount
```

2023-10-06 14:13 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/oh/tax/income/deductions/plan_529_deduction_threshold.yaml
make a deductions.yaml file and include the oh_529_plan_deduction.yaml as first deduction

2023-10-11 15:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/deductions/oh_529_plan_deduction.py
> +        return max_(capped_amount, 0)
```suggestion
```

2023-10-27 18:33 UTC, PavelMakarchuk approved these changes

2023-10-28 17:23 UTC, MaxGhenis requested changes
Please also tie this to an issue and include github:all in the description.

For future reference, we don't need to model programs like these at this time, since they're not part of [taxsim35](https://taxsim.nber.org/taxsim35/). Filing issues before PRs gives a chance to discuss the importance of the programs.

2023-10-28 17:23 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/oh/tax/income/deductions/plan_529_contributions/max_amount.yaml
> +description: Ohio limits its contributions to an Ohio 529 plan deduction below this amount.
```suggestion
description: Ohio deducts 529 plan contributions up to this amount from taxable income.
```

2023-10-28 17:23 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/oh/tax/income/deductions/plan_529_contributions/max_amount.yaml
> +  label: Ohio 529 plan contribution deduction max amount
rename cap.yaml
```suggestion
  label: Ohio 529 plan contribution deduction cap
```

2023-10-28 17:23 UTC, MaxGhenis commented on changelog_entry.yaml
> +    - Ohio 295 plan deduction.
```suggestion
    - Ohio 529 plan deduction.
```

2023-11-04 00:43 UTC, PavelMakarchuk commented on changelog_entry.yaml
could you run a `make install` and then a `git pull upstream master` to see if the conflicts will be fixed

2023-11-14 20:34 UTC, MaxGhenis approved these changes

2023-11-14 20:34 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/oh/tax/income/deductions/oh_529_plan_deduction.py
> +    label = "Ohio contributions to 529 plan deduction"
```suggestion
    label = "Ohio deduction for contributions to 529 plans"
```

2023-11-14 20:34 UTC, merged