Added variables and parameters
PolicyEngine/policyengine-us pull request #3139
Opened 2023-10-10 00:18 UTC by jnaux

Fixes #3138

2023-10-10 01:07 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +      - Virginia Spouse Tax Adjustment.
```suggestion
      - Virginia spouse tax adjustment.
```

2023-10-10 01:07 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/addition_amount.yaml
> +  2022-01-01: 930
need 2021 values

2023-10-10 01:07 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/addition_amount.yaml
> +  - title: Virginia 2022 Form 760 Resident Individual Income Tax Booklet
all yaml files

2023-10-10 01:07 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/addition_amount.yaml
> +  2022-01-01: 930
all yaml files

2023-10-10 01:08 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/personal_exemption_head.py
why 2 times?

2023-10-10 01:08 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/tax_adjustment_calculation.py
> +        if (
cant use if statements, need to use where

2023-10-10 01:08 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/tax_adjustment_calculation.py
> +        half_of_taxable_income = 0.5 * va_taxable_income
need to make 0.5 a parameter if it is mentioned in the files

2023-10-10 01:09 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/personal_exemption_spouse.py
> +class personal_exemption_head(Variable):
```suggestion
class va_personal_exemption_head(Variable):
```

2023-10-10 01:09 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/personal_exemption_spouse.py
> +class personal_exemption_head(Variable):
each Virginia specific variable class should start with va_

2023-10-10 01:10 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/personal_exemption_head.py
rename one of the files to spouse

2023-10-10 01:10 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/personal_exemption_spouse.py
> +        aged_blind_count = tax_unit("blind_spouse", period) + (age_spouse > 64)
make 64 a policy parameter

2023-10-10 01:12 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/personal_exemption_head.py
we can also probably combine the head and spouse exemption into one variable

2023-10-10 07:00 UTC, jnaux commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/addition_amount.yaml
> +  - title: Virginia 2022 Form 760 Resident Individual Income Tax Booklet
> need 2021 tax forms + legal code

I cannot find the relevant item on the legal code

2023-10-11 04:33 UTC, LeqiGogo commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/addition_amount.yaml
> +    href: https://www.tax.virginia.gov/sites/default/files/vatax-pdf/2021-760-instructions.pdf#page=20
and 2022 tax form

2023-10-11 04:34 UTC, LeqiGogo commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/age_blind_multiplier.yaml
> +description: Virginia multiple the person age/blind exemptions count by this amount to compute the personal exemptions for the tax filer and their spouse.
```suggestion
description: Virginia multiplies the person age/blind exemptions count by this amount to compute the personal exemptions for the tax filer and their spouse.
```

2023-10-11 04:35 UTC, LeqiGogo commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/age_threshold.yaml
> +description: Virginia allows an age deduction for taxpayers this age and older.
```suggestion
description: Virginia allows an age deduction for taxpayers of this age and older.
```

2023-10-12 02:02 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_tax_adjustment_calculation.py
make a va_agi file - just the metadata

2023-10-12 02:04 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_tax_adjustment_calculation.py
make a va_agi person - similar code to ia_prorate_fraction

2023-10-12 02:07 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_personal_exemption_head.py
> +            age_head >= p.age_threshold
age_head is not defined

age_head = tax_unit("age_head", period)

2023-10-12 02:08 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_personal_exemption_head.py
> +        aged_blind_count = tax_unit("blind_head", period) + (
blind_head = tax_unit("blind_head", period)
blind_spouse = tax_unit("blind_spouse", period)
total_blind = blind_head + blind_spouse

2023-10-12 02:08 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_personal_exemption_head.py
> +        aged_blind_count = tax_unit("blind_head", period) + (
same for age

2023-10-12 02:10 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_personal_exemption_head.py
> +class va_personal_exemption_head(Variable):
```suggestion
class va_personal_exemption(Variable):
```

2023-10-20 13:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_personal_exemption_head.py
> +        p = parameters(period).gov.states.va.tax.income.spouse_head_adjustment
use the following person level variables:
age 
is_blind
is_tax_unit_head_or_spouse

2023-10-20 13:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_personal_exemption_head.py
> +    def formula(tax_unit, period, parameters):
```suggestion
    def formula(person, period, parameters):
```

2023-11-04 08:17 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/taxable_income_threshold.yaml
> +  - title: Virginia 2021 Form 760 Resident Individual Income Tax Booklet
need 2022 tax form and legal code

2023-11-04 08:17 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/taxable_income_threshold.yaml
> +  - title: Virginia 2021 Form 760 Resident Individual Income Tax Booklet
all yaml files

2023-11-04 08:18 UTC, PavelMakarchuk commented on policyengine_us/variables/household/income/person/general/agi.py
does this represent the federal or state AGI

2023-11-04 08:18 UTC, PavelMakarchuk commented on policyengine_us/variables/household/income/person/general/agi.py
if federal, we can remove it and use `adjusted_gross_income`

2023-11-04 08:18 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +      - Virginia spouse tax adjustment.
indent back

2023-11-10 14:07 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_tax_adjustment_amount.py
> +        )
```suggestion
        x = where(
                adjustment_limit_condition,
                p.adjustment_limit,
                adjustment_amount)
         y = min_(
           (x ,p.adjustment_limit,
        )
```
        return tax_unit(
            "va_spouse_adjustment_qualification", period) * y)
```

2023-11-10 14:07 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_tax_adjustment_amount.py
> +        return tax_adjustment_amount
```suggestion
```

2023-11-10 14:14 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_spouse_adjustment_qualification.py
create a file called 
va_exemptions_indv.
person level 

formula:
age = ..
head_or_spouse = ... 
age_eligible = age > p.age_eligibility 

blind = ...

head_or_spouse = ... 

return age_eligible & blind & head_or_spouse

2023-11-10 14:15 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_spouse_adjustment_qualification.py
make a file called 
va_spouse_tax_adjsutment_eligible 
TaxUnit level
bool

formula 
exemptions = va_exemptions_indv
smaller_exemption = tax_unit.min(exemptions)
return smaller_exemption > 0

2023-11-10 14:21 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_spouse_adjustment_qualification.py
third file: 

va_spouse_tax_adjustment:
taxunit level
float 
defined_for = "va_spouse_tax_adjsutment_eligible"

formula:
taxable_income =
exemption = va_agi_less_exemptions_indv
smaller_exemption = tax_unit.min(exemption)
reduced_income = taxable_income - smaller_exemption
reduced_income_fraction = reduced_income / p.divisor 
# smaller 5 or 7
# larger 6 or 7 
add the two together 
....

2023-11-14 15:07 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_spouse_tax_adjustment.py
> +        smaller_agi_less_exemptions = tax_unit.min(agi_less_exemptions)
```suggestion
        # Comment that explains what's going on
        smaller_agi_less_exemptions = tax_unit.min(where(head_or_spouse, head_or_spouse_amount, np.inf))
```

2023-11-14 15:07 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_agi_less_exemptions_indiv.py
> +        head_or_spouse_amount = head_or_spouse_agi - total_personal_exemptions
```suggestion
        return head_or_spouse_agi - total_personal_exemptions
```

2023-11-14 15:07 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_agi_less_exemptions_indiv.py
> +        return where(head_or_spouse, head_or_spouse_amount, np.inf)
```suggestion
```

2023-11-17 14:09 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/addition_amount.yaml
delete this file and use policyengine_us/parameters/gov/states/va/tax/income/exemptions/personal.yaml instead

2023-11-17 14:09 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/adjustment_limit.yaml
rename this to cap.yaml

2023-11-17 14:10 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/adjustment_limit.yaml
> +description: Virginia cannot provide spouse tax adjustment that exceeds this amount.
```suggestion
description: Virginia caps the spouse tax adjustment at the following amount.
```

2023-11-17 14:10 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/adjustment_limit.yaml
> +  label: Virginia spouse tax adjustment
```suggestion
  label: Virginia spouse tax adjustment cap
```

2023-11-17 14:16 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/adjustment_limit.yaml
> +  - title: Virginia Department of Taxation
need to find the legal code on this website:
https://law.lis.virginia.gov/vacode/title58.1/chapter3/  

it has to be somewhere

2023-11-17 14:16 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/age_blind_multiplier.yaml
delete this file - we can use policyengine_us/parameters/gov/states/va/tax/income/exemptions/aged_blind.yaml instead

2023-11-17 14:17 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/age_threshold.yaml
> +description: Virginia allows an age deduction for taxpayers of this age and older.
```suggestion
description: Virginia qualifies filers for the age deduction of this age or older.
```

2023-11-17 14:18 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/age_threshold.yaml
> +  label: Virginia spouse tax adjustment
```suggestion
  label: Virginia spouse tax adjustment age threshold
```

2023-11-17 14:18 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/age_threshold.yaml
move this to the exemptions folder

2023-11-17 14:19 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/divider.yaml
> +  label: Virginia spouse tax adjustment
```suggestion
  label: Virginia spouse tax adjustment divisor
```

2023-11-17 14:19 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/divider.yaml
rename to divisor.yaml

2023-11-17 14:19 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/taxable_income_threshold.yaml
rename this to income_threshold

2023-11-17 14:21 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/taxable_income_threshold.yaml
> +description: Virginia uses this amount as a threshold for taxable income to determine qualification for spouse tax adjustment.
```suggestion
description: Virginia provides a flat spouse tax adjustment amount for filers with income above this taxable income amount.
```

2023-11-17 14:21 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/taxable_income_threshold.yaml
> +  label: Virginia spouse tax adjustment
```suggestion
  label: Virginia spouse tax adjustment upper income threshold
```

2023-11-17 14:22 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/taxable_income_threshold.yaml
nevermind, delete

2023-11-17 14:22 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/spouse_tax_adjustment/threshold.yaml
delete

2023-11-17 14:23 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_agi_less_exemptions_indiv.py
> +    label = "Difference between individual VAGI and personal exemptions"
```suggestion
    label = "Difference between individual VAGI and personal exemption amounts"
```

2023-11-17 14:23 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_spouse_tax_adjustment_eligible.py
> +    label = "Eligibility for Virginia's spouse tax adjustment"
```suggestion
    label = "Eligible for Virginia's spouse tax adjustment"
```

2023-11-22 02:56 UTC, jnaux commented
A issue is created with regard to the legal code for spouse tax adjustment: see issue 3267.

2023-11-28 15:46 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_agi_less_exemptions_indiv.py
> +        # age -
```suggestion
```

2023-12-01 09:08 UTC, jnaux commented on policyengine_us/variables/gov/states/va/tax/income/va_agi.py
> +    entity = Person
Yes, for the spouse tax adjustment calculation, it requires inputting the portion of the Virginia Adjusted Gross Income (VAGI) that is related to each spouse.

2023-12-01 13:26 UTC, jnaux commented on policyengine_us/parameters/gov/states/va/tax/income/exemptions/spouse_tax_adjustment/age_threshold.yaml
> +description: Virginia qualifies filers for the age exemption of this age or older.
In the VA spouse tax adjustment calculation, we use the age/blind count variable without a parameter file. #3342

2023-12-02 16:34 UTC, MaxGhenis requested changes

2023-12-02 16:34 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/va/tax/income/exemptions/spouse_tax_adjustment/age_threshold.yaml
> +description: Virginia qualifies filers for the age exemption of this age or older.
I think that's for a different deduction. The source you're citing (https://law.lis.virginia.gov/vacode/58.1-322.03/ 5b) is also based on birth year of 1939.

Virginia defines its exemptions following from the US Internal Revenue Code. For example you can see we don't have the 65 defined in the existing Virginia exemptions. So we don't need this file.

Instead I would suggest the following:
1. Add a person-level variable `is_irs_aged` to the IRS section, pointing to their 65 year threshold
2. Refactor the existing Virginia exemptions to be person-level (the total tax-unit exemptions variable can continue to use `adds`, which will sum across entities)
3. Use those person-level exemption variables in `va_agi_less_exemptions_indiv` - should be able to just do it with `adds` and `subtracts`. If you need to limit to heads and spouses you can do that in a later step.

2023-12-02 16:34 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/va/tax/income/va_agi_individual.py
> +class va_agi_individual(Variable):
For consistency (also note https://github.com/PolicyEngine/policyengine-us/issues/3351)
```suggestion
class va_agi_indiv(Variable):
```

2023-12-02 16:34 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/va/tax/income/va_agi_individual.py
> +    label = "Virginia Adjusted Gross Income (VAGI)"
```suggestion
    label = "Virginia adjusted gross income per individual"
```

2023-12-02 16:34 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_spouse_tax_adjustment_eligible.py
> +        exemptions = person("va_agi_less_exemptions_indiv", period)
```suggestion
        agi_less_exemptions = person("va_agi_less_exemptions_indiv", period)
```

2023-12-02 16:34 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_spouse_tax_adjustment_eligible.py
> +        smaller_exemptions = tax_unit.min(exemptions)
Dependents will bring this to zero. May need a `where(head_or_spouse, exemptions, np.inf)` first.

2023-12-08 14:22 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/va/tax/income/exemptions/spouse_tax_adjustment/age_threshold.yaml
delete this file

2023-12-08 14:28 UTC, PavelMakarchuk requested changes

2023-12-08 14:28 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/income/taxable_income/deductions/standard_deduction/is_irs_aged.py
> +        return (tax_unit("age", period) >= age_threshold).astype(int)
```suggestion
        return tax_unit("age", period) >= age_threshold
```

2023-12-08 14:28 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/irs/income/taxable_income/deductions/standard_deduction/is_irs_aged.yaml
> +    is_irs_aged: 0
```suggestion
    is_irs_aged: false
```

2023-12-08 14:28 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/irs/income/taxable_income/deductions/standard_deduction/is_irs_aged.yaml
> +    is_irs_aged: 1
```suggestion
    is_irs_aged: true
```

2023-12-08 14:28 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/irs/income/taxable_income/deductions/standard_deduction/is_irs_aged.yaml
> +- name: Not eligible for age deduction.
```suggestion
- name: Not aged
```

2023-12-08 14:28 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/irs/income/taxable_income/deductions/standard_deduction/is_irs_aged.yaml
> +- name: Eligible for age deduction.
```suggestion
- name: Aged
```

2023-12-08 14:28 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/va/tax/income/spouse_tax_adjustment/va_spouse_tax_adjustment.yaml
> +
delete extra line before output

2023-12-08 14:28 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/va/tax/income/spouse_tax_adjustment/va_spouse_tax_adjustment_eligible.yaml
> +- name: Virginia spouse tax adjustment eligibility unit test 1
explain test in a short note

2023-12-08 14:28 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/income/taxable_income/deductions/standard_deduction/is_irs_aged.py
> +    label = "Aged and or blind head and spouse count"
```suggestion
    label = "Aged person under the IRS requirements"
```

2023-12-08 14:28 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/income/taxable_income/deductions/standard_deduction/is_irs_aged.py
> +    unit = USD
```suggestion
```

2024-01-11 10:26 UTC, MaxGhenis approved these changes

2024-01-11 10:26 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/va/tax/income/exemptions/va_aged_blind_exemption_person.py
> +        aged_or_blind = aged_person + blind_person
or suggests bool
```suggestion
        aged_blind_count = aged_person + blind_person
```

2024-01-11 10:26 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_agi_less_exemptions_person.py
> +        vagi = person("va_agi_person", period)
```suggestion
        va_agi = person("va_agi_person", period)
```
Avoid that variable name

2024-01-11 10:26 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/va/tax/income/spouse_tax_adjustment/va_spouse_tax_adjustment.py
> +        # Line 8, take the smaller of the tax caluculated on line 5 or line 7
```suggestion
        # Line 8, take the smaller of the tax calculated on line 5 or line 7
```

2024-01-11 11:55 UTC, merged