Add married-combined logic to the MS income tax
PolicyEngine/policyengine-us pull request #3160
Opened 2023-10-17 15:30 UTC by ZiqianCui

Fixes #3136

2023-11-07 00:46 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ms/tax/income/deductions/ms_deductions_indiv.yaml
can we create an integration test with head and spouse income and the inputs from the tax form with a number of outputs to test our logic

2023-11-07 00:47 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/deductions/standard/ms_standard_deduction_indiv.py
> +        return (is_head | is_spouse) * p.amount[filing_status]
```suggestion
        head_or_spouse = person("is_tax_unit_head_or_spouse", period)
        p = parameters(period).gov.states.ms.tax.income.deductions.standard
        return head_or_spouse * p.amount[filing_status]
```

2023-12-05 18:52 UTC, Xinyi-Shao commented on policyengine_us/variables/gov/states/ms/tax/income/ms_taxable_income_joint.py
> +        agi = person.tax_unit("ms_agi", period)
Shall it be person.tax_unit.sum?

2023-12-05 18:58 UTC, Xinyi-Shao commented on policyengine_us/variables/gov/states/ms/tax/income/ms_taxable_income_joint.py
> -        deductions = tax_unit("ms_deductions", period)
Unsure if it needs a for statement

2023-12-08 09:49 UTC, Xinyi-Shao commented on policyengine_us/variables/gov/states/ms/tax/income/deductions/ms_deductions_indiv.py
> +        "https://www.law.cornell.edu/regulations/mississippi/35-Miss-Code-R-SS-3-02-11-103"
May add more source that directly explains an individual should claim itemized deductions or standard deduction, whichever is larger

2023-12-12 19:31 UTC, PavelMakarchuk commented
@MaxGhenis would we have to branch for the following married combined logic. The Standard deduction and exemptions can be divided between head and spouse as the filers want (minimizing taxable income). Or would prorating it and making sure there is no "waste" if possible be sufficient?

![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/d1f56bb4-a6ce-438e-a8f5-234edd29219e)

2023-12-12 19:40 UTC, MaxGhenis commented
For now let's assume the spouse with the higher agi claims the deductions. IIRC @nikhilwoodruff  did something more sophisticated in another program, Nikhil do you remember?

2023-12-12 19:42 UTC, PavelMakarchuk commented
> For now let's assume the spouse with the higher agi claims the deductions. IIRC @nikhilwoodruff did something more sophisticated in another program, Nikhil do you remember?

this is part of the married combined logic, however it differs from Martins approach in IA, different rules

2023-12-20 00:06 UTC, PavelMakarchuk requested changes

2023-12-20 00:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/deductions/ms_deductions_joint.py
> +    label = "Mississippi deductions filing jointly"
```suggestion
    label = "Mississippi deductions when married couples file jointly"
```

2023-12-20 00:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/deductions/standard/ms_standard_deduction_indiv.py
> +    label = "Mississippi personal standard deduction when married couples file separately"
```suggestion
    label = "Mississippi standard deduction when married couples file separately"
```

2023-12-20 00:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/exemptions/ms_total_exemptions_indiv.py
> +    label = "Mississippi total exemptions"
```suggestion
    label = "Mississippi total exemptions when married couples file separately"
```

2023-12-20 00:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/exemptions/ms_total_exemptions_joint.py
>      label = "Mississippi total exemptions"
```suggestion
    label = "Mississippi total exemptions hen married couples file jointly"
```

2023-12-20 00:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/exemptions/ms_total_exemptions_indiv.py
> +        # Per the atx form, the exemption amount is split in half between the head
```suggestion
        # Per the tax form, the exemption amount is split in half between the head
```

2023-12-20 00:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/ms_agi_indiv.py
> +    label = "Mississippi adjusted gross income"
```suggestion
    label = "Mississippi adjusted gross income when married couples file separately"
```

2023-12-20 00:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/ms_agi_indiv.py
> +        ms_agi = person.tax_unit("ms_agi_joint", period)
```suggestion
        p = parameters(period).gov.states.ms.tax.income
        income_sources = add(person, period, p.income_sources)
        adjustments = person("ms_agi_adjustments", period)
        adjusted_income = max_(0, income_sources - adjustments)
        return head_or_spouse * adjusted_income
```

2023-12-20 00:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/ms_agi_indiv.py
> +        return head_or_spouse * (0.5 * ms_agi)
```suggestion

```

2023-12-20 00:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/ms_agi_joint.py
can AGI be negative? if not we need to change this to a formula with max_

2023-12-20 00:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/ms_files_separately.py
> +    label = "married couple files separately on Mississippi tax return"
```suggestion
    label = "Married couple filing separately on the mississippi tax return"
```

2023-12-20 00:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/ms_files_separately.py
> +    reference = ()
add

2023-12-20 00:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/ms_income_tax.py
> +    label = "Mississippi income tax filing seperately"
```suggestion
    label = "Mississippi income tax when married couples file separately"
```

2023-12-20 00:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/ms_income_tax_before_credits.py
> +        income_separate = add(tax_unit, period, ["ms_taxable_income_indiv"])
```suggestion
        income_filing_separately = add(tax_unit, period, ["ms_taxable_income_indiv"])
```

2023-12-20 00:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/ms_income_tax_before_credits.py
> +        income_joint = tax_unit("ms_taxable_income_joint", period)
```suggestion
        income_filing_jointly = tax_unit("ms_taxable_income_joint", period)
```

2023-12-20 00:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/ms_taxable_income_indiv.py
> +    label = "Mississippi taxable income individually"
```suggestion
    label = "Mississippi taxable income when married couples file separately"
```

2024-01-06 14:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/ms_agi_indiv.py
we need to have a structure like [this](https://github.com/PolicyEngine/policyengine-us/pull/3516/files#diff-021f7f80aeb0e2208b18a44cad6c89f0811f1dca928f97d3ecc64c438a4fdd04:~:text=policyengine_us/variables/gov/states/ar/tax/income/ar_agi.py) for the AGI

2024-01-06 14:58 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/ms_income_tax.py
> +    label = "Mississippi income tax filing seperately when married couples file separately"
no need for this change

2024-01-06 14:59 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/ms_agi_indiv.py
we just make the agi person level but we can keep one file where we attribute the dependent income to the head 
![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/d53fd5e6-792f-40fa-b6e1-e9b2f79a7742)

2024-01-18 23:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ms/tax/income/ms_taxable_income_joint.py
can you add the following files:

state_filing_status_if_married_filing_separately_on_same_return

ms_can_file_separate_on_same_return

[this](https://github.com/PolicyEngine/policyengine-us/pull/3516/files#diff-9e807e0d8b3996ed47a0026c5abe5d2e9ad2eb416282bf9b82a24c37bcb2c686) PR can be an example

2024-02-06 18:04 UTC, PavelMakarchuk commented
Duplicate PR

2024-02-06 18:04 UTC, closed without merging