Adjust formatting for the Maine child care credit variable and test
PolicyEngine/policyengine-us pull request #3383
Opened 2023-12-06 22:27 UTC by jialyu0411

Fixes https://github.com/PolicyEngine/policyengine-us/issues/3378

2023-12-08 18:10 UTC, PavelMakarchuk requested changes

2023-12-08 18:10 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +
need changelog

2023-12-08 18:10 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/me/tax/income/credits/child_care_credit/non_refundable_child_care_credit.py
> +class non_refundable_child_care_credit(Variable):
```suggestion
class me_non_refundable_child_care_credit(Variable):
```

2023-12-08 18:10 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/me/tax/income/credits/child_care_credit/non_refundable_child_care_credit.py
> +        child_care_credit = tax_unit("child_care_credit", period)
```suggestion
        child_care_credit = tax_unit("me_child_care_credit", period)
```

2023-12-08 18:10 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/me/tax/income/credits/child_care_credit/non_refundable_child_care_credit.py
> +            "refundable_child_care_credit", period
```suggestion
            "me_refundable_child_care_credit", period
```

2023-12-08 18:10 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/me/tax/income/credits/child_care_credit/refundable_child_care_credit.py
> +class refundable_child_care_credit(Variable):
```suggestion
class me_refundable_child_care_credit(Variable):
```

2023-12-08 18:10 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/me/tax/income/credits/child_care_credit/refundable_child_care_credit.py
> +        return min_(p.max_amount, tax_unit("child_care_credit", period))
```suggestion
        return min_(p.max_amount, tax_unit("me_child_care_credit", period))
```

2023-12-08 18:10 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/me/tax/income/credits/child_care_credit/step_4_share_of_child_care_expenses.py
> +class step_4_share_of_child_care_expenses(Variable):
revert back

2023-12-08 18:10 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/me/tax/income/credits/me_child_care_credit/me_non_refundable_child_care_credit.py
we just need to change the name of the folder which is called me_child_care_credit to child_care_credit

2023-12-08 18:10 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/me/tax/income/credits/child_care/share_of_federal_credit/non_step_4.yaml
>    period: year
in label change CDCC to child care credit

2023-12-08 18:10 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/me/tax/income/credits/me_child_care_credit/me_non_refundable_child_care_credit.py
make sure that all files are tested

2023-12-13 14:36 UTC, PavelMakarchuk approved these changes

2023-12-13 14:36 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/me/tax/income/me_non_refundable_credits.py
> +    label = "Maine non refundable credits"
```suggestion
    label = "Maine non-refundable credits"
```

2023-12-13 14:36 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +- bump: minor
```suggestion
- bump: patch
```

2023-12-13 14:36 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    added:
```suggestion
    fixed:
```

2023-12-13 14:36 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Maine child care credit.
```suggestion
    - Maine child care credit format.
```

2023-12-13 19:06 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Maine child care format.
```suggestion
    - Maine child care credit format. 
```

2023-12-13 19:07 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    fixed:
```suggestion
    fixes: 
```

2023-12-13 23:58 UTC, MaxGhenis approved these changes

2023-12-14 19:02 UTC, merged