Add federal income tax as a Montana itemized deduction
PolicyEngine/policyengine-us pull request #3445
Opened 2023-12-13 17:40 UTC by Shinuing

Fixes #3427

2023-12-13 19:34 UTC, PavelMakarchuk requested changes

2023-12-13 19:34 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/mt/tax/income/deductions/itemized/federal_income_tax_limit.yaml
> +      href: https://mtrevenue.gov/wp-content/uploads/mdocs/form%202%202021%20instructions.pdf#page=32
could you add the 2022 reference to see if we have inflation adjustments

2023-12-13 19:34 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/mt/tax/income/deductions/itemized/federal_income_tax_limit.yaml
make a federal_income_tax folder and rename this file to cap.yaml

2023-12-13 19:34 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/mt/tax/income/deductions/itemized/federal_income_tax_limit.yaml
> +description: Montana allows a federal income tax deduction of up to this amount based on filing status.
```suggestion
description: Montana caps the federal income tax deduction to this amount, based on filing status.
```

2023-12-13 19:34 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/mt/tax/income/deductions/itemized/federal_income_tax_limit.yaml
> +  label: Montana federal income tax deduction limit
```suggestion
  label: Montana federal income tax deduction cap
```

2023-12-13 19:34 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Add federal income tax as a Montana itemized deduction.
```suggestion
    - Montana federal income tax deduction.
```

2023-12-13 20:49 UTC, PavelMakarchuk approved these changes

2023-12-14 00:31 UTC, MaxGhenis approved these changes
good to merge after this

2023-12-14 00:31 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/mt/tax/income/deductions/itemized/mt_federal_income_tax_deduction.py
> +        federal_income_tax = tax_unit("income_tax", period)
As the tax form requests `Federal income tax withheld` plus `Federal estimated tax payments` I don't think it includes negative values from refundable credits.
```suggestion
        federal_income_tax = tax_unit("income_tax_before_refundable_credits", period)
```

2023-12-14 17:57 UTC, merged