Massachusetts EITC rate increase in 2023
PolicyEngine/policyengine-us pull request #3457
Opened 2023-12-15 03:34 UTC by jialyu0411

Fixes #3432

2023-12-15 13:50 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/eitc/match.yaml
> +  2023-01-01: 0.4
add the legal code

2023-12-15 13:50 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/eitc/match.yaml
> +  2023-01-01: 0.4
add a tax form reference

2023-12-15 13:50 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +- bump: minor
```suggestion
- bump: patch
```

2023-12-15 13:50 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    added:
```suggestion
    fixed:
```

2023-12-15 13:51 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Massachusetts EITC rate.
```suggestion
    - Massachusetts 2023 EITC rate.
```

2023-12-15 13:51 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/eitc/match.yaml
>    label: MA EITC percent
```suggestion
  label: Massachusetts earned income tax credit match percent
```

2023-12-22 18:03 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/eitc/match.yaml
>  description: Percent of the EITC which is matched by MA income tax.
```suggestion
description: Massachusetts matched this Percent of the federal earned income credit.
```

2023-12-22 18:03 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/eitc/match.yaml
> +  label: Massachusetts earned income tax credit match percent
```suggestion
  label: Massachusetts earned income tax credit match 
```

2023-12-22 23:40 UTC, MaxGhenis requested changes

2023-12-22 23:40 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/eitc/match.yaml
>      - title: Mass. General Laws c.62 § 6(h)
```suggestion
    - title: Mass. General Laws c.62 § 6(h)(1)
```

2023-12-22 23:40 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/eitc/match.yaml
> +    - title: Bill H.4104, Session Laws, Acts (2023), Chapter 50, SECTION 11
don't need this since it's in the legal code already

2023-12-22 23:40 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/eitc/match.yaml
> +description: Massachusetts matched this Percent of the federal earned income credit.
```suggestion
description: Massachusetts matches this fraction of the federal earned income credit.
```

2023-12-22 23:40 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/eitc/match.yaml
> +  label: Massachusetts earned income tax credit match
```suggestion
  label: Massachusetts EITC match
```

2023-12-23 01:36 UTC, MaxGhenis approved these changes

2023-12-23 01:36 UTC, merged