Michigan heating credit
PolicyEngine/policyengine-us pull request #3526
Opened 2023-12-24 12:37 UTC by PavelMakarchuk

Fixes #2312

2024-01-02 23:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/mi/tax/income/credits/home_heating/mi_home_heating_credit_eligible.py
this part was not included: 
![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/3e845192-a68f-40d4-a7d1-38131311a97d)

2024-01-03 00:09 UTC, MaxGhenis requested changes

2024-01-03 00:09 UTC, MaxGhenis commented on policyengine_us/variables/household/expense/housing/heating_costs.py
> +class heating_costs(Variable):
```suggestion
class heating_expense(Variable):
```

2024-01-03 00:09 UTC, MaxGhenis commented on policyengine_us/variables/household/expense/housing/heating_costs.py
> +    entity = TaxUnit
```suggestion
    entity = Person
```

2024-01-03 00:09 UTC, MaxGhenis commented on policyengine_us/variables/household/expense/housing/heating_costs.py
also add `heating_expense_tax_unit`

2024-01-03 00:09 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/mi/tax/income/credits/home_heating/alternate_credit/mi_alternate_home_heating_credit.py
remove _credit from folder

2024-01-03 00:09 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/mi/tax/income/credits/home_heating/alternate/heating_costs/rate.yaml
> +description: Michigan multiplies the difference between the reduced heating costs and the reduced adjusted household resources by this rate under the alternate home heating credit computation.
```suggestion
description: Michigan provides a credit for this fraction of reduced heating costs less reduced adjusted household resources under the alternate home heating credit.
```

2024-01-03 00:09 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/mi/tax/income/credits/home_heating/alternate/household_resources/rate.yaml
> +description: Michigan reduces the heating costs by the following rate of household resoruces under the alternate home heating credit computation.
```suggestion
description: Michigan subtracts this fraction of resources from heating expenses under the alternate home heating credit.
```

2024-01-03 00:09 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/mi/tax/income/credits/home_heating/credit_percentage.yaml
> +description: Michigan multiplies the lerger of the standard or alternate home heating credit amount by this rate.
```suggestion
description: Michigan provides a credit for this fraction of the greater of the standard and alternate home heating credit.
```

2024-01-03 00:09 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/mi/tax/income/credits/home_heating/standard/base.yaml
> +description: Michigan provides the following home heating standard credit base, based on the number of exemptions.
```suggestion
description: Michigan provides this base amount of standard home heating credit, based on the number of exemptions.
```

2024-01-03 00:09 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/mi/tax/income/credits/home_heating/standard/fpg_rate.yaml
> +description: Michigan limits the home heating credit to filers with household resources below the following rate of the federal poverty guidelines.
```suggestion
description: Michigan limits the home heating credit to filers with household resources below this fraction of the federal poverty guidelines.
```

2024-01-03 00:09 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/mi/tax/income/credits/home_heating/standard/included_heating_cost_rate.yaml
> +description: Michigan multiplies the home heating credit amount by this rate if the heating costs are included in the filers rent payments.
```suggestion
description: Michigan multiplies the standard home heating credit by this fraction if rent includes heating.
```

2024-01-03 00:09 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/mi/tax/income/credits/home_heating/standard/included_heating_cost_rate.yaml
> +  label: Michigan standard home heating credit rate if heating costs are included in rent
```suggestion
  label: Michigan standard home heating credit rate if rent includes heating
```

2024-01-03 00:09 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/mi/tax/income/credits/home_heating/standard/reduction_rate.yaml
> +description: Michigan reduces the heating credit amount by this percentage of household resources.
```suggestion
description: Michigan reduces the standard heating credit amount by this fraction of household resources. 
```

2024-01-06 14:43 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/mi/tax/income/household_resources.yaml
move this also into the heating credit folder

2024-01-06 14:43 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/mi/tax/income/mi_household_resources.py
> +class mi_household_resources(Variable):
the household resources definition is applied across multiple programs and is not just defined for the heating credit

2024-01-06 14:44 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/mi/tax/income/household_resources.yaml
the household resources definition is applied across multiple programs and is not just defined for the heating credit

2024-01-06 15:09 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/mi/tax/income/mi_household_resources.py
> +class mi_household_resources(Variable):
what other programs? does the MI heating credit legal code point to that central definition?

the law defines it as IRS gross income minus a couple deductions. the form seems to stick to that except adding SSI. the parameter file also includes tanf and general relief, which I don't see mentioned in either source. would be good to back this up with other instances to make sure it's the same thing.

2024-01-08 22:35 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/mi/tax/income/mi_household_resources.py
> +class mi_household_resources(Variable):
I also see things like alimony income in the tax form, which I dont think is included in the irs gross income sources 

Should we just use irs_gross_income + the income sources which are not included but mentioned in the form?

I also dont think that the e.g.  business loss deduction currently affects the gross income

2024-01-09 02:37 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/mi/tax/income/mi_household_resources.py
> +class mi_household_resources(Variable):
does the MI heating credit legal code point to that central definition?

2024-01-09 08:19 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/mi/tax/income/mi_household_resources.py
> +class mi_household_resources(Variable):
The heating credit [legal code](https://law.justia.com/codes/michigan/2022/chapter-206/statute-act-281-of-1967/division-281-1967-1/division-281-1967-1-9/section-206-527a/) does not offer its own definition but does not reference any specific law (federal or state) as well

2024-01-10 01:10 UTC, MaxGhenis approved these changes

2024-01-10 01:10 UTC, merged