Immigration rules for SNAP/CalFresh and CalWORKS Child Care programs
PolicyEngine/policyengine-us pull request #3574
Opened 2024-01-10 11:27 UTC by PavelMakarchuk

Fixes #3572

2024-01-10 16:14 UTC, MaxGhenis commented
Could you point to a source? If it's in a document we're already sourcing you can mention it here in the PR - just want some paper trail.

2024-01-10 19:13 UTC, PavelMakarchuk commented
> Could you point to a source? If it's in a document we're already sourcing you can mention it here in the PR - just want some paper trail.

The official [DPSS](https://epolicy.dpss.lacounty.gov/epolicy/epolicy/server/general/projects_responsive/ePolicyMaster/index.htm?&area=general&type=responsivehelp&ctxid=&project=ePolicyMaster#t=mergedProjects%2FChild%20Care%2FChild_Care%2F1210_8_Regional_Market_Rate_Ceilings%2F1210_8_Regional_Market_Rate_Ceilings.htm%23Referencesbc-11&rhtocid=_3_3_8_10) site is not available right, now, using the following as a [reference](https://ehsd.org/benefits/calworks-cash-aid/calworks-fact-sheet/):
![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/bdd868f7-b242-4c9f-8069-29199028e9c5)

2024-01-10 23:31 UTC, MaxGhenis requested changes
Is there other info indicating treatment of mixed-status households?

2024-01-10 23:31 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/cdss/tanf/child_care/eligibility/ca_calworks_child_care_immigration_status_eligible.py
> +        resident = immigration_status == status.RESIDENT
can we change this code to `LEGAL_PERMANENT_RESIDENT`? everyone is a resident

2024-01-11 07:38 UTC, PavelMakarchuk commented
> Is there other info indicating treatment of mixed-status households?

can not find any information on that, currently checking for the head and the child immigration status, still cant access the epolicy site

2024-01-12 20:41 UTC, MaxGhenis approved these changes
Good to merge after this. We can amend it if we hear from SBN/DPSS different info about mixed-status households.

2024-01-12 20:41 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/states/ca/cdss/tanf/child_care/eligibility/ca_calworks_child_care_child_age_eligible.yaml
> +    immigration_status: RESIDENT
```suggestion
    immigration_status: LEGAL_PERMANENT_RESIDENT
```

2024-01-13 22:01 UTC, merged