Utah taxpayer credit calculations
PolicyEngine/policyengine-us pull request #3580
Opened 2024-01-11 15:43 UTC by JudyZ13

2024-01-12 10:01 UTC, PavelMakarchuk requested changes

2024-01-12 10:01 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    added:
```suggestion
    fixed:
```

2024-01-16 18:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/exemptions/oh_personal_exemptions.py
> +        credit_amount = p.amount.calc(agi, right=True)
```suggestion
        exemption_amount = p.amount.calc(agi, right=True)
```

2024-01-16 18:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/oh/tax/income/exemptions/oh_personal_exemptions.py
> +        return eligible_exemptions * credit_amount
```suggestion
        return eligible_exemptions * exemption_amount
```

2024-01-16 18:07 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ut/tax/income/credits/ut_federal_deductions_for_taxpayer_credit.yaml
give tests unique names

2024-01-16 18:16 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ut/tax/income/credits/taxpayer_credit/ut_federal_deductions_for_taxpayer_credit.py
> -        std_ded = tax_unit("standard_deduction", period)
we never added back the standard deduction here

2024-01-16 18:16 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ut/tax/income/credits/taxpayer_credit/ut_federal_deductions_for_taxpayer_credit.py
> +        p = parameters(period).gov.irs.deductions
add comments for each line

2024-01-18 12:15 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ut/tax/income/credits/taxpayer_credit/ut_federal_deductions_for_taxpayer_credit.py
> +        p = parameters(period).gov.irs.deductions
The following states that the filer can pick either the standard or the itemized deduction
you need 
```
        std_ded = tax_unit("standard_deduction", period)
        us_itemizing = tax_unit("tax_unit_itemizes", period)
```


![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/94dc8fa8-92de-4503-a8e0-d07fbcdb6cbb)

2024-01-18 12:16 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ut/tax/income/credits/taxpayer_credit/ut_federal_deductions_for_taxpayer_credit.py
> +        p = parameters(period).gov.irs.deductions
please in the code, add line comments from this source

2024-01-18 15:36 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ut/tax/income/credits/taxpayer_credit/ut_federal_deductions_for_taxpayer_credit.py
> +
```suggestion
     # Line 12 standard or itemized deduction
     st_ded = tax_unit...
     .
     .
     .
     # Line 13
```

2024-01-18 23:09 UTC, PavelMakarchuk requested changes

2024-01-18 23:09 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ut/tax/income/credits/taxpayer_credit/ut_federal_deductions_for_taxpayer_credit.py
> +        ite_ded = add(tax_unit, period, deductions)
```suggestion
        item_ded = add(tax_unit, period, deductions)
```

2024-01-18 23:09 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ut/tax/income/credits/taxpayer_credit/ut_federal_deductions_for_taxpayer_credit.py
> +        return where(us_itemizing, ite_ded + capped_real_estate_tax, std_ded)
```suggestion
        total_item_ded = item_ded + capped_real_estate_tax
        return where(us_itemizing, total_item_ded, std_ded)
```

2024-01-20 17:08 UTC, MaxGhenis approved these changes

2024-01-20 17:08 UTC, merged