Fix Michigan home heating credit
PolicyEngine/policyengine-us pull request #3623
Opened 2024-01-15 12:32 UTC by Mshuning

Fixes #3585

2024-01-16 13:59 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/mi/tax/income/credits/home_heating/integration.yaml
> +    mi_home_heating_credit: 911.07
add a test 

- name: integration test 2, an elderly couple with $12,020 income and four dependents
  period: 2022
  input:
    people:
      person1:
        age: 65
        employment_income: 6_000
      person2:
        age: 65
        employment_income: 6_020
      person3:
        age: 10
        employment_income: 0
      person4:
        age: 8
        employment_income: 0
      person5:
        age: 6
        employment_income: 0
      person6:
        age: 4
        employment_income: 0
    tax_units:
      tax_unit:
        # heating_expenses: 1_000
        # utilities_included_in_rent: false
        members: [person1, person2, person3, person4]
    households:
      household:
        members: [person1, person2, person3, person4]
        state_code: MI
  output: 
    mi_alternate_home_heating_credit_eligible: true
    # (1_000 - 12_020 * 0.11) * 0.7 < 0
    mi_alternate_home_heating_credit: 0
    mi_standard_home_heating_credit_eligible: true
    # 1433 - 12_020 * 0.035
    mi_standard_home_heating_credit: 1012.3
    mi_home_heating_credit_eligible_rate: 1
    # 1012.3 * 0.9
    mi_home_heating_credit: 911.07

2024-01-16 13:59 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/mi/tax/income/credits/home_heating/integration.yaml
> +- name: integretion test 2, an elderly couple with $12,020 income and four dependents
```suggestion
- name: integration test 2, an elderly couple with $12,020 income and four dependents
```

2024-01-17 21:39 UTC, PavelMakarchuk commented
> @PavelMakarchuk To fix the bug, I have to create a new file related to `mi_exemptions`, which is the number of people eligible for MI exemptions. But it will not be involved in the calculation of `mi_exemptions` itself, since different types of eligible people share different exemption amount. Should I create this new variable in `exemptions` folder? ![image](https://private-user-images.githubusercontent.com/31402450/297266684-3aa434a8-ced1-4127-8756-73f740a160d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1Mjc3MDgsIm5iZiI6MTcwNTUyNzQwOCwicGF0aCI6Ii8zMTQwMjQ1MC8yOTcyNjY2ODQtM2FhNDM0YTgtY2VkMS00MTI3LTg3NTYtNzNmNzQwYTE2MGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDIxMzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NTgyZTY1ZjA4Zjk2MDkxMmEyNDNkNzdlZmZlNjZjM2IyOGY5YmZlMWI3ZWFmNjRmNTc4YzBkNTVjYmIwZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cz_iC1kjlrynB3O9RdCLkFLdKhR-mTBU2lS6J7WwZ54)

We need to total number (int) of exemptions right? Not the total value of the exemptions (the dollar amount that you get per exemption)? If we need the number then we need to create a `mi_exemptions_count.py` and if we need the value we can take `mi_exemptions`

2024-01-20 23:31 UTC, MaxGhenis requested changes

2024-01-20 23:31 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/mi/tax/income/exemptions/mi_exemptions_count.py
> +
Would this work?
```suggestion
    adds = ["tax_unit_size", "mi_disabled_exemption_eligible_person", "is_fully_disabled_service_connected_veteran"]
```

2024-01-20 23:31 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/states/mi/tax/income/credits/home_heating/integration.yaml
> +        tax_unit_size: 3
this and `mi_exemptions_count` are inconsistent. they are also derived from the person-level information so neither is needed. in general for integration tests we should provide only "leaf-node" inputs - those without a formula. so also e.g. please remove tax_unit_fpg and mi_household_resources

2024-01-22 16:28 UTC, MaxGhenis approved these changes

2024-01-22 16:28 UTC, merged