Refactor co_ccap_parent_fee code
PolicyEngine/policyengine-us pull request #3625
Opened 2024-01-15 21:45 UTC by vrathi101

Fixes #3619

2024-01-31 15:22 UTC, PavelMakarchuk requested changes

2024-01-31 15:22 UTC, PavelMakarchuk commented on changelog_entry.yaml
run make format

2024-01-31 15:22 UTC, PavelMakarchuk commented on policyengine_us/data/datasets/cps/cps.py
> +    df["employment_income_prev"][
revert changes back

2024-01-31 15:22 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/co/ccap/base_parent_fee/first_and_second_multiplication_factor.yaml
> +description: Colorado Child Care Assistance Program multiplies adjusted gross income below or above federal poverty guidelines with these factors to calculate base parent fee.
```suggestion
description: Colorado Child Care Assistance Program multiplies adjusted gross income by the following factor to calculate base parent fee, based on gross income relative to the federal poverty guidelines.
```

2024-01-31 15:22 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/co/ccap/base_parent_fee/first_and_second_multiplication_factor.yaml
> +  label: Colorado Child Care Assistance Program multiplication factors
```suggestion
  label: Colorado Child Care Assistance Program multiplication factor
```

2024-01-31 15:22 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/co/ccap/is_quality_rating_discounted.yaml
>  metadata:
change the description

2024-01-31 23:32 UTC, PavelMakarchuk approved these changes

2024-02-01 03:38 UTC, MaxGhenis requested changes

2024-02-01 03:38 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/co/ccap/co_ccap_parent_fee.py
> +        gross_income_scaled = gross_income / fpg
```suggestion
        gross_income_fpg_ratio = gross_income / fpg
```

2024-02-01 03:38 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/co/ccap/base_parent_fee/first_and_second_multiplication_factor.yaml
How about reorganizing this to be `parent_fee/{base,add_on}.yaml`? where this is base

2024-02-01 03:38 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/co/ccap/base_parent_fee/first_and_second_multiplication_factor.yaml
> +description: Colorado Child Care Assistance Program multiplies adjusted gross income by the following factor to calculate base parent fee, based on gross income relative to the federal poverty guidel
Please also change other variables (Python and PolicyEngine) and descriptions/labels to refer consistently to countable income or adjusted gross income (appears to be the former).
```suggestion
description: Colorado calculates its Child Care Assistance Program base parent fee by applying this rate schedule to the ratio of countable income to the federal poverty guideline, then multiplying the result by the federal poverty guideline.
```

2024-02-01 03:38 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/co/ccap/base_parent_fee/first_and_second_multiplication_factor.yaml
>        href: https://docs.google.com/spreadsheets/d/1EEc3z8Iwu_KRTlBtd2NssDDEx_FITqVq/edit#gid=468321263
While you're here could you change the reference to publicly available documents?

2024-02-04 18:11 UTC, vrathi101 commented on policyengine_us/parameters/gov/states/co/ccap/parent_fee/base.yaml
> +    - title: COLORADO CHILD CARE ASSISTANCE PROGRAM RULES AND REGULATIONS - 3.111 PARENT FEES - P
Sure, should I remove references to spreadsheets in the CCCAP variables as well?

2024-02-11 20:21 UTC, PavelMakarchuk requested changes

2024-02-11 20:21 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/co/ccap/co_ccap_base_parent_fee.py
> +        base_parent_fee = base_parent_fee_scaled * fpg
```suggestion
        return base_parent_fee_scaled * fpg
```

2024-02-11 20:21 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/co/ccap/co_ccap_add_on_parent_fee.py
> +        add_on_parent_fee = (
```suggestion
        return (
```

2024-02-11 20:21 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/co/ccap/co_ccap_add_on_parent_fee.py
> +        add_on_parent_fee_if_applies = (
```suggestion
        add_on_parent_fee_amount = (
```

2024-02-11 20:21 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/co/ccap/co_ccap_add_on_parent_fee.py
> +        fpg = spm_unit("snap_fpg", period)
```suggestion
        snap_fpg = spm_unit("snap_fpg", period)
```

2024-02-11 20:21 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/co/ccap/co_ccap_base_parent_fee.py
> +        fpg = spm_unit("snap_fpg", period)
```suggestion
        snap_fpg = spm_unit("snap_fpg", period)
```

2024-02-11 20:21 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/co/ccap/co_ccap_base_parent_fee.py
> +        return base_parent_fee
```suggestion
```

2024-02-11 20:21 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/co/ccap/co_ccap_add_on_parent_fee.py
> +        return add_on_parent_fee
```suggestion
```

2024-02-12 17:15 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/co/ccap/co_ccap_add_on_parent_fee.py
> +        if period.start.month >= 10:
need to cover the different years with tests

2024-02-12 17:17 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/co/ccap/parent_fee/base.yaml
> +description: Colorado calculates its Child Care Assistance Program base parent fee by applying this rate schedule to the ratio of countable income to the federal poverty guideline, then multiplying t
```suggestion
description: Colorado multiplies the ratio of countable income to the federal poverty guideline by this rate under the Child Care Assistance Program to calculate the base parent fee.  
```

2024-02-12 17:18 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/co/ccap/parent_fee/add_on.yaml
> +description: Colorado Child Care Assistance Program multiplies additional number of eligible children with this factor to calculate add on parent fee.
```suggestion
description: Colorado multiplies the number of additional eligible children by this amount under the Child Care Assistance Program to calculate add on parent fee.
```

2024-02-13 16:50 UTC, PavelMakarchuk approved these changes

2024-02-13 16:51 UTC, PavelMakarchuk commented
@MaxGhenis let us know if is more representative than the original code

2024-02-13 17:31 UTC, MaxGhenis approved these changes

2024-02-13 17:31 UTC, merged