Adjust the state medicaid eligibility to include every immigration status
PolicyEngine/policyengine-us pull request #3651
Opened 2024-01-19 16:29 UTC by PavelMakarchuk

Fixes #3639

2024-01-19 19:43 UTC, MaxGhenis requested changes

2024-01-19 19:43 UTC, MaxGhenis commented on policyengine_us/parameters/gov/hhs/medicaid/eligibility/immigration.yaml
> +      href: https://files.kff.org/attachment/Table-3-Medicaid-and-CHIP-Eligibility-and-Enrollment-Policies-as-of-January-2021.pdf
That link didn't work - not sure if this is the right one though? I searched Google for the filename and it came up
```suggestion
      href: https://files.kff.org/attachment/Table-3-State-Adoption-of-Options-to-Cover-Immigrant-Populations-January-2021.pdf
```

2024-01-19 19:43 UTC, MaxGhenis commented on policyengine_us/parameters/gov/hhs/medicaid/eligibility/immigration.yaml
> +description: The following states cover undocumented immigrats under the medicaid program.
```suggestion
description: The following states provide Medicaid coverage to undocumented immigrants.
```

2024-01-19 19:43 UTC, MaxGhenis commented on policyengine_us/parameters/gov/hhs/medicaid/eligibility/immigration.yaml
rename `undocumented_immigrant.yaml`

2024-01-19 19:43 UTC, MaxGhenis commented on policyengine_us/parameters/gov/hhs/medicaid/eligibility/immigration.yaml
> +  label: Medicaid state immigration status eligibility
```suggestion
  label: Medicaid undocumented immigrant eligibility
```

2024-01-19 19:43 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/hhs/medicaid/eligibility/is_medicaid_eligible.yaml
> +- name: Inligible undocumented immigrant due to state rules
```suggestion
- name: Ineligible undocumented immigrant due to state rules
```

2024-01-19 19:43 UTC, MaxGhenis commented on policyengine_us/variables/gov/hhs/medicaid/eligibility/categories/medicaid_state_immigration_eligible.py
i'd just move this into `is_medicaid_eligible`. also note the descriptions don't align with the logic - this variable as written describes whether the person's state covers undocumented (not all) immigrants

2024-01-19 19:43 UTC, MaxGhenis commented on policyengine_us/variables/gov/hhs/medicaid/eligibility/is_medicaid_eligible.py
> +        immigrations_status_eligible = (
```suggestion
        immigration_status_eligible = (
```

2024-01-19 23:17 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/hhs/medicaid/eligibility/categories/medicaid_state_immigration_eligible.py
I was thinking of keeping it outside since the immigration rules can be more nuanced e.g. we could model immigration eligibility for different age groups which would then make this variable more useful to keep for clarity

2024-01-20 01:04 UTC, MaxGhenis requested changes

2024-01-20 01:04 UTC, MaxGhenis commented on policyengine_us/parameters/gov/hhs/medicaid/eligibility/undocumented_immigrant.yaml
> +      href: https://files.kff.org/attachment/Table-3-State-Adoption-of-Options-to-Cover-Immigrant-Populations-January-2021.pdf
```suggestion
      href: https://files.kff.org/attachment/Table-3-Medicaid-and-CHIP-Eligibility-and-Enrollment-Policies-as-of-January-2022.pdf
```

2024-01-20 01:04 UTC, MaxGhenis commented on policyengine_us/variables/gov/hhs/medicaid/eligibility/categories/medicaid_state_immigration_eligible.py
either describe that this characterizes state rules (not individual eligibility) or move to main file

2024-01-20 01:27 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/hhs/medicaid/eligibility/categories/medicaid_state_immigration_eligible.py
moved to main file

2024-01-20 01:27 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/hhs/medicaid/eligibility/undocumented_immigrant.yaml
> +      href: https://files.kff.org/attachment/Table-3-State-Adoption-of-Options-to-Cover-Immigrant-Populations-January-2021.pdf
added 2021 and 2022 reference

2024-01-20 02:14 UTC, MaxGhenis approved these changes
good to merge after these plus fixing lint

2024-01-20 02:14 UTC, MaxGhenis commented on policyengine_us/variables/gov/hhs/medicaid/eligibility/is_medicaid_eligible.py
> +        eligible_undocumented_immigrant = p.undocumented_immigrant[state].astype(bool)
```suggestion
        state_covers_undocumented = p.undocumented_immigrant[state].astype(bool)
```

2024-01-20 02:14 UTC, MaxGhenis commented on policyengine_us/variables/gov/hhs/medicaid/eligibility/is_medicaid_eligible.py
> +        immigration_status_eligible = (
```suggestion
        immigration_status_eligible = ~undocumented | state_covers_undocumented
```

2024-01-20 02:14 UTC, MaxGhenis commented on policyengine_us/parameters/gov/hhs/medicaid/eligibility/undocumented_immigrant.yaml
leave a comment about omitting states that only cover some age groups of undocumented immigrants, and file an issue to capture these rules

2024-01-20 12:57 UTC, merged