Add Massachusetts Senior Circuit Breaker Credit 2023 Parameters
PolicyEngine/policyengine-us pull request #3655
Opened 2024-01-21 02:17 UTC by DianaShi5083

2024-01-21 02:22 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/senior_circuit_breaker/amount/max.yaml
could you update the legal code reference? I think it's (k)(2): $1,500 in 2004 plus inflation. And I'm guessing 2023 legislation doubled it from $750 in 2004.

2024-02-05 18:14 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/senior_circuit_breaker/eligibility/max_income.yaml
> +      href: https://www.mass.gov/doc/2023-schedule-cb-circuit-breaker-credit/download
please also add the legal code or a comment to the legal code if it differs from the tax form amount

2024-03-14 02:58 UTC, MaxGhenis requested changes

2024-03-14 02:58 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/senior_circuit_breaker/amount/max.yaml
> +    # The legal code specifies infaltion unadjusted amounts
Specify the new legal code value since it changed for 2023
```suggestion
    # The legal code specifies inflation unadjusted amounts.
```

2024-03-14 13:38 UTC, MaxGhenis approved these changes

2024-03-14 13:38 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/senior_circuit_breaker/amount/max.yaml
> +    # amount from $ 750 to $ 1,500
```suggestion
    # amount from $750 to $1,500
```

2024-03-14 14:59 UTC, merged