SSI Substantial Gainful Activity
PolicyEngine/policyengine-us pull request #3665
Opened 2024-01-24 19:22 UTC by CalebPena

fixes: #3664

2024-01-24 22:38 UTC, MaxGhenis requested changes

2024-01-24 22:38 UTC, MaxGhenis commented on policyengine_us/variables/gov/ssa/ssi/eligibility/income/ssi_income_eligible.py
> +class ssi_income_eligible(Variable):
Let's flip it to indicate SGA, and also disambiguate from the separate income limit (not exactly a limit but the income level at which SSI would fall to zero through the phase-out). Also we'll include ssi in the name to distinguish from SSDI's definition, which applies to blind people.
```suggestion
class ssi_engaged_in_sga(Variable):
```

2024-01-24 22:38 UTC, MaxGhenis commented on policyengine_us/variables/gov/ssa/ssi/eligibility/income/ssi_income_eligible.py
> +        income = person("ssi_earned_income", period)
just a note for the future that we'll want to deduct impairment-related work expenses https://github.com/PolicyEngine/policyengine-us/issues/3669

no need to address here

2024-01-24 22:38 UTC, MaxGhenis commented on policyengine_us/variables/gov/ssa/ssi/eligibility/income/ssi_income_eligible.py
> +    definition_period = YEAR
```suggestion
    definition_period = YEAR
    reference = "https://www.ssa.gov/OP_Home/cfr20/416/416-0971.htm"
```

2024-01-24 22:54 UTC, CalebPena commented on policyengine_us/variables/gov/ssa/ssi/uncapped_ssi.py
>          eligible = person("is_ssi_eligible_individual", period)
Will I have to update all of the other eligibility variables like `is_ssi_eligible_spouse` and `is_ssi_ineligible_child`

2024-01-25 03:01 UTC, MaxGhenis commented on policyengine_us/variables/gov/ssa/ssi/uncapped_ssi.py
>          eligible = person("is_ssi_eligible_individual", period)
Good point - the simplest will be instead adding it as a criterion to `is_ssi_disabled`. Cleaner later on might be adding an intermediate variable `is_ssi_eligible_person` which is just `is_ssi_aged_blind_disabled & ~ssi_engaged_in_sga` and then using that in lieu of `is_ssi_aged_blind_disabled`.

2024-01-25 03:01 UTC, MaxGhenis commented on policyengine_us/variables/gov/ssa/ssi/eligibility/income/ssi_income_eligible.py
> +class ssi_income_eligible(Variable):
not quite what i suggested. let's make this income > sga

2024-01-25 18:36 UTC, MaxGhenis approved these changes
Could you just make these changes and check comment line length? Placing precedence on SGA over reported SSI receipt won't affect MFB but it'll help us model policy reforms and microsimulation.

I'll merge from there.

2024-01-25 18:36 UTC, MaxGhenis commented on policyengine_us/variables/gov/ssa/ssi/eligibility/status/is_ssi_disabled.py
>          aged = person("is_ssi_aged", period)
```suggestion
        # Classify person as disabled for SSI if:
        # 1) They reported receiving SSI due to presumed disability status (being neither aged nor blind); or
        # 2) They are disabled.
        # Earnings in excess of the Substantial Gainful Activity threshold disqualify from either case.
        # First check case 1: SSI reported and neither aged nor blind.
        aged = person("is_ssi_aged", period)
```

2024-01-25 18:36 UTC, MaxGhenis commented on policyengine_us/variables/gov/ssa/ssi/eligibility/status/is_ssi_disabled.py
> +        is_disabled = person("is_disabled", period)
```suggestion
        reported_disabled_ssi = reported_receipt & ~aged & ~blind
        is_disabled = person("is_disabled", period)
        engaged_in_ssa = person("ssi_engaged_in_sga", period)
        return (reported_disabled_ssi | is_disabled) & ~engaged_in_ssa
```

2024-01-25 19:54 UTC, MaxGhenis approved these changes

2024-01-25 19:54 UTC, MaxGhenis commented on policyengine_us/variables/gov/ssa/ssi/eligibility/status/is_ssi_disabled.py
> +        in_sga = person("ssi_engaged_in_sga", period)
remove this and next line

2024-01-25 20:07 UTC, merged