Arizona Resident Personal Income Tax Parameter Update
PolicyEngine/policyengine-us pull request #3678
Opened 2024-01-25 07:17 UTC by Kevintowne

Fixes #3677

2024-01-25 13:20 UTC, PavelMakarchuk requested changes

2024-01-25 13:20 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Arizona Resident Personal Income Tax Parameter Update.
```suggestion
    - Arizona 2023 income tax parameters.
```

2024-01-25 13:20 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/deductions/standard/amount.yaml
do not delete any of the 2021 and 2022 references or values - just add the 2023 values and references

2024-01-25 13:20 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/main/joint.yaml
add references to all parameters that you update

2024-01-25 13:20 UTC, PavelMakarchuk commented on changelog_entry.yaml
add 2023 tests

2024-01-29 19:14 UTC, MaxGhenis requested changes

2024-01-29 19:14 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/az/tax/income/deductions/standard/amount.yaml
>    2022-01-01: 25_900
Did they change the widow filing rules? In this tax form they should be head of household, not joint (page 9).

<img width="358" alt="image" src="https://github.com/PolicyEngine/policyengine-us/assets/6076111/333248bb-0b98-4dee-a8b5-507bd08e2cde">

We should make an `az_filing_status` variable that incorporates this logic.

2024-01-29 19:14 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/az/tax/income/deductions/standard/amount.yaml
> +  - title: 2023 Arizona Form 140 Resident Personal Income Tax Booklet
```suggestion
  - title: 2023 Arizona Form 140 Resident Personal Income Tax Booklet, Page 3
```

2024-01-29 19:14 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/az/tax/income/deductions/standard/increased/rate.yaml
> +  - title: 2023 Arizona Form 140 Resident Personal Income Tax Booklet
```suggestion
  - title: 2023 Arizona Form 140 Resident Personal Income Tax Booklet, Page 3
```

2024-01-29 19:14 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/az/tax/income/main/head_of_household.yaml
> +      2023-01-01: 0
can remove

2024-01-29 19:14 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/az/tax/income/main/head_of_household.yaml
> +    - title: 2023 Arizona Form 140 Resident Personal Income Tax Booklet
```suggestion
    - title: 2023 Arizona Form 140 Resident Personal Income Tax Booklet, Page 3
```

2024-01-29 19:14 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/az/tax/income/main/head_of_household.yaml
> +    - title: 2023 Arizona Form 140 Resident Personal Income Tax Booklet
Can you add a legislative reference? Looks like the legal code isn't updated to reflect the 2.5% flat tax so we may need to locate a bill.

2024-01-29 19:14 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/states/az/tax/income/az_income_tax_before_non_refundable_credits.yaml
> +    az_income_tax_before_non_refundable_credits: 1500
And elsewhere
```suggestion
    az_income_tax_before_non_refundable_credits: 1_500
```

2024-02-26 19:23 UTC, PavelMakarchuk requested changes

2024-02-26 19:23 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/deductions/standard/amount.yaml
> -SEPARATE:
deleted separate but need to delete widow

2024-02-26 19:23 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/deductions/standard/amount.yaml
>      href: https://azdor.gov/sites/default/files/2023-03/FORMS_INDIVIDUAL_2021_140BOOKLET.pdf#page=43
add 2023 values + reference

2024-02-26 19:23 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/main/head_of_household.yaml
> -      2019-01-01: 0.045
I dont think this is correct

2024-02-26 19:23 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/main/head_of_household.yaml
> +      href: https://www.azleg.gov/legtext/55leg/1R/summary/S.1828APPROP.DOCX.htm
add 2023 tax form

2024-02-26 19:23 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/main/head_of_household.yaml
>        2019-01-01: 0
add 2023 values

2024-02-26 19:23 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/main/joint.yaml
> -      2019-01-01: 0.045
check all the files -> should not have deleted the last lines of code

2024-02-26 19:23 UTC, PavelMakarchuk commented on changelog_entry.yaml
add the 2023 tax form to ALL of the az parameters even if the value is the same

2024-02-26 19:23 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/deductions/standard/amount.yaml
> +  - az_filing_status
check other AZ files with filing status and delete widow

2024-02-29 19:43 UTC, PavelMakarchuk requested changes

2024-02-29 19:43 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Arizona 2023 income tax parameters.
```suggestion
    - Arizona 2023 income tax parameters. 
    - Arizona filing status variable.
```

2024-02-29 19:43 UTC, PavelMakarchuk commented on changelog_entry.yaml
property tax form: 
https://azdor.gov/forms/tax-credits-forms/property-tax-refund-credit-claim-form-fillable

2024-02-29 19:43 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/credits/family_tax_credits/amount/cap.yaml
> +    href: https://azdor.gov/forms/individual/form-140a-arizona-resident-personal-income-tax-booklet#page=21
should be page 22

2024-02-29 19:43 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/credits/family_tax_credits/amount/cap.yaml
> +    href: https://azdor.gov/forms/individual/form-140a-arizona-resident-personal-income-tax-booklet#page=21
check all yaml files

2024-02-29 19:43 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/az/tax/income/az_filing_status.py
> +class StateFilingStatusIfMarriedFilingSeparatelyOnSameReturn(Enum):
```suggestion
class ArizonaFilingStatus(Enum):
```

2024-02-29 19:43 UTC, PavelMakarchuk commented on changelog_entry.yaml
delete widow files

2024-02-29 19:43 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/credits/dependent_credit/reduction/start.yaml
> +  - title: Arizona Form 140A - 2023 Resident Personal Income Tax Booklet
add page in the title

2024-02-29 19:43 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/az/tax/income/az_filing_status.py
> +    WIDOW = "Widow(er)"
```suggestion
```

2024-02-29 19:43 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/az/tax/income/az_filing_status.py
> +    possible_values = StateFilingStatusIfMarriedFilingSeparatelyOnSameReturn
adjust accordingly

2024-02-29 19:43 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/exemptions/parent_grandparent/cost_rate.yaml
> +      href: https://azdor.gov/forms/individual/form-140a-arizona-resident-personal-income-tax-booklet#page=10
```suggestion
      href: https://azdor.gov/forms/individual/form-140a-arizona-resident-personal-income-tax-booklet
```

2024-02-29 19:43 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/exemptions/parent_grandparent/cost_rate.yaml
> +      href: https://azdor.gov/forms/individual/form-140a-arizona-resident-personal-income-tax-booklet#page=10
does not work for non .pdf links - need to add page to title

2024-02-29 19:43 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/exemptions/parent_grandparent/cost_rate.yaml
> +    - title: 2023 Arizona Form 140A - Arizona Resident Personal Income Tax Booklet line11a
```suggestion
    - title: 2023 Arizona Form 140A - Arizona Resident Personal Income Tax Booklet Page 10, Line 11a
```

2024-02-29 19:43 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/exemptions/parent_grandparent/cost_rate.yaml
> +    - title: 2023 Arizona Form 140A - Arizona Resident Personal Income Tax Booklet line11a
same style in all yaml without hyperlink

2024-03-04 19:45 UTC, PavelMakarchuk requested changes

2024-03-04 19:45 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/az/tax/income/az_filing_status.py
> +                # Simulate scenario where joint filers file separately on Arkansas return.
```suggestion
                # In Arkansas, widowed filers are treated as heads of households.
```

2024-03-04 19:45 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/deductions/standard/amount.yaml
> +  2023-01-01: 13_850
add back the 2021 and 2022 values

2024-03-04 19:45 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/deductions/standard/increased/rate.yaml
> +  - title: 2023 Arizona Form 140 Resident Personal Income Tax Booklet
add pages to the title if there is no hyperlink

2024-03-04 19:45 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/deductions/standard/increased/rate.yaml
> +  - title: 2023 Arizona Form 140 Resident Personal Income Tax Booklet
all yaml files

2024-03-04 19:45 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/main/head_of_household.yaml
> +    - title: ARIZONA STATE SENATE, Fifty-Fifth Legislature, First Regular Session, Paragraph 1,Purpose
add section to law source

2024-03-04 19:45 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/main/head_of_household.yaml
>        2021-01-01: 333_684
add 2.5% to the bottom rate - all main files

2024-03-04 23:53 UTC, PavelMakarchuk requested changes

2024-03-04 23:53 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/deductions/standard/amount.yaml
>  WIDOW:
delete widow here

2024-03-04 23:53 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/subtractions/capital_gains/rate.yaml
> +  - title: 2023 Arizona Form 140A - Arizona Resident Personal Income Tax Booklet
add page

2024-03-04 23:53 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/subtractions/college_savings/cap.yaml
> +  - title: 2023 Arizona Form 140A - Arizona Resident Personal Income Tax Booklet
add page

2024-03-04 23:53 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/subtractions/military_retirement/max_amount.yaml
> +    - title: 2023 Arizona Form 140A - Arizona Resident Personal Income Tax Booklet
add page

2024-03-04 23:53 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/subtractions/pension/public_pension_cap.yaml
> +  - title: 2023 Arizona Form 140A - Arizona Resident Personal Income Tax Booklet
add page

2024-03-04 23:53 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/subtractions/subtractions.yaml
> +    - title: 2023 Arizona Form 140A - Arizona Resident Personal Income Tax Booklet
add page

2024-03-04 23:53 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/az/tax/income/az_filing_status.py
> +        return select(
this needs another test (probably for widow input)

2024-03-04 23:53 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/credits/family_tax_credits/amount/cap.yaml
> +    href: https://azdor.gov/forms/individual/form-140a-arizona-resident-personal-income-tax-booklet#page=22
```suggestion
    href: https://azdor.gov/forms/individual/form-140a-arizona-resident-personal-income-tax-booklet
```

2024-03-04 23:53 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/az/tax/income/credits/family_tax_credits/amount/cap.yaml
> +    href: https://azdor.gov/forms/individual/form-140a-arizona-resident-personal-income-tax-booklet#page=22
page in title the #page= only works for .pdf files

2024-03-07 19:36 UTC, PavelMakarchuk commented
Could you add a comment to the issue describing all parameters that changed

2024-03-07 19:37 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/az/tax/income/az_filing_status.yaml
add one more test

2024-03-11 18:02 UTC, PavelMakarchuk approved these changes

2024-03-11 23:00 UTC, MaxGhenis requested changes

2024-03-11 23:00 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/az/tax/income/az_filing_status.py
> +    label = "Arizona filing status"
Add a legal code reference indicating that surviving spouses are treated as HoH

2024-03-14 12:02 UTC, MaxGhenis approved these changes

2024-03-14 12:02 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/az/tax/income/az_filing_status.py
> +    documentation = "https://azdor.gov/forms/individual/form-140a-arizona-resident-personal-income-tax-booklet"  # Page 5, Box 5
```suggestion
    documentation = (
        # Section 43-1001(5)
        "https://www.azleg.gov/viewdocument/?docName=https://www.azleg.gov/ars/43/01001.htm",
        # Page 5 (page 9 of pdf), Box 5.
        "https://azdor.gov/forms/individual/form-140a-arizona-resident-personal-income-tax-booklet"
    )
```

2024-03-14 12:02 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/az/tax/income/az_filing_status.py
> +    label = "Arizona filing status"
Please note I requested legal code not tax form

2024-03-14 15:32 UTC, merged