Idaho subtraction for allowable state childcare expenses
PolicyEngine/policyengine-us pull request #3761
Opened 2024-02-02 00:37 UTC by PavelMakarchuk

Fixes #3110

2024-02-02 03:09 UTC, MaxGhenis requested changes
Could you add an integration test going off the worksheet?

2024-02-02 03:09 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/id/tax/income/deductions/dependent_care_expenses/cap.yaml
> +    href: https://tax.idaho.gov/wp-content/uploads/forms/EIN00046/EIN00046_11-15-2021.pdf#31
```suggestion
    href: https://tax.idaho.gov/wp-content/uploads/forms/EIN00046/EIN00046_11-15-2021.pdf#page=31
```

2024-02-02 13:49 UTC, PavelMakarchuk commented
> Could you add an integration test going off the worksheet?

I see, refactored the relevant cdcc expenses to math the form calc

2024-02-02 14:04 UTC, MaxGhenis requested changes
Could you describe how this works more?

2024-02-02 14:04 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/id/tax/income/subtractions/dependent_care_exepenses/id_household_and_dependent_care_expense_deduction.py
> +            amount_per_child = cdcc.max * capped_count_cdcc_eligible
rename variable to reflect that it's multiplied by number of children

2024-02-02 14:04 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/id/tax/income/deductions/dependent_care_expenses/cap/available.yaml
rename `applies.yaml`? though i'm not clear on how this works

2024-02-02 14:04 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/id/tax/income/deductions/dependent_care_expenses/cap/available.yaml
> +description: Idaho caps the household and dependent care expense deduction independently of the federal CDCC calucaltion if this is true.
```suggestion
description: Idaho caps the household and dependent care expense deduction independently of the federal child and dependent care calculation if this is true.
```

2024-02-02 14:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/id/tax/income/deductions/dependent_care_expenses/cap/available.yaml
In 2023 Idaho removed the 3,000 for one and 6,000 for two or more children cap on the expenses with a flat 12,000 cap

2024-02-02 23:52 UTC, MaxGhenis requested changes
Could you refactor `cdcc_relevant_expenses` by creating a new `cdcc_limit` variable, which equals `capped_count_cdcc_eligible * amount`?

Then you can avoid pulling in IRS parameters, remove `p.applies`, turn `p.cap.amount` into `p.cap` (remove folder), and simplify this formula to
```python
limit = max_(tax_unit("cdcc_limit", period), p.cap)
```

2024-02-03 00:36 UTC, PavelMakarchuk commented
> Could you refactor `cdcc_relevant_expenses` by creating a new `cdcc_limit` variable, which equals `capped_count_cdcc_eligible * amount`?
> 
> Then you can avoid pulling in IRS parameters, remove `p.applies`, turn `p.cap.amount` into `p.cap` (remove folder), and simplify this formula to
> 
> ```python
> limit = max_(tax_unit("cdcc_limit", period), p.cap)
> ```

I have refactored the cdcc but it forces me to set the cap to 0 pre 2023 to avoid making the $6,000 obsolete

2024-02-03 00:57 UTC, MaxGhenis requested changes

2024-02-03 00:57 UTC, MaxGhenis commented on policyengine_us/variables/gov/irs/credits/cdcc/cdcc_limit.py
> +        cdcc = parameters(period).gov.irs.credits.cdcc
```suggestion
        p = parameters(period).gov.irs.credits.cdcc
```

2024-02-03 00:57 UTC, MaxGhenis commented on policyengine_us/variables/gov/irs/credits/cdcc/cdcc_limit.py
> +        "https://www.law.cornell.edu/uscode/text/26/21#d_1",
remove - only c

2024-02-03 00:57 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/irs/credits/cdcc/cdcc_limit.yaml
do you need to adjust the cdcc_relevant_expenses tests too?

2024-02-03 00:57 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/id/tax/income/deductions/dependent_care_expenses/cap.yaml
> +description: Idaho caps the household and dependent care expense deduction at this amount.
```suggestion
description: Idaho caps the household and dependent care expense deduction at the greater of the federal cap and this amount.
```

2024-02-03 00:57 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/id/tax/income/deductions/dependent_care_expenses/cap.yaml
> +  # The cap was introduced in 2022
```suggestion
  # Idaho introduced the higher cap in 2022.
```

2024-02-03 01:08 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/irs/credits/cdcc/cdcc_limit.yaml
seems like we never had a unit test for `cdcc_relevant_expenses`  - added

2024-02-03 01:09 UTC, MaxGhenis approved these changes

2024-02-03 01:21 UTC, merged