Update California 2023 Individual Income Tax Parameter
PolicyEngine/policyengine-us pull request #3770
Opened 2024-02-02 19:23 UTC by DianaShi5083

Fixes #3769

2024-02-05 18:03 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Update 2023 CA Income Tax Parameters
```suggestion
    - Update 2023 California income tax parameters.
```

2024-02-05 18:03 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ca/tax/income/credits/child_dependent_care/rate.yaml
> +    - href: https://www.ftb.ca.gov/forms/2023/2023-3506.pdf
add page

2024-02-05 18:04 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ca/tax/income/deductions/itemized/limit/agi_fraction.yaml
> +    href: https://www.ftb.ca.gov/forms/2023/2023-540.pdf
add page - and all other .pdf links

2024-02-05 18:06 UTC, PavelMakarchuk commented on changelog_entry.yaml
could you add one integration test, where you create a test case with 2 people with employment income and calculate their standard deduction, income tax, taxable income etc. 
Calculate it from the 2023 form first to make sure we we get the right results

2024-02-13 00:39 UTC, PavelMakarchuk requested changes

2024-02-13 00:39 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ca/tax/income/integration.yaml
> +  input:
```suggestion
  input:
     people:
        person1:
           age: 40
           employment_income: 50_000
        person2:
           age: 40
           employment_income: 40_000
    tax_units....
```

2024-02-13 00:39 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ca/tax/income/integration.yaml
> +  output:
```suggestion
  output:
       ca_agi: 90_000
```

2024-02-13 00:39 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ca/tax/income/integration.yaml
> +    ca_itemized_deductions: 10_000
keep itemized ded as an input

2024-02-13 00:39 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ca/tax/income/integration.yaml
> +    ca_agi: 90_000
```suggestion
```

2024-02-13 00:43 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ca/tax/income/deductions/itemized/limit/agi_threshold.yaml
> +  - title: Cal. Rev. & Tax. Code § 17077 #the parameters in this reference didn't updated
```suggestion
  # The legal code provides the inflation unadjusted amount
  - title: Cal. Rev. & Tax. Code § 17077 
```

2024-02-20 15:32 UTC, PavelMakarchuk approved these changes

2024-03-12 01:27 UTC, MaxGhenis requested changes

2024-03-12 01:27 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ca/tax/income/exemptions/dependent_amount.yaml
> +  1999-01-01: 227
```suggestion
  1999-01-01: 227 # As specified in legal code. Indexed to inflation from here.
```

2024-03-12 01:27 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ca/tax/income/exemptions/phase_out/amount.yaml
>  description: Amount to phase california exemption out by
```suggestion
description: California reduces its exemption by this amount for each increment of income exceeding the threshold.
```

2024-03-12 01:27 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ca/tax/income/exemptions/phase_out/start.yaml
>  description: Phase out starting amount of california exemption
```suggestion
description: California reduces the exemption amount for filers with income exceeding this threshold.
```

2024-03-12 01:27 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ca/tax/income/exemptions/phase_out/increment.yaml
>  description: Phase out increment of california exemption
```suggestion
description: California reduces its exemption for each of these increments of income in excess of the threshold.
```

2024-03-12 01:27 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ca/tax/income/exemptions/phase_out/start.yaml
> +  1991-01-01: 100_000
```suggestion
  1991-01-01: 100_000 # Defined in the legal code. Inflation-indexed from here.
```

2024-03-15 03:40 UTC, MaxGhenis requested changes
Could you please:
1. Double-check the parameters I added uprating metadata to that don't have 2023 values, e.g. AMT?
2. Add remaining uprating metadata to the other thresholds as I did for `rates/head_of_household.yaml` (sorry this is annoying! should be easier post https://github.com/PolicyEngine/policyengine-core/issues/163)

2024-03-15 03:44 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ca/cpi.yaml
>  metadata:
```suggestion
  2023-01-01: 332.035
metadata:
  reference:
    title: California Consumer Price Index
    href: https://www.dir.ca.gov/oprl/CPI/EntireCCPI.PDF
```

2024-03-15 04:32 UTC, PavelMakarchuk commented
@MaxGhenis the uprating would affect the unit tests correct?

2024-03-15 04:33 UTC, MaxGhenis commented
Yep

2024-03-15 12:02 UTC, MaxGhenis approved these changes

2024-03-15 12:02 UTC, merged