Update Arkansas parameters based on 2023 tax form
PolicyEngine/policyengine-us pull request #3807
Opened 2024-02-07 21:19 UTC by Kiki-67

Fixes #3804

2024-02-16 17:06 UTC, PavelMakarchuk requested changes

2024-02-16 17:06 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +
need a changelog

2024-02-16 17:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/credits/inflationary_relief/reduction/start.yaml
add references to all yaml files

2024-02-16 17:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/rates/main/reduction.yaml
>        2022-01-01: .inf
might need to add a .inf bracket to the bottom -> all yaml files

2024-02-16 17:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/rates/main/rate.yaml
add one test for main rate, for the maximum bracket

2024-02-21 14:52 UTC, PavelMakarchuk requested changes

2024-02-21 14:52 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +
add changelog

2024-02-21 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/credits/inflationary_relief/reduction/start.yaml
add the 2023 form as a reference to all yaml files

2024-02-21 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/rates/low_income_tax_tables/head_of_household/two_or_more_dependents.yaml
> +      2023-01-01: .inf
```suggestion
      2021-01-01: .inf      
```

2024-02-21 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/rates/low_income_tax_tables/head_of_household/two_or_more_dependents.yaml
> +      2023-01-01: .inf
```suggestion
      2021-01-01: .inf
```

2024-02-21 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/rates/low_income_tax_tables/head_of_household/two_or_more_dependents.yaml
> +      2023-01-01: .inf
```suggestion
      2021-01-01: .inf
```

2024-02-23 17:05 UTC, PavelMakarchuk requested changes

2024-02-23 17:05 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/rates/low_income_tax_tables/single.yaml
> +      2023-01-01: .inf
```suggestion
```

2024-02-23 17:05 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/rates/low_income_tax_tables/single.yaml
> +      2021-01-01: .inf
```suggestion
```

2024-02-23 17:05 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/rates/main/reduction.yaml
> +      2023-01-01: .inf
```suggestion
```

2024-02-23 17:05 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/rates/main/reduction.yaml
> +      2023-01-01: .inf
same adj. for all of rates files

2024-03-01 13:52 UTC, PavelMakarchuk requested changes

2024-03-01 13:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/deductions/itemized/tuition/weighted_average_tuition/two_year_college.yaml
> +  2023-01-01: 4_405
shouldn't this be [this](https://www.dfa.arkansas.gov/images/uploads/incomeTaxOffice/AR1075_2023.pdf#page=1) number:

![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/a8d3aad6-b344-4afa-934c-daab0df1af07)

2024-03-01 13:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/rates/main/reduction.yaml
> +      2023-01-01: 100_001
```suggestion
      2023-01-01: .inf
```

2024-03-01 13:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/rates/main/reduction.yaml
> +      2023-01-01: 153.70
```suggestion
      2023-01-01: .inf
```

2024-03-01 13:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/rates/main/rate.yaml
> +      2021-01-01: .inf
```suggestion
```

2024-03-01 13:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/rates/low_income_tax_tables/joint/no_or_one_dependent.yaml
> +      2021-01-01: .inf
```suggestion
```

2024-03-01 13:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ar/tax/income/rates/low_income_tax_tables/head_of_household/two_or_more_dependents.yaml
> +      2023-01-01: 27_400
add 2021 values to this if we need these brackets

2024-03-06 19:55 UTC, PavelMakarchuk commented
Could you write out all the programs that changed in 2023 in the issue #3804 - it makes reviewing changes easier

2024-03-06 20:19 UTC, Kiki-67 commented
parameters changed in 2023:
1. cdcc
2. deductions - weighted average tuition
  2.1 four year college
  2.2 two year college
3. low income tax tables
  3.1 head of household - no or one dependent
  3.2 head of household - two or more dependent
  3.3 joint - no or one dependent
  3.4 joint - two or more dependent
  3.5 single
4. main rate 
5. main reduction

2024-03-13 15:17 UTC, PavelMakarchuk approved these changes

2024-03-13 20:24 UTC, MaxGhenis approved these changes

2024-03-13 20:24 UTC, merged