Decompose snap_utility_allowance into three variables for SUA, LUA, and IUA
PolicyEngine/policyengine-us pull request #3903
Opened 2024-02-16 16:39 UTC by yy3187

2024-02-23 15:02 UTC, PavelMakarchuk requested changes

2024-02-23 15:02 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Louisiana adoption credit.
adjust here

2024-02-23 15:02 UTC, PavelMakarchuk commented on policyengine_us/data/datasets/cps/cps.py
> +    ].values
delete this code

2024-02-23 15:02 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/usda/snap/income/deductions/snap_individual_utility_allowance.yaml
> +    snap_individual_utility_allowance: 228 # 19 * 12
add a couple of other tests, representing edge cases

2024-02-23 15:02 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/la/tax/income/la_refundable_credits.py
did we intend to delete this?

2024-02-23 15:02 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/income/deductions/shelter/snap_individual_utility_allowance.py
> +    label = "Individual Utility Allowance"
```suggestion
    label = "SNAP Individual Utility Allowance"
```

2024-02-23 15:02 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/income/deductions/shelter/snap_individual_utility_allowance.py
> +    label = "Individual Utility Allowance"
and others

2024-02-23 15:13 UTC, yy3187 commented on policyengine_us/variables/gov/states/la/tax/income/la_refundable_credits.py
yes, it was the adoption credit.

2024-02-23 15:23 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/la/tax/income/la_refundable_credits.py
I believe we need this back

2024-02-26 20:15 UTC, PavelMakarchuk commented on changelog_entry.yaml
test failing

2024-02-27 14:26 UTC, PavelMakarchuk requested changes

2024-02-27 14:26 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/la/tax/income/la_refundable_credits.py
was this renamed?

2024-02-27 14:26 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/la/tax/income/la_refundable_credits.py
This is causing the test issues

2024-02-27 14:26 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/income/deductions/shelter/snap_utility_allowance.py
>      label = "Standard Utility Allowance"
```suggestion
    label = "Standard Utility Allowance"
    unit = USD
```

2024-02-27 14:26 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/income/deductions/shelter/snap_individual_utility_allowance.py
> +    documentation = "The regular utility allowance deduction for SNAP"
```suggestion
    documentation = "The individual utility allowance deduction for SNAP"
```

2024-02-27 14:26 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/income/deductions/shelter/snap_limited_utility_allowance.py
> +    documentation = "The regular utility allowance deduction for SNAP"
```suggestion
    documentation = "The limited utility allowance deduction for SNAP"
```

2024-02-27 16:17 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/la/tax/income/la_refundable_credits.py
how does that connect to snap utility allowances?

2024-02-28 02:03 UTC, MaxGhenis approved these changes

2024-02-28 19:05 UTC, merged