California Investment interest expense deduction
PolicyEngine/policyengine-us pull request #3931
Opened 2024-02-18 17:52 UTC by vrathi101

Fixes #3837

2024-02-19 00:03 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ca/tax/income/deductions/ca_investment_interest_deduction.py
> +        )  # Line 9
make the line comment above of the line of code, e.g.:
```suggestion
        # Line 9
        form_4952_amount = tax_unit(
            "investment_income_form_4952", period
        )  
```

2024-02-19 00:04 UTC, PavelMakarchuk requested changes

2024-02-19 00:04 UTC, PavelMakarchuk commented on policyengine_us/variables/household/expense/person/investment_expense.py
> +class investment_expense(Variable):
```suggestion
class investment_expenses(Variable):
```

2024-02-19 00:04 UTC, PavelMakarchuk commented on policyengine_us/variables/household/expense/person/investment_expense.py
> +    label = "Investment expense"
```suggestion
    label = "Investment expenses"
```

2024-02-19 00:44 UTC, MaxGhenis commented on policyengine_us/variables/household/expense/person/investment_expense.py
are we sure this isn't the same as the existing `interest_expense`? please check its uses against this one

2024-02-19 01:55 UTC, vrathi101 commented on policyengine_us/variables/household/expense/person/investment_expense.py
According to the CA form, "Investment expenses are your allowed deductions, other than interest expense, directly connected with the production of investment income." So I believe they're different, but I may be wrong.

2024-02-19 02:58 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/tax/income/deductions/ca_investment_interest_deduction.py
> +        net_investment_income = (
income will not be the difference between two types of expenses

2024-02-21 13:13 UTC, PavelMakarchuk requested changes

2024-02-21 13:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ca/tax/income/deductions/ca_investment_interest_deduction.py
> +        return np.absolute(
```suggestion
        return np.absolute(
```

2024-02-21 13:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ca/tax/income/deductions/ca_investment_interest_deduction.py
> +        # )
delete commented files

2024-02-21 13:13 UTC, PavelMakarchuk commented on policyengine_us/variables/household/expense/person/investment_expense.py
> +class investment_expenses(Variable):
delete this file,

Net investment income seems to serve the purpose

2024-02-23 14:12 UTC, PavelMakarchuk requested changes

2024-02-23 14:12 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ca/tax/income/deductions/itemized/limit/excluded_deductions.yaml
>    unit: variable
```suggestion
  unit: list
  period: year
```

2024-02-23 14:12 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ca/tax/income/deductions/ca_investment_interest_deduction.py
> +        # Lines 2, 3, 4a, 4b, 4c, 4d, 4e, 4f, 7 from tax form not included in calculations
```suggestion
```

2024-02-23 14:12 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ca/tax/income/deductions/ca_investment_interest_deduction.py
> +        return np.absolute(
```suggestion
        return np.abs(
```

2024-02-25 14:04 UTC, PavelMakarchuk requested changes

2024-02-25 14:04 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ca/tax/income/deductions/itemized/limit/excluded_deductions.yaml
should it be part of this list or a list of all actual deductions?

2024-02-25 21:25 UTC, PavelMakarchuk approved these changes

2024-02-28 17:51 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/tax/income/deductions/ca_investment_interest_deduction.py
>      documentation = "https://www.ftb.ca.gov/forms/2021/2021-3526.pdf"
could you add a legal code reference?

2024-03-08 01:19 UTC, MaxGhenis approved these changes

2024-03-08 01:19 UTC, merged