Georgia 2024 - 2029 income tax rates and exemption increase
PolicyEngine/policyengine-us pull request #4033
Opened 2024-02-29 00:59 UTC by laviniawo

Fixes #3953

2024-02-29 02:39 UTC, PavelMakarchuk requested changes

2024-02-29 02:39 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ga/tax/income/agi/exclusions/retirement/cap/earned_income.yaml
>  values:
add the 2023 tax form reference

2024-02-29 02:39 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ga/tax/income/agi/exclusions/retirement/cap/earned_income.yaml
> +  2023-01-01: 4_000
```suggestion
```

2024-02-29 02:39 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ga/tax/income/agi/exclusions/retirement/cap/earned_income.yaml
> +  2023-01-01: 4_000
dont need to add the new year if the value is the same

2024-02-29 02:39 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ga/tax/income/agi/exclusions/retirement/cap/earned_income.yaml
>  values:
for all yaml files

2024-02-29 02:39 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ga/tax/income/agi/exclusions/retirement/cap/earned_income.yaml
> +  2023-01-01: 4_000
for all yaml files

2024-02-29 02:39 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ga/tax/income/credits/low_income/amount.yaml
> +  - threshold:
delete if it is the same

2024-02-29 02:39 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ga/tax/income/deductions/standard/amount.yaml
> +  #2024-01-01: 18_500
?

2024-03-01 00:42 UTC, PavelMakarchuk approved these changes

2024-03-01 13:52 UTC, MaxGhenis requested changes

2024-03-01 13:52 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ga/tax/income/exemptions/dependent.yaml
>      href: https://advance.lexis.com/documentpage/?pdmfid=1000516&crid=5c65c45e-44b1-4c09-be93-e1cf5dc8590c&config=00JAA1MDBlYzczZi1lYjFlLTQxMTgtYWE3OS02YTgyOGM2NWJlMDYKAFBvZENhdGFsb2feed0oM9qoQOMCSJF
document not available could you update? if the legal code includes these changes we can drop the legislation reference

2024-03-01 15:03 UTC, PavelMakarchuk approved these changes

2024-03-01 15:45 UTC, MaxGhenis requested changes

2024-03-01 17:12 UTC, merged