Replace state income tax with estimated withholding for all states in income tax used for SALT deduction
PolicyEngine/policyengine-us pull request #4045
Opened 2024-02-29 22:02 UTC by Shinuing

Fixes #4024 

create basic structure

2024-02-29 23:08 UTC, PavelMakarchuk requested changes

2024-02-29 23:08 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/in_withheld_income_tax.py
> +        p = parameters(period).gov.states.ca.tax.income
```suggestion
        p = parameters(period).gov.states["in"]tax.income
```

2024-02-29 23:08 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ks/tax/income/ks_withheld_income_tax.py
> +        p = parameters(period).gov.states.ca.tax.income
```suggestion
        p = parameters(period).gov.states.ka.tax.income
```

2024-02-29 23:08 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ks/tax/income/ks_withheld_income_tax.py
> +        p = parameters(period).gov.states.ca.tax.income
and others

2024-03-01 01:21 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/state_income_tax.yaml
some states use the federal SD and some states use the personal exemptions instead

2024-03-01 15:23 UTC, Shinuing commented on policyengine_us/parameters/gov/state_income_tax.yaml
yes, I'm not finishing yet. Just created basic structure for all states needed. will check when doing

2024-03-01 20:11 UTC, Shinuing commented
Some confusions @PavelMakarchuk 

1. Do we always apply maximum sd compared with base sd?
2. **KS**: do i need to model JOINT separately? JOINT rate is different than others
2: **MI**: sd tier 2 or tier 3 ?
3. **PA**: Pennsylvania does not have standard deductions, personal exemptions, or itemized deductions. Also, They do not use the federal standard deduction amounts. How can we do withheld in this situation?

2024-03-02 11:50 UTC, PavelMakarchuk requested changes

2024-03-02 11:50 UTC, PavelMakarchuk commented on changelog_entry.yaml
Some tests fail

2024-03-02 11:50 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/id/tax/income/id_withheld_income_tax.py
> +        # We apply the base standard deduction amount
```suggestion
        # We apply the base IRS standard deduction amount
```

2024-03-02 11:50 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/id/tax/income/id_withheld_income_tax.py
> +        # We apply the base standard deduction amount
all files with IRS

2024-03-02 11:50 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/nm/tax/income/nm_withheld_income_tax.yaml
> +- name: Changing the filing status should not change the output
thanks for that!

2024-03-04 18:23 UTC, PavelMakarchuk requested changes

2024-03-04 18:23 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/pa/tax/income/pa_withheld_income_tax.py
> +        p = parameters(period).gov.states.pa.tax.income
finish var.

2024-03-04 18:25 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/pa/tax/income/pa_withheld_income_tax.py
> +        p = parameters(period).gov.states.pa.tax.income
also add test

2024-03-04 19:48 UTC, Shinuing commented on policyengine_us/variables/gov/states/pa/tax/income/pa_withheld_income_tax.py
> +        p = parameters(period).gov.states.pa.tax.income
Hi please check my comment above, I have mentioned my concerns with PA also other states

2024-03-04 23:38 UTC, PavelMakarchuk commented
> Some confusions @PavelMakarchuk
> 
> 1. Do we always apply maximum sd compared with base sd?
> 2. **KS**: do i need to model JOINT separately? JOINT rate is different than others
> 3. **MI**: sd tier 2 or tier 3 ?
> 4. **PA**: Pennsylvania does not have standard deductions, personal exemptions, or itemized deductions. Also, They do not use the federal standard deduction amounts. How can we do withheld in this situation?

1. We apply the max SD if there is a phase-out but if there if thee is an additional SD (e.g. dependents) we use the base 
2. We only model SINGLE 
3. MI -> lets do no SD as they only apply for elderly (over 65) - same with exemptions
4. Lets just take the rate here

2024-03-07 18:05 UTC, PavelMakarchuk requested changes

2024-03-07 18:05 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nh/tax/income/nh_withheld_income_tax.py
I dont think new hampshire taxes only dividend and interest - so there is no withheld tax - we should NH completely from the state income tax yaml file

2024-03-07 18:05 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nh/tax/income/nh_withheld_income_tax.py
(the way e.g. Texas is)

2024-03-07 19:44 UTC, PavelMakarchuk approved these changes

2024-03-07 19:51 UTC, MaxGhenis approved these changes

2024-03-07 19:52 UTC, merged