Add the Louisiana non refundable credits together in a parameter file and add to the la_non_refundable_credits variable
PolicyEngine/policyengine-us pull request #4050
Opened 2024-03-01 15:28 UTC by yy3187

#4005

2024-03-01 16:01 UTC, PavelMakarchuk requested changes

2024-03-01 16:01 UTC, PavelMakarchuk commented on changelog_entry.yaml
add change log

2024-03-01 16:01 UTC, PavelMakarchuk commented on changelog_entry.yaml
make format

2024-03-01 16:01 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/la/tax/income/credits/nonrefundable.yaml
> +  name: la_nonrefundable_credits
```suggestion
  period: year
```

2024-03-01 16:01 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/la/tax/income/credits/nonrefundable.yaml
> +  unit: variable
```suggestion
  unit: list
```

2024-03-01 16:01 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/la/tax/income/credits/nonrefundable.yaml
> +  label: LA Nonrefundable Credits
```suggestion
  label: Louisiana non-refundable tax credits
```

2024-03-01 16:01 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/la/tax/income/credits/nonrefundable.yaml
> +description: Louisiana Nonrefundable Credits
```suggestion
description: Louisiana provides the following non-refundable tax credits.
```

2024-03-01 16:01 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/la/tax/income/credits/nonrefundable.yaml
rename non_refundable.yaml

2024-03-02 09:10 UTC, PavelMakarchuk approved these changes

2024-03-02 11:07 UTC, MaxGhenis approved these changes

2024-03-02 11:08 UTC, merged