Pxu12/issue4035
PolicyEngine/policyengine-us pull request #4071
Opened 2024-03-04 09:06 UTC by pxu12

Fixes #4035

2024-03-04 15:17 UTC, PavelMakarchuk requested changes

2024-03-04 15:17 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/tuition_and_fees_deduction/joint.yaml
we can name the folder `tuition_and_fees`

2024-03-04 15:17 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/tuition_and_fees_deduction/other.yaml
can you rename this to non_joint.yaml

2024-03-04 15:17 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/tuition_and_fees_deduction/joint.yaml
> +      2004-01-01: 130_000
```suggestion
```

2024-03-04 15:17 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/tuition_and_fees_deduction/joint.yaml
> +    - title: I.R.C. § 222(b)(2)(B)(ii)
```suggestion
    # Law was repealed in 2021 
    - title: I.R.C. § 222(b)(2)(B)(ii)
```

2024-03-04 17:48 UTC, PavelMakarchuk requested changes

2024-03-04 17:48 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/tuition_and_fees/joint.yaml
> +description: Modified adjusted gross income limit of tuition and fees deduction for joint filers.
```suggestion
description: The IRS limits the tuition and fees deduction to joint filers to this amount, based on adjusted gross income.
```

2024-03-04 17:48 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/tuition_and_fees/joint.yaml
> +  amount_period: year
```suggestion
  period: year
```

2024-03-04 17:48 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/tuition_and_fees/joint.yaml
> +  type: single_amount
add label

2024-03-04 17:48 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/tuition_and_fees/non_joint.yaml
> +  amount_period: year
```suggestion
  period: year
```

2024-03-04 17:48 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/tuition_and_fees/non_joint.yaml
> +  type: single_amount
add label

2024-03-04 17:48 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/tuition_and_fees/non_joint.yaml
> +description: Modified adjusted gross income limit of tuition and fees deduction for non-joint filers.
```suggestion
description: The IRS limits the tuition and fees deduction to non-joint filers to this amount, based on adjusted gross income
```

2024-03-04 17:48 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/income/taxable_income/deductions/tuition_and_fees_deduction.py
> +        limit = select(
can we use a where statement here instead?

2024-03-04 17:48 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/income/taxable_income/deductions/tuition_and_fees_deduction.py
> +        limit = select(
```suggestion
        cap = select(
```

2024-03-05 16:05 UTC, PavelMakarchuk requested changes

2024-03-05 16:05 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/income/taxable_income/deductions/tuition_and_fees_deduction.py
> +            filing_status == filing_status.possible_values.JOINT,
```suggestion
        joint = filing_status == filing_status.possible_values.JOINT
        cap = where(
            joint,
```

2024-03-05 16:05 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/income/taxable_income/deductions/tuition_and_fees_deduction.py
> +    unit = USD
add reference

2024-03-05 16:05 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/tuition_and_fees/non_joint.yaml
> +  label: IRS tuition and fees deduction cap to non-joint filers
```suggestion
  label: IRS tuition and fees deduction non-joint filers cap 
```

2024-03-05 16:05 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/tuition_and_fees/joint.yaml
> +  label: IRS tuition and fees deduction cap to joint filers
```suggestion
  label: IRS tuition and fees deduction joint filers cap 
```

2024-03-05 16:05 UTC, PavelMakarchuk commented on changelog_entry.yaml
we need to add this to the list of IRS deductions

2024-03-07 07:10 UTC, pxu12 commented
Hi @PavelMakarchuk, regarding the deduction list, in the tax form, this deduction is in the adjustment to income section:
<img width="407" alt="Screen Shot 2024-03-07 at 3 00 48 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/129036923/1c09df44-3600-41aa-9e14-1b7bd20b7267">
I searched online and it's said to be an above-the-line deduction:
<img width="731" alt="Screen Shot 2024-03-07 at 3 07 31 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/129036923/17f6428d-e359-486b-a8ec-ebcbcd13c264">
I assumed that means that the deduction can be claimed both when itemizing and not itemizing, so I added it to both lists. But I'm not sure that's correct.

2024-03-11 14:13 UTC, PavelMakarchuk requested changes

2024-03-11 14:13 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/deductions_if_itemizing.yaml
>    name: taxable_income_deductions_if_itemizing
```suggestion
  name: taxable_income_deductions_if_itemizing
```

2024-03-11 14:13 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/deductions_if_itemizing.yaml
>    unit: variable
```suggestion
  unit: list
  period: year
```

2024-03-11 14:13 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/deductions_if_not_itemizing.yaml
>    name: taxable_income_deductions_if_itemizing
```suggestion
```

2024-03-11 14:13 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/deductions_if_not_itemizing.yaml
>    unit: variable
```suggestion
  unit: list
  period: year
```

2024-03-11 14:13 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/deductions_if_itemizing.yaml
> +    - tuition_and_fees_deduction
make a 2021-01-01: 
  2021-01-01:
    - charitable_deduction
    - interest_deduction
    - salt_deduction
    - medical_expense_deduction
    - casualty_loss_deduction
    - qualified_business_income_deduction
    - wagering_losses_deduction

2024-03-11 14:13 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/deductions_if_itemizing.yaml
> +    - tuition_and_fees_deduction
same for not itemized to show that it was repealed

2024-03-14 02:45 UTC, closed without merging