Rename WIDOW to SURVIVING_SPOUSE filing status
PolicyEngine/policyengine-us pull request #4130
Opened 2024-03-11 23:16 UTC by JudyZ13

Fixes #4094

2024-03-11 23:21 UTC, PavelMakarchuk commented on changelog_entry.yaml
I think this got mixed up with the DC files. Could you take a look and remove all DC related files? You need to check out the PR from your master branch

2024-03-12 17:07 UTC, PavelMakarchuk requested changes

2024-03-12 17:07 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/dc/tax/income/dc_disability_exclusion.yaml
delete file

2024-03-12 17:07 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/dc/tax/income/subtractions/dc_disability_exclusion.py
delete

2024-03-12 17:07 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/dc/tax/income/subtractions/disability_income_exclusion/amount.yaml
delete

2024-03-12 17:07 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/dc/tax/income/subtractions/disability_income_exclusion/cap.yaml
delete

2024-03-14 01:45 UTC, PavelMakarchuk requested changes

2024-03-14 01:45 UTC, PavelMakarchuk commented on CHANGELOG.md
revert here

2024-03-14 01:45 UTC, PavelMakarchuk commented on changelog.yaml
> +    - Limit suriving spouse filing status to widowed head with child dependents.
revert here

2024-03-14 01:45 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/contrib/congress/wftca/bonus_guaranteed_deduction/amount.yaml
> +    label: WFTCA SURVIVING_SPOUSE filer amount
the labels and descriptions can remain unadjusted

2024-03-14 01:47 UTC, PavelMakarchuk commented
also need to resolve merge conflicts

2024-03-29 12:49 UTC, PavelMakarchuk requested changes
please double check that we didnt delete any lines or changed the dates

2024-03-29 12:49 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ca/tax/income/credits/renter/amount.yaml
> +  2021-01-01: 60
```suggestion
  1998-01-01: 60
```

2024-03-29 12:49 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ca/tax/income/credits/renter/amount.yaml
> +  2022-01-01: 120
```suggestion
SURVIVING_SPOUSE:
  1998-01-01: 120
```

2024-03-29 12:49 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ca/tax/income/deductions/itemized/limit/agi_threshold.yaml
>    2022-01-01: 344_867
add 2023 value back

2024-03-29 12:49 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ca/tax/income/deductions/standard/amount.yaml
>    2022-01-01: 10_404
add 2023 value back

2024-03-29 12:49 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ca/tax/income/exemptions/phase_out/increment.yaml
> +  2022-01-01: 1_250
revert to old date structure

2024-03-29 12:49 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ca/tax/income/exemptions/phase_out/start.yaml
>    2022-01-01: 229_908
add 2023 value

2024-03-29 12:49 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/senior_circuit_breaker/eligibility/max_income.yaml
>    2022-01-01: 80_000
add 2023 values back

2024-04-02 17:06 UTC, PavelMakarchuk commented
@MaxGhenis the basic rules PR is done but do we need to change anything in the cps etc.? No tests fail currently

2024-04-02 17:06 UTC, PavelMakarchuk approved these changes

2024-04-02 18:06 UTC, MaxGhenis commented on CHANGELOG.md
> +- Limit widow filing status to widowed head with child dependents.
undo here and in changelog.yaml (we never modify these)

2024-04-02 20:28 UTC, MaxGhenis approved these changes

2024-04-02 20:28 UTC, MaxGhenis commented on policyengine_us/variables/household/demographic/tax_unit/filing_status.py
> +    SURVIVING_SPOUSE = "Widow(er)"
```suggestion
    SURVIVING_SPOUSE = "Surviving spouse"
```

2024-04-02 21:40 UTC, merged