Merge branch 'master' of https://github.com/PolicyEngine/policyengine-us into pxu12/issue4035
PolicyEngine/policyengine-us pull request #4138
Opened 2024-03-14 00:20 UTC by hua7450

2024-03-14 01:05 UTC, PavelMakarchuk commented
@hua7450 new PR?

2024-03-14 01:42 UTC, PavelMakarchuk requested changes

2024-03-14 01:42 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/income/taxable_income/deductions/tuition_and_fees_deduction.py
> +        eligible = (
```suggestion
        has_take_the_american_opp_or_life_learn_credits = (
```

2024-03-14 01:42 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/income/taxable_income/deductions/tuition_and_fees_deduction.py
> +        ) == 0
```suggestion
        ) > 0
```

2024-03-14 01:42 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/income/taxable_income/deductions/tuition_and_fees_deduction.py
> +        return min_(qualified_tuition_expenses * eligible * not_separate, cap)
```suggestion
        return capped_expenses * ~eligible * not_separate
```

2024-03-14 01:42 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/income/taxable_income/deductions/tuition_and_fees_deduction.py
> +        )
```suggestion
        )
        capped_expenses = min_(qualified_tuition_expenses, cap)

```

2024-03-14 02:47 UTC, PavelMakarchuk approved these changes

2024-03-14 02:53 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/income/taxable_income/deductions/tuition_and_fees_deduction.py
> +        has_take_the_american_opp_or_life_learn_credits = (
```suggestion
        has_taken_the_american_opp_or_life_learn_credits = (
```

2024-03-14 02:55 UTC, MaxGhenis requested changes
Thanks. For posterity, the 2021 Consolidated Appropriations Act repealed this, shifting it to a higher Lifetime Learning Credit

2024-03-14 02:55 UTC, MaxGhenis commented on policyengine_us/variables/gov/irs/income/taxable_income/deductions/tuition_and_fees_deduction.py
> +        # married filing separatly are not eligible for this deduction
```suggestion
        # Married filing separately are not eligible for this deduction.
```

2024-03-14 02:55 UTC, MaxGhenis commented on policyengine_us/variables/gov/irs/income/taxable_income/deductions/tuition_and_fees_deduction.py
> +        # can't caim this deduction if the household has American oppportunity or lifetime learning credit
```suggestion
        # Can't claim this deduction if the household has taken the
        # American Opportunity Credit or Lifetime Learning Credit.
```

2024-03-14 02:55 UTC, MaxGhenis commented on policyengine_us/variables/gov/irs/income/taxable_income/deductions/tuition_and_fees_deduction.py
> +        american_opportunity_credit = tax_unit(
Please make a separate variable `tuition_and_fees_deduction_eligible` that looks like this
```suggestion
        aoc_llc = add(tax_unit, period, ["american_opportunity_credit", "lifetime_learning_credit"])
        return ~separate & (aoc_llc == 0)
```

2024-03-14 04:10 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/irs/income/taxable_income/deductions/tuition_and_fees_deduction.yaml
> +    american_opportunity_credit: 0
Use eligibility variable as input instead

2024-03-15 02:55 UTC, MaxGhenis approved these changes

2024-03-15 04:20 UTC, merged