add 2023-2026 tax rates
PolicyEngine/policyengine-us pull request #4232
Opened 2024-03-19 15:42 UTC by yy3187

2024-03-19 17:02 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ia/tax/income/ia_regular_tax_joint.yaml
> +- name: IA regular tax joint unit test 5
could you make more descriptive test case names

2024-03-19 17:02 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ia/tax/income/ia_regular_tax_indiv.yaml
> +- name: IA regular tax indiv unit test 13
could you make more descriptive test case names?

2024-03-26 13:26 UTC, PavelMakarchuk requested changes

2024-03-26 13:26 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ia/tax/income/pension_exclusion/cap_eligible.yaml
> +description: Iowa allows a cap amount for the exclusion of taxable pension income if this is true.
```suggestion
description: Iowa caps the taxable pension exclusion if this is true. 
```

2024-03-26 13:26 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ia/tax/income/pension_exclusion/cap_eligible.yaml
> +  label: Iowa pension income exclusion cap eligibility
```suggestion
  label: Iowa pension income exclusion cap available 
```

2024-03-26 13:26 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ia/tax/income/pension_exclusion/cap_eligible.yaml
rename to cap_available.yaml

2024-03-26 13:26 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ia/tax/income/net_income/ia_pension_exclusion.py
> +        )
```suggestion
        if p.cap_available:
             filing_status = person.tax_unit("filing_status", period)
             exclusion_cap = p.maximum_amount[filing_status]
             return min_(pension, exclusion_cap) * is_eligible
        return pension * is_eligible
```

2024-03-26 13:26 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ia/tax/income/net_income/ia_pension_exclusion.py
> +        cap_eligible = p.cap_eligible
```suggestion
```

2024-03-26 15:09 UTC, PavelMakarchuk commented on changelog_entry.yaml
For the alternative minimum tax:
Make a bool parameter 
In the ia_amt_indiv and ia_amt_joint - if true then compute, if false then false

2024-03-26 17:06 UTC, PavelMakarchuk requested changes

2024-03-26 17:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ia/tax/income/files_separate/if_files_separate.yaml
rename filing to married_filing_separately_on_same_return and rename file to availability.yaml

2024-03-26 17:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ia/tax/income/files_separate/if_files_separate.yaml
> +description: Iowa allows married couple filing separately on Iowa tax return if this is true.
```suggestion
description: Iowa allows married couples to file separately on the same tax return ,if this is true.
```

2024-03-26 17:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ia/tax/income/files_separate/if_files_separate.yaml
> +  label: Iowa's availbility of the filing status of married couple filing separately on a combined return
```suggestion
  label: Iowa's married filing separately on the same return availability 
```

2024-03-26 17:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ia/tax/income/alternative_minimum_tax/amt_available.yaml
rename file availability.yaml

2024-03-26 17:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ia/tax/income/alternative_minimum_tax/amt_available.yaml
> +  label: Iowa alternative minimum tax available
```suggestion
  label: Iowa alternative minimum tax availability
```

2024-03-26 17:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ia/tax/income/ia_files_separately.py
> +        if p.if_files_separate:
put lines 19-21 into the if condition

2024-03-26 17:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ia/tax/income/ia_amt_indiv.py
> +        if amt.amt_available:
put the whole computation in the if conditions

2024-03-26 18:34 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ia/tax/income/net_income/ia_pension_exclusion.py
> +        return pension * is_eligible
please break out into a `ia_pension_exclusion_eligible` variable while here

2024-03-31 20:20 UTC, PavelMakarchuk requested changes

2024-03-31 20:20 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Iowa 2023-2026 tax rates
```suggestion
    - Iowa 2023-2026 tax rates.
```

2024-03-31 20:20 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - 2023 Iowa pension income exclusion change
```suggestion
    - 2023 Iowa pension income exclusion logic.
```

2024-03-31 20:20 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - 2023 Iowa alternative minimum tax change
```suggestion
    - 2023 Iowa alternative minimum tax logic.
```

2024-03-31 20:20 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - 2023 Iowa filing status of married couple change
```suggestion
    - Disable married filing separately on the same return in Iowa past 2023.
```

2024-03-31 20:20 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ia/tax/income/married_filing_separately_on_same_return/availability.yaml
> +  label: Iowa's married filing separately on the same return availability
```suggestion
  label: Iowa married filing separately on the same return availability 
```

2024-03-31 20:20 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ia/tax/income/married_filing_separately_on_same_return/availability.yaml
> +description: Iowa allows married couples to file separately on the same tax return ,if this is true.
```suggestion
description: Iowa allows married couples to file separately on the same tax return if this is true.
```

2024-03-31 20:20 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ia/tax/income/pension_exclusion/cap_available.yaml
> +  label: Iowa pension income exclusion cap available
```suggestion
  label: Iowa pension income exclusion cap availability 
```

2024-03-31 20:20 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ia/tax/income/ia_amt_indiv.yaml
> +- name: IA AMT indiv unit test 2
```suggestion
- name: IA AMT indiv disabled in 2023
```

2024-03-31 20:20 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ia/tax/income/ia_amt_joint.yaml
> +- name: IA AMT joint unit test 2
```suggestion
- name: IA AMT indiv disabled in 2023
```

2024-03-31 20:20 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ia/tax/income/ia_files_separately.yaml
> +- name: IA files separately unit test 3
```suggestion
- name: IA married filing separately disabled in 2023
```

2024-03-31 20:20 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ia/tax/income/ia_amt_indiv.py
> +            us_filing_status = person.tax_unit("filing_status", period)
```suggestion
            reg_taxinc = person("ia_taxable_income_indiv", period)
            std_ded = person("ia_standard_deduction_indiv", period)
            itm_ded = person("ia_itemized_deductions_indiv", period)
            prorate_frac = person("ia_prorate_fraction", period)
            proptax = add(person.tax_unit, period, ["real_estate_taxes"])
            amt_taxinc = where(
                itm_ded > std_ded,
                reg_taxinc + prorate_frac * proptax,
                reg_taxinc,
            )
            # compute AMT amount
            p = parameters(period).gov.states.ia.tax.income
            amt = p.alternative_minimum_tax
            us_filing_status = person.tax_unit("filing_status", period)
```
Move everything into the if statement so we dont need to run the computation after 2023

2024-03-31 20:20 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ia/tax/income/ia_amt_indiv.py
> +            us_filing_status = person.tax_unit("filing_status", period)
same for all of the files below

2024-04-02 13:15 UTC, PavelMakarchuk approved these changes

2024-04-02 15:53 UTC, MaxGhenis requested changes

2024-04-09 13:22 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ia/tax/income/net_income/ia_pension_exclusion.py
> +        is_eligible = person("ia_pension_exclusion_eligible", period)
you dont need this since it's the defined_for

2024-04-09 13:55 UTC, PavelMakarchuk requested changes

2024-04-09 13:55 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ia/tax/income/ia_amt_indiv.py
> +                    fsvals.WIDOW,
```suggestion
                    fsvals.SURVIVING_SPOUSE,
```

2024-04-10 22:13 UTC, PavelMakarchuk requested changes

2024-04-10 22:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ia/tax/income/net_income/ia_pension_exclusion_eligible.py
> +    unit = USD
```suggestion
```

2024-04-10 22:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ia/tax/income/net_income/ia_pension_exclusion_eligible.py
> +        an_elder = person("age", period) >= p.minimum_age
```suggestion
        age = person("age", period)
        age_eligible = age >= p.minimum_age
```

2024-04-10 22:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ia/tax/income/net_income/ia_pension_exclusion_eligible.py
> +        is_elderly = (is_head & an_elder) | (is_spouse & an_elder)
```suggestion
        head_or_spouse_age_eligible = (is_head | is_spouse) & age_eligible
```

2024-04-10 22:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ia/tax/income/net_income/ia_pension_exclusion_eligible.py
> +        has_disability = person("is_permanently_and_totally_disabled", period)
```suggestion
        is_disabled = person("is_permanently_and_totally_disabled", period)
```

2024-04-10 22:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ia/tax/income/net_income/ia_pension_exclusion_eligible.py
> +        is_disabled = (is_head & has_disability) | (is_spouse & has_disability)
```suggestion
        is_head_or_spouse_disabled = (is_head | is_spouse) & is_disabled
```

2024-04-10 22:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ia/tax/income/net_income/ia_pension_exclusion_eligible.py
make a unit test for this

2024-04-11 04:00 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ia/tax/income/net_income/ia_pension_exclusion_eligible.py
> +        is_head = person("is_tax_unit_head", period)
use instead
```suggestion
        is_head_or_spouse = person("is_tax_unit_head_or_spouse", period)
```

2024-04-12 08:10 UTC, yy3187 commented on policyengine_us/variables/gov/states/ia/tax/income/net_income/ia_pension_exclusion_eligible.py
already made the test file ia_pension_exclusion_eligible.yaml

2024-04-12 12:33 UTC, PavelMakarchuk approved these changes

2024-04-12 20:25 UTC, MaxGhenis approved these changes

2024-04-12 20:25 UTC, merged