Fix Virginia low-income credit calculation
PolicyEngine/policyengine-us pull request #4261
Opened 2024-03-21 23:45 UTC by PavelMakarchuk

Fixes #4260

2024-03-22 01:07 UTC, PavelMakarchuk commented
Will also add itemized ded. fix

2024-03-31 20:55 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/deductions/va_itemized_deductions.py
This should be more readable now

2024-04-01 06:40 UTC, MaxGhenis requested changes

2024-04-01 06:40 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/va/tax/income/deductions/va_reduced_itemized_deductions.py
> +        # The federal limitation on itemized deductions does not apply during the TCJA period
Move this `instant_str` piece to the code section where it's used

2024-04-01 06:40 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/va/tax/income/deductions/va_reduced_itemized_deductions.py
can you shrink this further? still almost 100 lines. parameterizing some of the lists could help

2024-04-01 20:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/va/tax/income/deductions/va_reduced_itemized_deductions.py
Add the parameters, 
I could shrink the code by removing the comments (22 lines) but it seems like having throughout documentation of the steps, given the complexity, would be very useful. 
I would also not like to separate more computation steps out as it is all one section of the form

2024-04-02 15:56 UTC, MaxGhenis approved these changes

2024-04-02 15:56 UTC, merged