Alabama 2023 Tax Rules
PolicyEngine/policyengine-us pull request #4274
Opened 2024-03-22 14:20 UTC by XZ-mabel

Fixes #4169

2024-03-26 15:26 UTC, PavelMakarchuk commented
[this](https://support.taxslayer.com/hc/en-us/articles/360021569452-What-s-new-in-2023-for-Alabama) website talks about a retirement exemptions, could you double check. I see [this](https://www.revenue.alabama.gov/wp-content/uploads/2024/01/23schrsinstr.pdf) form

2024-03-29 14:22 UTC, PavelMakarchuk commented on changelog_entry.yaml
need to add the 2023 retirement deduction

2024-04-04 05:04 UTC, XZ-mabel commented on changelog_entry.yaml
Have just added the deduction.

2024-04-04 14:34 UTC, PavelMakarchuk requested changes

2024-04-04 14:34 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/al/tax/income/exemptions/retirement/al_retirement_exemption_eligible_person.py
> +class al_retirement_exemption_eligible_person(Variable):
make three variables:
`al_retirement_exemption_eligible_person`
- the return here should be `eligible_age & head_or_spouse`
`al_retirement_exemption_person`
- person level min_(pension_income, p.max_amount) and defined for eligible person
`al_retirement_exemption`
- same as it is now

2024-04-04 14:34 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/al/tax/income/exemptions/retirement/age_threshold.yaml
> +  label: Alabama retirement exemption eligible age
```suggestion
  label: Alabama retirement exemption age threshold
```

2024-04-04 14:34 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/al/tax/income/exemptions/retirement/age_threshold.yaml
> +description: Alabama provides the retirement exemption above this age threshold
```suggestion
description: Alabama provides the retirement exemption to filers at or above this age threshold.
```

2024-04-04 14:34 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/al/tax/income/exemptions/retirement/age_threshold.yaml
> +      href: https://www.revenue.alabama.gov/wp-content/uploads/2024/01/23schrsinstr.pdf
add page, all pdf

2024-04-04 14:34 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/al/tax/income/exemptions/retirement/max_amount.yaml
> +  label: Alabama retirement exemption maximum amount
```suggestion
  label: Alabama retirement exemption cap

2024-04-04 14:34 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/al/tax/income/exemptions/retirement/max_amount.yaml
rename cap.yaml

2024-04-04 14:34 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/al/tax/income/exemptions/retirement/max_amount.yaml
> +description: Alabama provides the retirement exemption with this maximum amount
```suggestion
description: Alabama caps the retirement exemption at this amount.
```

2024-04-04 14:34 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/al/tax/income/exemptions/retirement/al_retirement_exemption_eligible_person.py
add this to the list of exemptions/deductions

2024-04-05 14:39 UTC, PavelMakarchuk requested changes

2024-04-05 14:39 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/al/tax/income/exemptions/retirement/al_retirement_exemption_person.py
> +    label = "Alabama retirement exemption"
```suggestion
    label = "Alabama retirement exemption for each person"
```

2024-04-05 14:39 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/al/tax/income/exemptions/retirement/al_retirement_exemption_eligible_person.py
> +    unit = USD
```suggestion
```

2024-04-05 14:39 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/al/tax/income/exemptions/dependent.yaml
> +    href: https://www.revenue.alabama.gov/ultraviewer/viewer/basic_viewer/index.html?form=2024/01/23f40bk.pdf#page=9
I think this should be page 10, could you double check all the references that the pages are correct?

2024-04-05 14:39 UTC, PavelMakarchuk commented on changelog_entry.yaml
need a git pull upstream master

2024-04-23 15:26 UTC, PavelMakarchuk requested changes

2024-04-23 15:26 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/al/tax/income/deductions/federal_tax/countable_sources.yaml
> +    - al_retirement_exemption
delete this here

2024-04-23 15:26 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/al/tax/income/exemptions/retirement/al_retirement_exemption_person.py
> +        pension_income = person("taxable_pension_income", period)
we need more income types, including:
```
    - taxable_ira_distributions
    - taxable_401k_distributions
    - taxable_sep_distributions
    - taxable_403b_distributions
    - keogh_distributions # Keogh plans don't have a Roth option.
    - pension_income
```
Then add this to the list of deductions.yaml

2024-04-23 15:26 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/al/tax/income/exemptions/retirement/al_retirement_exemption_person.py
> +        pension_income = person("taxable_pension_income", period)
use an add function 
add(person, period, ["taxable_ira_distributions", "taxable_401k_distributions"....]

2024-04-23 15:26 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/al/tax/income/exemptions/retirement/al_retirement_exemption_person.py
> +        pension_income = person("taxable_pension_income", period)
when adding to the list of deduction check if it is only a 2023 or did it exist before (the deduction)

2024-04-26 06:01 UTC, MaxGhenis requested changes

2024-04-26 06:01 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/al/tax/income/exemptions/retirement/al_retirement_exemption_person.py
> +                "taxable_ira_distributions",
taxable_retirement_distributions includes the 4 categories
```suggestion
                "taxable_retirement_distributions", "taxable_pension_income"]
```

2024-04-29 09:12 UTC, PavelMakarchuk requested changes

2024-04-29 09:12 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/al/tax/income/exemptions/retirement/al_retirement_exemption_person.py
> +            ],
```suggestion
```

2024-04-29 09:12 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/al/tax/income/exemptions/retirement/al_retirement_exemption_person.py
> +            ],
you have doubled the inputs..

2024-04-29 09:12 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/al/tax/income/exemptions/retirement/al_retirement_exemption_person.py
> +            ],
please adjust tests as well to only have `"taxable_retirement_distributions", "taxable_pension_income" `as inputs

2024-05-02 09:33 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/al/tax/income/deductions/itemized/sources.yaml
> +  2023-01-01:
add of the exemptions from above has to also be included in the list! Not just the new one

2024-05-02 16:08 UTC, PavelMakarchuk approved these changes

2024-05-02 17:27 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/al/tax/income/exemptions/retirement/al_retirement_exemption_eligible_person.py
re-request my review after this

2024-05-05 22:18 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/al/tax/income/agi/deductions.yaml
Include the exemption in this file

2024-05-06 16:11 UTC, PavelMakarchuk approved these changes

2024-05-06 20:19 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/al/tax/income/exemptions/retirement/al_retirement_exemption_person.py
> +    documentation = "https://casetext.com/statute/code-of-alabama/title-40-revenue-and-taxation/chapter-18-income-taxes/article-1-general-provisions/section-40-18-19-exemptions-generally"
add the form for this exemption, since the legal code's "taxable retirement income" is ambiguous

2024-05-06 20:53 UTC, MaxGhenis requested changes
please include both the legal code and the form. you can make it a tuple of strings. also the form you linked only describes distributions; can you point to where pensions are also part of it?

2024-05-06 22:56 UTC, XZ-mabel commented
> please include both the legal code and the form. you can make it a tuple of strings. also the form you linked only describes distributions; can you point to where pensions are also part of it?

In the form 40 instructions, on page 14 it mentions "Use Schedule RS to report pension and annuity income you received. Also, use these lines to report distributions from SEP, Keogh, 401(k)(2), 403(b), and profit sharing plans. Generally, you will receive a Form 1099-R or a Form W-2P showing the amount of your distribution", and that's why I thought pension income should be part of the total retirement income.

Also, I encountered this when I'm trying to run the tests under Alabama folder. ValueError(
ValueError: Unexpected attributes in definition of variable "co_child_care_subsidies": 'exhaustive_parameter_dependencies'.

2024-05-06 23:11 UTC, MaxGhenis commented
OK in that case please add the instructions as a reference. In general please add all references needed to corroborate logic in formulas.

Try `pip install -U policyengine-core` to fix the test error

2024-05-06 23:18 UTC, XZ-mabel commented
> OK in that case please add the instructions as a reference. In general please add all references needed to corroborate logic in formulas.
> 
> Try `pip install -U policyengine-core` to fix the test error

Got it. Thank you.

2024-05-07 15:23 UTC, MaxGhenis approved these changes

2024-05-07 15:23 UTC, merged