Add 2023 New Mexico Tax Rules
PolicyEngine/policyengine-us pull request #4300
Opened 2024-03-26 04:45 UTC by xianxinzhu

Fixes #4192

2024-03-26 13:27 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/de/tax/income/combined_separate_status/de_personal_credit.py
I dont think this should be in this PR right?

2024-03-26 16:25 UTC, xianxinzhu commented on policyengine_us/variables/gov/states/de/tax/income/combined_separate_status/de_personal_credit.py
Yes, I'll delete that. I actually have no clue why it is here. Sorry

2024-03-26 20:39 UTC, PavelMakarchuk commented
Could you sum up the changes that happened here? It is easier to double check

2024-03-27 03:58 UTC, xianxinzhu commented
- Update the low income comprehensive tax rebate for filers with different exemptions.
- Add the 2023 references for the unchanging parameters.

2024-03-27 18:17 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Add 2023 New Mexico Tax Rules.
```suggestion
    - 2023 New Mexico Tax Rules.
```

2024-03-27 18:17 UTC, PavelMakarchuk approved these changes

2024-03-27 19:25 UTC, MaxGhenis requested changes

2024-03-27 19:25 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/nm/tax/income/rebates/low_income/amount/five_exemptions.yaml
>        2021-01-01: 1_001
Then use `calc(..., right=True)` in the formula. This better mirrors the law.
```suggestion
      2021-01-01: 1_000
```

2024-03-27 19:25 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/nm/tax/income/rebates/low_income/amount/five_exemptions.yaml
>      - title: New Mexico 2022 PIT-RC, page 58, SECTION II LOW INCOME COMPREHENSIVE TAX REBATE
```suggestion
    # The law adjusts for inflation beginning in 2022, but no values changed in 2022.
    - title: New Mexico 2022 PIT-RC, page 58, SECTION II LOW INCOME COMPREHENSIVE TAX REBATE
```

2024-03-29 15:21 UTC, MaxGhenis approved these changes
good to merge after this

2024-03-29 15:21 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/nm/tax/income/rebates/low_income_comprehensive/nm_low_income_comprehensive_tax_rebate.py
>                  exemptions >= 6,
delete and use `default`

2024-03-29 15:21 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/nm/tax/income/rebates/low_income_comprehensive/nm_low_income_comprehensive_tax_rebate.py
> +                p.amount.six_exemptions.calc(agi, right=True),
```suggestion
], default = p.amount.six_exemptions.calc(agi, right=True),
```

2024-03-31 22:25 UTC, merged