Add 2023 Utah Tax Rules
PolicyEngine/policyengine-us pull request #4351
Opened 2024-04-09 04:28 UTC by JudyZ13

Fixes #4198

2024-04-11 14:37 UTC, PavelMakarchuk requested changes

2024-04-11 14:37 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ut/tax/income/credits/taxpayer/personal_exemption.yaml
>    unit: currency-USD
```suggestion
  unit: currency-USD
  uprating: gov.irs.uprating
  period: year
```

2024-04-11 14:37 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ut/tax/income/credits/taxpayer/phase_out/threshold.yaml
>    unit: currency-USD
```suggestion
  unit: currency-USD
  uprating: gov.irs.uprating

```

2024-04-16 17:16 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Add 2023 Utah Tax Rules.
```suggestion
    - 2023 Utah Tax Rules.
```

2024-04-16 17:22 UTC, PavelMakarchuk requested changes

2024-04-16 17:22 UTC, PavelMakarchuk commented on changelog_entry.yaml
could you add the reference to policyengine_us/parameters/gov/states/ut/tax/income/rate.yaml

2024-04-16 17:22 UTC, PavelMakarchuk commented on changelog_entry.yaml
Could you also check this piece:
![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/430f3ead-2a29-4aba-90b4-f8f56b1eaf2f)

2024-04-16 21:46 UTC, PavelMakarchuk commented on changelog_entry.yaml
What would be the difference to the current ut_personal_exemption?

2024-04-17 21:53 UTC, JudyZ13 commented on changelog_entry.yaml
<img width="191" alt="image" src="https://github.com/PolicyEngine/policyengine-us/assets/112495414/073e22bd-c9e0-4e53-b4b3-76b8a0941520">
I think there is not any difference? In the tax form it just sums up all the qualifying dependents and I think the current ut_personal_exemption does the same?

2024-04-18 14:33 UTC, PavelMakarchuk approved these changes

2024-04-18 15:05 UTC, MaxGhenis requested changes

2024-04-18 15:05 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ut/tax/income/credits/at_home_parent/amount.yaml
> +    - title: 2023 Utah Indivdual Income Tax Form
and elsewhere
```suggestion
    - title: 2023 Utah Individual Income Tax Form
```

2024-04-18 15:05 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ut/tax/income/credits/taxpayer/phase_out/threshold.yaml
> +    - title: 2023 TC-40  Utah Individual Income Tax Form (Line 17)
add legal code reference

2024-04-25 18:38 UTC, MaxGhenis approved these changes

2024-04-25 19:40 UTC, merged