Adjust the Missouri deductions metadata to align with model standards
PolicyEngine/policyengine-us pull request #4378
Opened 2024-04-11 17:03 UTC by Kevintowne

Fixes #4327

2024-04-11 18:16 UTC, PavelMakarchuk commented on changelog_entry.yaml
remove all changes related to the expenses

2024-04-11 18:37 UTC, PavelMakarchuk requested changes

2024-04-11 18:37 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/mo/tax/income/deductions/federal_income_tax/ignored_credits.yaml
> +  label: Missouri ignored credits in federal income tax deduction
```suggestion
  label: Missouri ignored credits in federal income tax deduction
  period: year
```

2024-04-11 18:37 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/mo/tax/income/deductions/federal_income_tax/ignored_credits.yaml
> +  label: Missouri ignored credits in federal income tax deduction
add period everywhere, where missing

2024-04-12 12:51 UTC, PavelMakarchuk requested changes

2024-04-12 12:51 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/mo/tax/income/credits/property_tax/public_assistance_types.yaml
>    label: Types of public assistance in MO property tax credit gross income
```suggestion
  label: Missouri property tax credit gross income public assistance sources
```

2024-04-12 12:51 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/mo/tax/income/credits/property_tax/rent_property_tax_limit.yaml
>    label: MO property tax credit limit for property renters
```suggestion
  label: Missouri property tax credit limit for property renters
```

2024-04-12 12:51 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/mo/tax/income/credits/wftc/eitc_match.yaml
> +  label: Missouri EITC percent
```suggestion
  label: Missouri EITC match
```

2024-04-12 12:51 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/mo/tax/income/deductions/federal_income_tax/ignored_credits.yaml
>    unit: variable
```suggestion
  unit: list
```

2024-04-12 12:51 UTC, PavelMakarchuk commented on policyengine_us/variables/household/expense/utilities/broadband_cost.py
revert all utility expense related variables - wrong PR

2024-04-22 13:38 UTC, PavelMakarchuk requested changes

2024-04-22 13:38 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/mo/tax/income/deductions/mo_max_private_pension.yaml
> +  period: year
```suggestion
```

2024-04-23 17:46 UTC, PavelMakarchuk approved these changes

2024-04-23 18:17 UTC, MaxGhenis approved these changes

2024-04-23 18:20 UTC, MaxGhenis commented
Merging this. Thank you. But let's hold off on further cleanup PRs until merging all possible commits from #4210. I did much of this sort of work there so it would duplicate work and cause merge conflicts.

2024-04-23 18:20 UTC, merged