Include 403b_contributions in pre_tax_contributions
PolicyEngine/policyengine-us pull request #4382
Opened 2024-04-11 19:57 UTC by yuantian0204

Fixes #4369

2024-04-15 16:35 UTC, PavelMakarchuk requested changes

2024-04-15 16:35 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/gross_income/pre_tax_contributions.yaml
> +    - roth_403b_contributions
```suggestion
```

2024-04-15 16:35 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/gross_income/pre_tax_contributions.yaml
add a changelog_entry - then request my review

2024-04-15 22:15 UTC, PavelMakarchuk commented
Could you run `make format`

2024-04-16 18:25 UTC, yuantian0204 reviewed
@PavelMakarchuk Request for reviewing changes

2024-04-29 15:09 UTC, MaxGhenis approved these changes
Good to merge after this

2024-04-29 15:09 UTC, MaxGhenis commented on policyengine_us/parameters/gov/irs/gross_income/pre_tax_contributions.yaml
> +    - traditional_403b_contributions
Move below 401k since it's most similar to that

2024-05-02 09:02 UTC, merged