Add SSI Couple Test
PolicyEngine/policyengine-us pull request #4403
Opened 2024-04-15 19:00 UTC by CalebPena

#1900

2024-05-02 14:24 UTC, MaxGhenis commented
Michigan home heating credit integration tests are failing because that credit is based on an income measure that includes SSI. Looks like the integration test initially defined a household that (wrongly) didn’t previously qualify for SSI but now does with your fix. I'd suggest setting `ssi: 0` to each person entity in `home_heating/integration.yaml` to get back to the original expected outputs and pass the tests again.

2024-05-02 14:27 UTC, MaxGhenis requested changes

2024-05-02 14:27 UTC, MaxGhenis commented on changelog_entry.yaml
> +    - Countable income now includes the spouses income when both the head and spouse are eligible.
```suggestion
    - Countable income now includes the spouse's income when both the head and spouse are eligible.
```

2024-05-02 14:27 UTC, MaxGhenis commented on policyengine_us/variables/gov/ssa/ssi/eligibility/status/is_ssi_ineligible_spouse.py
> +        return spouse & ~person("is_ssi_eligible_spouse", period) & ~eligible
Just for stylistic consistency within the formula
```suggestion
        eligible_spouse = person("is_ssi_eligible_spouse", period)
        return spouse & ~eligible_spouse & ~eligible
```

2024-05-03 20:08 UTC, CalebPena commented
> Michigan home heating credit integration tests are failing because that credit is based on an income measure that includes SSI. Looks like the integration test initially defined a household that (wrongly) didn’t previously qualify for SSI but now does with your fix. I'd suggest setting `ssi: 0` to each person entity in `home_heating/integration.yaml` to get back to the original expected outputs and pass the tests again.

I think that the couple in this test was eligible for SSI previously, but the spouse's income was not considered, so they had a different SSI amount. Setting SSI to 0 did not work.

2024-05-03 22:22 UTC, MaxGhenis commented
Can you set the output to the result for the failing integration tests after setting it to zero? We could calculate it by hand but since they previously worked and your PR doesn't change those programs we can just keep them working.

2024-05-06 17:52 UTC, MaxGhenis approved these changes

2024-05-06 17:53 UTC, merged