Add Rhode Island 2023 rules
PolicyEngine/policyengine-us pull request #4406
Opened 2024-04-16 16:16 UTC by hua7450

2024-04-18 12:22 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ri/tax/income/agi/subtractions/social_security/limit/income.yaml
> +  - title: Rhode Island 2023 Modification for Taxable social security income worksheet
I think the amounts here are adjusted with inflation:
![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/c2bca45b-ddcb-472b-9c5e-dbb3a1434a97)

We need to add some metadata for inflation adjustments and rounding, see DC:
https://github.com/PolicyEngine/policyengine-us/pull/4306

2024-04-18 14:19 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ri/tax/income/credits/property_tax/max_amount.yaml
> +  2023-01-01: 650
could you add uprating and rounding to the property tax files as well?

2024-04-18 14:20 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ri/tax/income/exemption/amount.yaml
>    2021-01-01: 4_250
could you check all the file that adjust every year if we need updates and rounding?

2024-04-18 14:21 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ri/tax/income/rate.yaml
> +        uprating: gov.irs.uprating
might need rounding here too right? Maybe nearest 50

2024-04-22 13:02 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ri/tax/income/deductions/standard/phase_out/increment.yaml
> +  2023-01-01: 6_700
I think we need to uprate this as well:
![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/d132ff4a-489a-43e7-87b8-f380eb61ebed)

2024-04-22 13:04 UTC, PavelMakarchuk requested changes

2024-04-22 13:04 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ri/tax/income/rate.yaml
> +      interval: 50
we need to add this metadata piece to each individual threshold (besides 0) as this structure will also uprate the rate, which should stay the same

2024-04-22 23:34 UTC, MaxGhenis approved these changes

2024-04-22 23:34 UTC, merged