Consolidated state level additions variables across all state models
PolicyEngine/policyengine-us pull request #4408
Opened 2024-04-16 18:41 UTC by masterismail

Fixes #3650

2024-04-16 22:23 UTC, PavelMakarchuk requested changes

2024-04-16 22:23 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ct/tax/income/ct_additions.py
this seems to be a duplicate file - we already have a `ct_additions` file - please delete one of them

2024-04-16 22:23 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/me/tax/income/adjusted_gross_income/me_additions.py
>      label = "ME AGI additions"
```suggestion
    label = "Maine AGI additions"
```
While we are in here

2024-04-16 22:23 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ne/tax/income/ne_additions.py
>      label = "NE AGI additions to federal AGI"
```suggestion
    label = "Nebraska AGI additions to federal AGI"
```

2024-04-16 22:23 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ny/tax/income/adjusted_gross_income/ny_additions.py
>      label = "NY AGI additions"
```suggestion
    label = "New York AGI additions"
```

2024-04-16 22:23 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/or/tax/income/or_additions.py
>      label = "OR income additions"
```suggestion
    label = "Oregon income additions"
```

2024-04-16 22:23 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/wi/tax/income/additions/wi_additions.py
>      label = "WI additions to federal adjusted gross income"
```suggestion
    label = "Wisconsin additions to federal adjusted gross income"
```

2024-04-17 06:38 UTC, masterismail commented on changelog_entry.yaml
> +
done

2024-04-17 06:39 UTC, masterismail commented on policyengine_us/variables/gov/states/ct/tax/income/ct_additions.py
done

2024-04-17 13:42 UTC, PavelMakarchuk commented
@masterismail some tests still seem to fail, could take a look at the usage of:
`ut_additions_to_income` , `nj_agi_additions` , and `me_agi_additions` across the model and adjust where needed

2024-04-17 16:56 UTC, masterismail commented
> @masterismail some tests still seem to fail, could take a look at the usage of: `ut_additions_to_income` , `nj_agi_additions` , and `me_agi_additions` across the model and adjust where needed

fixed them ! apologies for the oversight

2024-04-17 17:21 UTC, PavelMakarchuk commented
> Details

@masterismail No worries, it takes some time to dig through the whole code base and get familiar with it. I think the last file that needs should be `wi_income_additions`  , my bad I missed it initially.

2024-04-17 20:03 UTC, PavelMakarchuk approved these changes

2024-04-17 20:42 UTC, MaxGhenis approved these changes

2024-04-17 20:43 UTC, merged