Fix New York household credit calculation
PolicyEngine/policyengine-us pull request #4414
Opened 2024-04-17 20:36 UTC by Shinuing

Fixes #4399

2024-04-17 22:27 UTC, PavelMakarchuk requested changes

2024-04-17 22:27 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ny/tax/income/credits/household_credit/non_single/base.yaml
>        1986-01-01: 20_000
```suggestion
      1986-01-01: 22_000
```

2024-04-17 22:27 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ny/tax/income/credits/household_credit/non_single/base.yaml
> +      1986-01-01: 22_000
```suggestion
```

2024-04-17 22:27 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ny/tax/income/credits/household_credit/non_single/base.yaml
>        1986-01-01: 20_000
Would something like this work? (We are basically extending the $60 bracket right?)

2024-04-17 23:21 UTC, Shinuing commented
Not really. The additional amount are different.


On Apr 17, 2024, at 17:27, Pavel Makarchuk ***@***.***> wrote:

﻿

@PavelMakarchuk requested changes on this pull request.

________________________________

In policyengine_us/parameters/gov/states/ny/tax/income/credits/household_credit/non_single/base.yaml<https://github.com/PolicyEngine/policyengine-us/pull/4414#discussion_r1569616343>:

> @@ -28,6 +28,10 @@ brackets:
       1986-01-01: 60
   - threshold:
       1986-01-01: 20_000


⬇️ Suggested change

-      1986-01-01: 20_000
+      1986-01-01: 22_000


________________________________

In policyengine_us/parameters/gov/states/ny/tax/income/credits/household_credit/non_single/base.yaml<https://github.com/PolicyEngine/policyengine-us/pull/4414#discussion_r1569616461>:

> +    amount:
+      1986-01-01: 60
+  - threshold:
+      1986-01-01: 22_000


⬇️ Suggested change

-    amount:
-      1986-01-01: 60
-  - threshold:
-      1986-01-01: 22_000


________________________________

In policyengine_us/parameters/gov/states/ny/tax/income/credits/household_credit/non_single/base.yaml<https://github.com/PolicyEngine/policyengine-us/pull/4414#discussion_r1569616737>:

> @@ -28,6 +28,10 @@ brackets:
       1986-01-01: 60
   - threshold:
       1986-01-01: 20_000


Would something like this work? (We are basically extending the $60 bracket right?)

—
Reply to this email directly, view it on GitHub<https://github.com/PolicyEngine/policyengine-us/pull/4414#pullrequestreview-2007407231>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AU4PV66YEKQEX65HGDXNV2DY53ZOFAVCNFSM6AAAAABGMAN7TGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMBXGQYDOMRTGE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-04-17 23:22 UTC, PavelMakarchuk commented
@Shinuing is it $60 between 7,000 and 20,000 for the base amount?

2024-04-18 01:14 UTC, Shinuing commented
> @Shinuing is it $60 between 7,000 and 20,000 for the base amount?

No it's $65

<img width="1364" alt="Screen Shot 2024-04-17 at 8 14 21 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/87620347/d04ec0eb-2b1e-4436-8cc0-5549b2ca75b6">

2024-04-18 15:10 UTC, PavelMakarchuk commented
> > @Shinuing is it $60 between 7,000 and 20,000 for the base amount?
> 
> No it's $65
> 
> <img alt="Screen Shot 2024-04-17 at 8 14 21 PM" width="1364" src="https://private-user-images.githubusercontent.com/87620347/323432237-d04ec0eb-2b1e-4436-8cc0-5549b2ca75b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NTMyNDcsIm5iZiI6MTcxMzQ1Mjk0NywicGF0aCI6Ii84NzYyMDM0Ny8zMjM0MzIyMzctZDA0ZWMwZWItMmIxZS00NDM2LThjYzAtNTU0OWIyY2E3NWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE1MDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NGEzMzY3OTI1OWE4YjczYmU1NjYxM2IyZWIyZmI3ZGIyMzY3MDY3MDc0NTRkYjM5NGEyODBlNTc2NjA5NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5RJP2I26v6-d3t82EgM0nWTq2_yqg-smwAbJBVdOiPk">

My bad for the misunderstanding, cant we summarize this bracket into one, (just in the particular file that we are talking about):
![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/823c4bf1-97f7-43f1-b821-9fb39bbf4376)

2024-04-18 16:49 UTC, Shinuing commented
> My bad for the misunderstanding, cant we summarize this bracket into one, (just in the particular file that we are talking about): 

NO! The additional amount are different

2024-04-18 17:49 UTC, PavelMakarchuk commented
> > My bad for the misunderstanding, cant we summarize this bracket into one, (just in the particular file that we are talking about):
> 
> NO! The additional amount are different

But isn't this represented in base.yaml?

2024-04-18 18:22 UTC, Shinuing commented
> > > My bad for the misunderstanding, cant we summarize this bracket into one, (just in the particular file that we are talking about):
> > 
> > 
> > NO! The additional amount are different
> 
> But isn't this represented in base.yaml?

Yes you're right. Just merged

2024-04-18 18:32 UTC, PavelMakarchuk approved these changes

2024-04-19 05:38 UTC, MaxGhenis approved these changes

2024-04-19 05:38 UTC, merged