Add 2023 Idaho Tax Rules
PolicyEngine/policyengine-us pull request #4437
Opened 2024-04-23 03:15 UTC by JudyZ13

Fixes #4174

2024-04-23 15:14 UTC, PavelMakarchuk requested changes

2024-04-23 15:14 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/id/tax/income/deductions/retirement_benefits/cap.yaml
> +    - title: Individual Income Tax Forms and Instructions 2023
I think we need to add uprating metadata here (update with inflation)

2024-04-25 10:57 UTC, PavelMakarchuk approved these changes

2024-04-25 10:57 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/id/tax/income/deductions/retirement_benefits/cap.yaml
>    2022-01-01: 0
```suggestion
```

2024-04-25 18:39 UTC, MaxGhenis approved these changes

2024-04-25 19:54 UTC, merged