Add 2023 Massachusetts Tax Rules
PolicyEngine/policyengine-us pull request #4457
Opened 2024-04-26 11:26 UTC by Mshuning

Fixes #4180

2024-04-29 09:27 UTC, PavelMakarchuk requested changes

2024-05-02 09:13 UTC, PavelMakarchuk requested changes

2024-05-02 09:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/tax/income/credits/ma_dependent_or_dependent_care_credit.py
> +        p = parameters(period).gov.states.ma.tax.income.credits.dependent_care
Is the child and family tax credit a completely new credit concept or did MA just merge the two previous credits? I dont think I see the exact definition in the 2021 tax forms

2024-05-02 09:13 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +- bump: patch
```suggestion
- bump: minor
```

2024-05-02 09:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/tax/income/credits/ma_dependent_or_dependent_care_credit.py
> +        return tax_unit("ma_dependent_credit", period)
```suggestion
        dependent_credit = tax_unit("ma_dependent_credit", period)
        if p.in_effect:
            return max_(
                dependent_credit,
                tax_unit("ma_dependent_care_credit", period),
            )
        return dependent_credit
```

2024-05-02 09:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/tax/income/credits/ma_dependent_or_dependent_care_credit.py
> +        p = parameters(period).gov.states.ma.tax.income.credits.dependent_care
The question is whether the rules stay the same or if we need to re-write the logic

2024-05-02 13:23 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ma/tax/income/credits/ma_dependent_or_dependent_care_credit.yaml
> +- name: 2023 Max of the credits.
add 2024 test

2024-05-02 13:29 UTC, PavelMakarchuk requested changes

2024-05-02 13:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/dependent_care/in_effect.yaml
> +description: Massachusetts replaces the Dependent Care Tax Credit with the Child and Family Tax Credit if this is true.
```suggestion
description: Massachusetts replaces the Dependent and Dependent Care Tax Credit with the Child and Family Tax Credit if this is false.  
```

2024-05-02 13:29 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/tax/income/credits/ma_dependent_or_dependent_care_credit.py
>      defined_for = StateCode.MA
add documentation metadata stating that from 2023 this is called the Child and Family tax credit

2024-05-02 16:11 UTC, PavelMakarchuk approved these changes

2024-05-02 17:21 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/states/ma/tax/income/credits/ma_dependent_or_dependent_care_credit.yaml
> +- name: 2022 Max of the credits.
```suggestion
- name: 2022 max of the credits.
```

2024-05-06 16:02 UTC, PavelMakarchuk requested changes

2024-05-06 16:02 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/senior_circuit_breaker/income/disallowed_deductions.yaml
>    name: ma_scb_disallowed_deductions
```suggestion
```

2024-05-06 16:02 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/tax/income/credits/senior_circuit_breaker/income/disallowed_deductions.yaml
>    name: ma_scb_disallowed_deductions
Could you remove all -name tags if thee are more while we are in here

2024-05-07 12:03 UTC, PavelMakarchuk approved these changes

2024-05-07 12:04 UTC, merged