Montgomery County, MD Local EITC
PolicyEngine/policyengine-us pull request #4471
Opened 2024-05-02 17:13 UTC by YichunRen

FIX #1010

2024-05-07 01:35 UTC, PavelMakarchuk requested changes

2024-05-07 01:35 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/md/tax/income/credits/eitc/md_eitc.py
> +        return non_refundable_eitc + refundable_eitc(1 + p.match * montgomery)
could you split the formula into multiple steps?

2024-05-07 01:35 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/md/tax/income/credits/eitc/md_eitc.py
> +    # adds = ["md_non_refundable_eitc", "md_refundable_eitc"]
```suggestion
```

2024-05-07 01:35 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/md/tax/income/credits/eitc/montgomery/match.yaml
> +description: Montgomery County matches this percentage of the State Earned Income Tax Credit for taxpayers who qualify for the Refundable EITC from the State of Maryland, called the Working Families
```suggestion
description: Montgomery County matches this percentage of the refundable Maryland Earned Income Tax Credit.
```

2024-05-07 01:35 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/md/tax/income/credits/eitc/montgomery/match.yaml
> +  unit: /1
```suggestion
  unit: /1
  period: year
```

2024-05-07 01:35 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/md/tax/income/credits/eitc/montgomery/match.yaml
> +      href: https://www3.montgomerycountymd.gov/311/Solutions.aspx?SolutionId=1-4DAM0I
2016 and prior law:
https://codelibrary.amlegal.com/codes/montgomerycounty/latest/montgomeryco_md/0-0-0-129735

It seems like it was not updated with the new bill 
I am reading this as a full match but 90% in 2025 and 95% in 2026 


But it definitely is 56% starting in 2023/07 - need to find more up to date bill

2024-05-14 02:24 UTC, PavelMakarchuk requested changes

2024-05-14 02:24 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/md/tax/income/credits/eitc/refundable/montgomery_refundable_eitc.py
> +class montgomery_refundable_eitc(Variable):
```suggestion
class md_montgomery_eitc(Variable):
```

2024-05-14 02:24 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/md/tax/income/credits/eitc/refundable/montgomery_refundable_eitc.py
> +    label = "Montgomery EITC"
```suggestion
    label = "Maryland montgomery county earned income tax credit"
```

2024-05-14 02:24 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/md/tax/income/credits/eitc/refundable/montgomery_refundable_eitc.py
> +        is_montgomery_resident = county == "MONTGOMERY_COUNTY_MD"
```suggestion
        in_montgomery = county == "MONTGOMERY_COUNTY_MD"
```

2024-05-14 02:24 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/md/tax/income/credits/eitc/refundable/montgomery_refundable_eitc.py
> +        md_refundable_eitc = tax_unit("md_refundable_eitc", period)
```suggestion
        state_refundable_eitc = tax_unit("md_refundable_eitc", period)
```

2024-05-14 02:24 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/md/tax/income/credits/eitc/refundable/montgomery/match.yaml
> +  label: Montgomery Refundable State EITC match
```suggestion
  label: Maryland montgomery refundable state earned income tax credit match
```

2024-05-14 02:24 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Montgomery County, MD Local EITC
```suggestion
    - Montgomery County Local EITC.
```

2024-05-14 22:39 UTC, PavelMakarchuk requested changes

2024-05-14 22:39 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/md/tax/income/credits/eitc/refundable/montgomery/match.yaml
> +    - title: 2023 Montgomery County Earned Income Credit EIC Refund
could add comments to the individual sources adding e.g. that the 2023 change is not yet reflected in the legal code

2024-05-31 11:57 UTC, PavelMakarchuk approved these changes

2024-05-31 11:57 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/md/tax/income/credits/eitc/refundable/montgomery/match.yaml
> +description: Montgomery County matches this percentage of the refundable Maryland Earned Income Tax Credit.
```suggestion
description: Montgomery County matches this percentage of the refundable Maryland earned income tax credit. 
```

2024-05-31 11:57 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/md/tax/income/credits/eitc/refundable/montgomery/match.yaml
> +  label: Maryland montgomery refundable state earned income tax credit match
```suggestion
  label: Maryland montgomery county refundable state earned income tax credit match
```

2024-05-31 12:00 UTC, MaxGhenis requested changes
please move these to the `local` folder(s) - see nyc as an example

2024-06-19 12:51 UTC, PavelMakarchuk requested changes

2024-06-19 12:51 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/md/tax/income/credits/eitc/refundable/montgomery/match.yaml
move to local

2024-06-19 12:51 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/md/tax/income/credits/eitc/refundable/montgomery_refundable_eitc.py
move to local

2024-06-19 12:51 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/md/tax/income/credits/eitc/montgomery_refundable_eitc.yaml
move to local

2024-06-20 19:17 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/local/md/montgomery/tax/income/credits/refundable.yaml
delete

2024-06-27 11:57 UTC, PavelMakarchuk requested changes

2024-06-27 11:57 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/local/md/montgomery/tax/income/credits/eitc/refundable/montgomery_refundable_eitc.py
> +        ).gov.local.md.montgomery.tax.income.credits.eitc.refundable  # policyengine_us/parameters/gov/local/md/montgomery/tax/income/credits/eitc/refundable
```suggestion
        ).gov.local.md.montgomery.tax.income.credits.eitc.refundable  
```

2024-06-27 11:57 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/local/md/montgomery/tax/income/credits/eitc/refundable/montgomery_refundable_eitc.py
> +        # check montgomery county match qualification
```suggestion
        # Check whether unit is in montgomery county 
```

2024-06-27 11:57 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/local/md/montgomery/tax/income/credits/eitc/refundable/match.yaml
> +  label: Montgomery County, Maryland EITC match
```suggestion
  label: Montgomery County EITC match
```

2024-06-27 11:57 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/local/md/montgomery/tax/income/credits/eitc/refundable/match.yaml
> +description: Montgomery County matches this percentage of the refundable Maryland earned income tax credit.
```suggestion
description: Montgomery County matches this percentage of the refundable Maryland Earned Income Tax Credit. 
```

2024-06-30 23:34 UTC, PavelMakarchuk approved these changes

2024-07-01 13:53 UTC, MaxGhenis approved these changes

2024-07-01 13:53 UTC, MaxGhenis commented on policyengine_us/variables/gov/local/md/montgomery/tax/income/credits/eitc/refundable/montgomery_refundable_eitc.py
> +    label = "Maryland montgomery county earned income tax credit"
```suggestion
    label = "Montgomery County, Maryland EITC"
```

2024-07-01 13:53 UTC, MaxGhenis commented on policyengine_us/variables/gov/local/md/montgomery/tax/income/credits/eitc/refundable/montgomery_refundable_eitc.py
> +    documentation = "Refundable Montgomery county EITC"
```suggestion
```

2024-07-01 13:54 UTC, merged