Saver's Credit
PolicyEngine/policyengine-us pull request #4506
Opened 2024-05-09 01:47 UTC by Mshuning

2024-05-09 13:47 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/credits/retirement_saving/qualified_contributions.yaml
dont need as this seems to SC

2024-05-09 14:54 UTC, Mshuning commented
@PavelMakarchuk There will be no errors if changing all starting years in every saver's credit parameter files from 2019-01-01 to 2018-01-01.

2024-05-10 02:22 UTC, Mshuning commented
@PavelMakarchuk Should `able_contributions` be included refer to [this](https://www.irs.gov/retirement-plans/plan-participant-employee/retirement-savings-contributions-savers-credit)?

> Amount of the credit
Depending on your adjusted gross income reported on your Form 1040 series return, the amount of the credit is 50%, 20% or 10% of:
> 
> contributions you make to a traditional or Roth IRA,
> elective salary deferral contributions to a 401(k), 403(b), governmental 457(b), SARSEP, or SIMPLE plan,
> voluntary after-tax employee contributions made to a qualified retirement plan (including the federal Thrift Savings Plan) or 403(b) plan,
> contributions to a 501(c)(18)(D) plan, or
> contributions made to an ABLE account for which you are the designated beneficiary (beginning in 2018).

2024-05-10 14:00 UTC, PavelMakarchuk requested changes

2024-05-10 14:00 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/credits/retirement_savings/savers_qualified_contributions.py
> +    adds = "gov.irs.credits.retirement_saving.qualified_retirement_savings_contributions"
I think we should make this a full formula since it might be negative

2024-05-10 14:00 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/credits/retirement_saving/qualified_retirement_savings_contributions.yaml
> +    - title: 26 U.S. Code § 25B - (d)
Is there a tax form for this as well?

2024-05-10 14:00 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/credits/retirement_saving/qualified_retirement_savings_contributions.yaml
> +  label: Qualified retirement savings contributions
```suggestion
  label: Saver's Credit qualified retirement savings contributions
```

2024-05-13 16:35 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/credits/retirement_savings/savers_qualified_contributions.py
> +    adds = "gov.irs.credits.retirement_saving.qualified_retirement_savings_contributions"
Just a simple:

    def formula(tax_unit, period, parameters):
        contributions = add(tax_unit, period, "gov.irs.credits.retirement_saving.qualified_retirement_savings_contributions")
        distributions = add(tax_unit, period, ["retirement_distributions'])
        return max_(contributions - distributions, 0)

2024-05-14 04:50 UTC, PavelMakarchuk requested changes

2024-05-14 04:50 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/credits/retirement_savings/savers_qualified_contributions.py
rename file and add test

2024-05-14 04:50 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/credits/retirement_savings/savers_qualified_contributions.py
> +class savers_qualified_contributions(Variable):
```suggestion
class savers_credit_qualified_contributions(Variable):
```

2024-05-14 13:21 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/credits/retirement_saving/qualified_retirement_savings_contributions.yaml
> +    - self_employed_pension_contributions
```suggestion
    - self_employed_pension_contributions
    - able_contributions
```

2024-05-14 13:24 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/credits/retirement_saving/qualified_retirement_savings_contributions.yaml
> +    - self_employed_pension_contributions
we need to create a new variable called `able_contributions_person` and use an adds in the existing `able_contributions`

2024-05-14 22:55 UTC, PavelMakarchuk approved these changes

2024-05-15 02:18 UTC, MaxGhenis requested changes

2024-05-15 02:18 UTC, MaxGhenis commented on policyengine_us/parameters/gov/irs/credits/retirement_saving/rate/threshold_adjustment/head_of_household.yaml
make these a single breakdown parameter by filing_status (joint=1)

2024-05-15 02:18 UTC, MaxGhenis commented on policyengine_us/variables/household/expense/retirement/able_contributions_person.py
> +        "Contributions made to an ABLE account by each individiual person."
```suggestion
        "Contributions made to an ABLE account by each individual."
```

2024-05-15 02:18 UTC, MaxGhenis commented on policyengine_us/variables/household/expense/retirement/able_contributions_person.py
> +    label = "ABLE contributions person"
```suggestion
    label = "Person-level ABLE contributions"
```

2024-05-15 02:18 UTC, MaxGhenis commented on policyengine_us/parameters/gov/irs/credits/retirement_saving/rate/threshold_adjustment/separate.yaml
> +description: IRS multiplies the joint threshold of the Savor's credit by this rate, for separate filers.
```suggestion
description: IRS multiplies the joint threshold of the saver's credit by this rate, for separate filers.
```

2024-05-15 02:18 UTC, MaxGhenis commented on policyengine_us/parameters/gov/irs/credits/retirement_saving/qualified_retirement_savings_contributions.yaml
> +description: The IRA sums the following elements as qualified retirement savings contributions when computing the retirement saving credit.
```suggestion
description: The IRA sums the following elements as qualified retirement savings contributions when computing the saver's credit.
```

2024-05-15 02:19 UTC, MaxGhenis commented
@nikhilwoodruff do we need to do anything if renaming an imputed PUF variable?

2024-05-16 23:01 UTC, MaxGhenis approved these changes

2024-05-16 23:01 UTC, MaxGhenis commented on policyengine_us/variables/household/expense/retirement/able_contributions_person.py
> +        "Contributions made to an ABLE account by each individiual."
```suggestion
        "Contributions made to an ABLE account by each individual."
```

2024-05-16 23:47 UTC, merged