DC Local State Supplement - additional SNAP minimum allotment
PolicyEngine/policyengine-us pull request #4511
Opened 2024-05-09 15:30 UTC by JudyZ13

2024-05-09 15:33 UTC, MaxGhenis commented on policyengine_us/variables/gov/usda/snap/dc_min_allotment.py
How about skipping this and putting the parameter in the main variable?

2024-05-09 16:09 UTC, PavelMakarchuk requested changes

2024-05-09 16:09 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/snap_min_allotment.py
> +        others_min = eligible * min_allotment.rate * relevant_max_allotment
```suggestion
        min_allotment_outside_of_DC = eligible * min_allotment.rate * relevant_max_allotment
```

2024-05-09 16:09 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/snap_min_allotment.py
> +        dc_min = spm_unit("dc_min_allotment", period)
```suggestion
        dc_min_alotment = spm_unit("dc_min_allotment", period)
```

2024-05-09 16:09 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/snap_min_allotment.py
> +        return where(snap_region == 'DC', dc_min, others_min)
```suggestion
        state_code = spm_unit.household("state_code", period)
        in_dc = state_code == "DC"
        
        return where(in_dc, dc_min, others_min)
```

2024-05-09 16:09 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/dc_min_allotment.py
> +        return dc_min_allotment
```suggestion
    adds = " parameters(period).gov.usda.snap.min_allotment.dc_amount"
```

2024-05-14 17:00 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/dc_min_allotment.py
> +    adds = " parameters(period).gov.usda.snap.min_allotment.dc_amount"
```suggestion
    adds = "gov.usda.snap.min_allotment.dc_amount"
```

2024-05-14 17:01 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/snap_min_allotment.py
> +        return where(in_dc, dc_min, others_min)
```suggestion
        return where(in_dc, dc_min_allotment, min_allotment_outside_of_DC)
```

2024-05-14 17:01 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/snap_min_allotment.py
> +        dc_min_alotment = spm_unit("dc_min_allotment", period)
```suggestion
        dc_min_allotment = spm_unit("dc_min_allotment", period)
```

2024-05-14 17:01 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - DC Additional SNAP minimum allotment
```suggestion
    - DC Additional SNAP minimum allotment.
```

2024-05-28 17:47 UTC, MaxGhenis commented
Please see #4569 also. We should probably fix that here and include an integration test to verify.

2024-07-02 00:40 UTC, PavelMakarchuk approved these changes

2024-07-02 02:09 UTC, MaxGhenis approved these changes

2024-07-02 12:50 UTC, MaxGhenis approved these changes

2024-07-02 12:50 UTC, merged