Add Oregon state uprating
PolicyEngine/policyengine-us pull request #4533
Opened 2024-05-15 18:58 UTC by Kiki-67

Fixes #4499

2024-05-15 21:56 UTC, PavelMakarchuk requested changes

2024-05-15 21:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/or/tax/income/credits/exemption/amount.yaml
need chnangelog

2024-05-15 21:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/or/tax/income/credits/retirement_income/income_threshold.yaml
> +    uprating: gov.irs.uprating
this seems to be rounded

2024-05-15 21:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/or/tax/income/credits/kicker/percent.yaml
> +  uprating: gov.irs.uprating
I dont think this is uprated with inflation -> not every parameter should be please check the legal code for the relevant sections

2024-05-15 21:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/or/tax/income/deductions/standard/amount.yaml
> +    uprating: gov.irs.uprating
rounding?

2024-05-15 21:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/or/tax/income/deductions/standard/claimable_as_dependent/min.yaml
> +  uprating: gov.irs.uprating
rounded -> all parameters that seem to be adjusted to a round number should be checked for rounding

2024-05-22 21:36 UTC, PavelMakarchuk requested changes

2024-05-22 21:36 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/or/tax/income/credits/kicker/percent.yaml
> +  label: Oregon kicker rate
I dont think this should be uprated

2024-05-22 21:36 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/or/tax/income/credits/retirement_income/income_threshold.yaml
> +        interval: 100
are you sure that the interval should be 100 and not 500

2024-05-22 21:36 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/or/tax/income/rates/head_of_household.yaml
> +      uprating: gov.irs.uprating
rounding?

2024-05-22 21:36 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/or/tax/income/rates/joint.yaml
> +      uprating: gov.irs.uprating
rounding?

2024-05-22 21:36 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/or/tax/income/rates/separate.yaml
> +      uprating: gov.irs.uprating
rounding?

2024-05-22 21:36 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/or/tax/income/rates/single.yaml
> +      uprating: gov.irs.uprating
rounding?

2024-05-22 21:36 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/or/tax/income/rates/widow.yaml
> +      uprating: gov.irs.uprating
rounding?

2024-06-05 17:19 UTC, Kiki-67 commented on policyengine_us/parameters/gov/states/or/tax/income/credits/kicker/percent.yaml
> +  label: Oregon kicker rate
delete the uprating in amount.yaml file

2024-06-05 20:38 UTC, PavelMakarchuk requested changes

2024-06-05 20:38 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/or/tax/income/credits/retirement_income/income_threshold.yaml
> +  metadata:
could we double check if we need to uprate - I dont think we do

2024-06-07 16:01 UTC, PavelMakarchuk approved these changes

2024-06-07 16:21 UTC, MaxGhenis approved these changes

2024-06-07 16:21 UTC, merged