Connecticut 2022 temporary child tax rebate
PolicyEngine/policyengine-us pull request #4606
Opened 2024-06-06 11:05 UTC by JudyZ13

Fixes #4579

2024-06-06 13:28 UTC, PavelMakarchuk commented on changelog_entry.yaml
we need to add this to the CT net income tree
It should be a non-refundable credit 
Is it only for 2022 or also for 2023 / 2024 /2025?

2024-06-06 13:29 UTC, PavelMakarchuk requested changes

2024-06-06 13:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/max.yaml
> +    - title: 2022 Child Tax Rebate
can we find the legal code source?

2024-06-06 13:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/max.yaml
> +  label: Connecticut child tax rebate maximum
```suggestion
  label: Connecticut child tax rebate cap
```

2024-06-06 13:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/max.yaml
rename to cap.yaml

2024-06-06 13:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/max.yaml
> +description: Connecticut restricts child tax rebate up to this amount.
```suggestion
description: Connecticut caps the child tax rebate to this amount.
```

2024-06-06 13:29 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ct/tax/income/rebate/ct_child_rebate_eligibility.py
> +class ct_child_tax_rebate_eligibility(Variable):
```suggestion
class ct_child_tax_rebate_eligible(Variable):
```

2024-06-06 13:29 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ct/tax/income/rebate/ct_child_rebate_eligibility.py
> +    label = "Connecticut child tax rebate eligibility"
```suggestion
    label = "Eligible for the Connecticut child tax rebate"
```

2024-06-11 17:06 UTC, PavelMakarchuk requested changes

2024-06-11 17:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/amount.yaml
> +      href: https://portal.ct.gov/drs/credit-programs/child-tax-rebate/overview
Could you look through the pdf and see if it mentions it:
https://cga.ct.gov/2022/ACT/PA/PDF/2022PA-00118-R00HB-05506-PA.PDF

2024-06-11 17:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/credits/non_refundable.yaml
> +    - ct_child_tax_rebate
cant add it to 2021 

Need to check whether only applied in 2022

2024-06-11 17:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/limit.yaml
rename to income_limit.yaml

2024-06-11 17:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/limit.yaml
> +description: Connecticut sets the child tax rebate income limits based on the filing status.
```suggestion
description: Connecticut limits the child tax rebate to filers with income below this thresholds, based on filing status.
```

2024-06-11 17:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/amount.yaml
> +description: Connecticut provides tax rabate at this amount per child
```suggestion
description: Connecticut provides a child tax rebate of this amount, per child.
```

2024-06-11 17:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ct/tax/income/rebate/ct_child_rebate_eligible.py
> +        )
```suggestion
```

2024-06-11 17:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ct/tax/income/rebate/ct_child_rebate_eligible.py
> +        income_eligibility = p.limit[filing_status] >= taxable_income
```suggestion
        return p.limit[filing_status] >= taxable_income
```

2024-06-18 17:05 UTC, PavelMakarchuk approved these changes

2024-06-18 17:05 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/cap.yaml
> +description: Connecticut caps the child tax rebate to this amount.
```suggestion
description: Connecticut caps the child tax rebate at this amount.
```

2024-06-18 19:59 UTC, MaxGhenis requested changes
is this in the legal code? if not please add a comment in the relevant files

2024-06-20 13:56 UTC, PavelMakarchuk requested changes

2024-06-20 13:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/income_limit.yaml
![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/0285910b-7fcb-4b93-9cc3-3b80fc0e2e20)


I think we need a reduction folder 
With start.yaml - amount.yaml - increment.yaml

2024-06-20 13:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/cap.yaml
> +    #not mentioned in the legal code
```suggestion
    # The legal code section has been repealed since
```

2024-06-20 13:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/cap.yaml
> +    #not mentioned in the legal code
same comment for all yaml files

2024-06-20 13:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/cap.yaml
rename to child_cap and make the value 3 as opposed to 750 - this is how the bill defines it

2024-06-20 13:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/cap.yaml
> +    - title: House Bill No. 5506 Public Act No. 22-118
```suggestion
    - title: House Bill No. 5506 Public Act No. 22-118 Sec. 411 (b) (1)
```

2024-06-20 13:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/cap.yaml
> +    - title: House Bill No. 5506 Public Act No. 22-118
specific paragraph for each parameter

2024-06-20 13:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ct/tax/income/rebate/ct_child_rebate_eligible.py
I dont think we need this as the rebates is phased out as oposed to a hard cut off

2024-06-25 17:03 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/reduction/increment.yaml
> +description: Connecticut reduces the child tax rebate amount for each of these increments of federal adjusted gross income exceeding the threshold.
```suggestion
description: Connecticut reduces the child tax rebate amount for each of these increments of state adjusted gross income exceeding the threshold.
```

2024-06-25 17:03 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/reduction/rate.yaml
> +description: Connecticut reduces the personal exemption amount by this rate for each increment of federal adjusted gross income exceeding the threshold.
```suggestion
description: Connecticut reduces the personal exemption amount by this rate for each increment of state adjusted gross income exceeding the threshold.
```

2024-06-25 17:03 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/reduction/start.yaml
> +description: Connecticut reduces the child tax rebate for filers with federal adjusted gross income above this amount, based on filing status.
```suggestion
description: Connecticut reduces the child tax rebate for filers with state adjusted gross income above this amount, based on filing status.
```

2024-06-25 17:04 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ct/tax/income/rebate/amount.yaml
> +description: Connecticut provides a child tax rebate of this amount, per child.
```suggestion
description: Connecticut provides a child tax rebate of this amount, for each eligible child.
```

2024-06-25 17:04 UTC, PavelMakarchuk approved these changes

2024-06-26 00:50 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ct/tax/income/rebate/ct_child_tax_rebate.py
> +        total_rebate = min_(count_dependents, child_max) * p.amount
delete above line
```suggestion
        capped_children = min_(count_dependents, p.child_cap)
        total_rebate = capped_children * p.amount
```

2024-06-26 00:50 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/states/ct/tax/income/rebate/ct_child_tax_rebate.yaml
> +- name: Single with $101,000 agi and 2 dependents
and below
```suggestion
- name: Single with $101,000 AGI and 2 dependents
```

2024-06-27 11:42 UTC, merged