San Francisco Working Families Tax Credit
PolicyEngine/policyengine-us pull request #4610
Opened 2024-06-07 10:34 UTC by xianxinzhu

Fixes #4578

2024-06-07 15:05 UTC, PavelMakarchuk requested changes

2024-06-07 15:05 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Add San Francisco working families tax credit.
```suggestion
    - San Francisco working families tax credit.
```

2024-06-07 15:05 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ca/tax/income/credits/wftc/amount.yaml
> +      href: https://www.sf.gov/news/san-francisco-launches-free-tax-preparation-assistance-and-local-tax-credit-program-and
Can we try to find a tax form or legal code for all of the values

2024-06-07 15:05 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/mt/tax/income/deductions/itemized/mt_medical_expense_deduction.py
This should not be in this file right?

2024-06-07 15:05 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ca/tax/income/credits/wftc/ca_wftc.py
> +class ca_wftc(Variable):
```suggestion
class ca_sf_wftc(Variable):
```

2024-06-07 15:05 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ca/tax/income/credits/wftc/ca_wftc.py
move to local folder - all parameters / variables and tests

2024-06-07 15:05 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ca/tax/income/credits/earned_income/ca_is_qualifying_child_for_caleitc.py
change back

2024-06-07 15:05 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ca/tax/income/credits/wftc/amount.yaml
change to reflect san Francisco in description and label

2024-06-08 03:09 UTC, PavelMakarchuk requested changes

2024-06-08 03:09 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/local/ca/sf/wftc/amount.yaml
> +    - title: CHAPTER 12S-SEC. 12S.1. WORKING FAMILIES CREDIT PROGRAM
```suggestion
    # The legal code states the San Francisco Human Services Agency shall publish the 
    # credit amount independently
    - title: CHAPTER 12S-SEC. 12S.1. WORKING FAMILIES CREDIT PROGRAM
```

2024-06-08 03:09 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/local/ca/sf/wftc/ca_sf_wftc.py
can we add this credit to the list of refundable credits in California

2024-06-12 20:00 UTC, PavelMakarchuk requested changes

2024-06-12 20:00 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ca/tax/income/credits/refundable.yaml
> +    - ca_sf_wftc
should this be in 2021? the parameters start in 2022

2024-06-12 20:00 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/local/ca/sf/wftc/ca_sf_wftc.py
> +        caeitc_eligible = tax_unit("ca_eitc_eligible", period)
```suggestion
        ca_eitc_eligible = tax_unit("ca_eitc_eligible", period)
```

2024-06-13 16:57 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ca/tax/income/credits/refundable.yaml
> +    # credit amount independently
```suggestion
    # San Francisco working families tax credit
```

2024-06-13 16:58 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/local/ca/sf/wftc/ca_sf_wftc.py
> +        county_eligible = county == "SAN_FRANCISCO_COUNTY_CA"
```suggestion
        in_sf = county == "SAN_FRANCISCO_COUNTY_CA"
```

2024-06-13 16:58 UTC, PavelMakarchuk approved these changes
good besides minor formatting comments

2024-06-13 17:10 UTC, MaxGhenis requested changes
please add the 2023 tax year reference, both to the parameter and variable

2024-06-14 09:40 UTC, MaxGhenis approved these changes

2024-06-14 09:40 UTC, merged