Adjust the New Mexico refundable credits parameter files
PolicyEngine/policyengine-us pull request #4620
Opened 2024-06-09 19:55 UTC by PavelMakarchuk

Fixes #4619

2024-06-09 21:14 UTC, MaxGhenis approved these changes

2024-06-09 21:15 UTC, MaxGhenis requested changes
Fix test

2024-06-10 16:17 UTC, PavelMakarchuk commented
> should we be just deleting those tests rather than adjusting them?

Generally we should definitely not just remove tests but I think here it is the best way to avoid misleading assumptions about the code structure.  

The tests were checking the structure of zeroing out parameters for the years that the program does not exist. Since this is not practice anymore those tests are obsolete - they would check exactly the same situation for e.g. 2021 and 2022 while there is nothing in the variables and parameters that would lead to the necessity of such tests.

2024-06-10 16:50 UTC, MaxGhenis approved these changes

2024-06-10 16:50 UTC, merged