NJ SNAP minimum allotment
PolicyEngine/policyengine-us pull request #4647
Opened 2024-06-14 07:18 UTC by Kiki-67

Fix #4405

2024-06-14 16:04 UTC, PavelMakarchuk requested changes

2024-06-14 16:04 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/snap.py
> +                    "nj_snap_min_allotment",
I think we should add this to the `snap_min_allotment` with the NJ condition

2024-06-14 16:04 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/nj_snap_min_allotment.py
> +            return 0
Could we change this to a where statement

2024-06-14 16:04 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/nj_snap_min_allotment.py
> +    label = "NJ minimum snap payment"
```suggestion
    label = "New Jersey minimum snap payment"
```

2024-06-14 16:04 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/usda/snap/temporary_local_benefit/nj/amount.yaml
> +description: NJ provides a minimum monthly SNAP benefit at this amount
```suggestion
description: New Jersey provides a minimum monthly SNAP benefit of this amount.
```

2024-06-14 16:04 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/usda/snap/temporary_local_benefit/nj/amount.yaml
Could you add a bool parameter for new jersey applies a separate min allotment - 2023: true - before false

2024-06-14 16:04 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/usda/snap/temporary_local_benefit/nj/amount.yaml
> +  label: NJ SNAP minimum allotment amount
```suggestion
  label: New Jersey SNAP minimum allotment amount
```

2024-06-19 20:20 UTC, PavelMakarchuk requested changes

2024-06-19 20:20 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +
need changelog

2024-06-19 20:20 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/usda/snap/temporary_local_benefit/nj/in_effect.yaml
> +      href: https://www.nj.gov/humanservices/njsnap/emergency/covid19/
```suggestion
    - title: New Jersey Department of Human Services - SNAP
      href: https://www.nj.gov/humanservices/njsnap/emergency/covid19/
```

2024-06-19 20:20 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/usda/snap/temporary_local_benefit/nj/in_effect.yaml
> +      href: https://www.nj.gov/humanservices/njsnap/emergency/covid19/
all tests

2024-06-19 20:20 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/snap_min_allotment.py
> +        is_nj = state_code == StateCode.NJ
```suggestion
        in_nj = state_code == StateCode.NJ
```

2024-06-19 20:20 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/snap_min_allotment.py
> +        nj_supplement = spm_unit("nj_snap_min_allotment", period)
```suggestion
        nj_min_allotment = spm_unit("nj_snap_min_allotment", period)
```

2024-06-19 20:20 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/nj_snap_min_allotment.py
> +        base_benefit = spm_unit("snap_reported", period)
```suggestion
        snap_amount = spm_unit("snap_reported", period)
```

2024-06-19 20:20 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/snap_min_allotment.py
> +        state_code = spm_unit.household("state_code", period)
need to use the in effect parameter

2024-06-19 20:20 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/snap_min_allotment.py
> +        base_benefit = eligible * min_allotment.rate * relevant_max_allotment
```suggestion
        base_benefit_amount = eligible * min_allotment.rate * relevant_max_allotment
```

2024-06-19 20:20 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/nj_snap_min_allotment.py
> +    documentation = "NJ minimum snap payment"
```suggestion
```

2024-06-20 14:04 UTC, PavelMakarchuk requested changes

2024-06-24 11:39 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/snap_min_allotment.py
> +        )
```suggestion
        if snap.temporary_local_benefit.nj.in_effect
             state_code = spm_unit.household("state_code_str", period)
             in_nj = state_code == "NJ"
             nj_min_allotment = snap.temporary_local_benefit.nj.amount
             base_benefit_amount = where(in_nj, nj_min_allotment, base_benefit_amount)
        return base_benefit_amount
```

2024-06-28 12:37 UTC, PavelMakarchuk requested changes

2024-06-28 12:37 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/usda/snap/temporary_local_benefit/nj/amount.yaml
can we move this file to parameters/states/nj/snap/....

2024-07-03 19:38 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/usda/snap/snap_min_allotment.py
> -        p_dc = parameters(period).gov.states.dc.dhs.snap.min_allotment
we want to keep the DC changes and add NJ on top of it

2024-07-05 12:13 UTC, PavelMakarchuk approved these changes

2024-07-05 12:51 UTC, MaxGhenis requested changes

2024-07-05 12:51 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/usda/snap/snap_min_allotment.yaml
> +  period: 2024
Can we keep the period as a month? For monthly variables it better aligns with our minimalist approach. Please change others in this file too.

2024-07-05 17:36 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/usda/snap/snap_min_allotment.yaml
> +  period: 2024
>Please change others in this file too.

2024-07-11 14:21 UTC, MaxGhenis commented
Pull again - too many changes

2024-07-12 03:01 UTC, MaxGhenis approved these changes

2024-07-12 16:05 UTC, merged