Hawaii Tax bill H.B. 2404 H.D. 1, S.D.1, C.D.1 into law, becoming Act 46 SLH 2024
PolicyEngine/policyengine-us pull request #4682
Opened 2024-06-23 23:52 UTC by PavelMakarchuk

Fixes #4681

2024-06-23 23:56 UTC, MaxGhenis requested changes
any legal code for the existing rules? if not could you add 2023 forms as reference?

2024-06-23 23:56 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/hi/tax/income/rates/surviving_spouse.yaml
> +description: Hawaii taxes widow(er) filers at these rates by taxable income.
```suggestion
description: Hawaii taxes surviving spouse filers at these rates by taxable income.
```

2024-06-23 23:56 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/hi/tax/income/rates/surviving_spouse.yaml
> +  label: Hawaii widow(er) income tax rate
```suggestion
  label: Hawaii surviving spouse income tax rate
```

2024-06-24 00:23 UTC, PavelMakarchuk commented
> any legal code for the existing rules? if not could you add 2023 forms as reference?

I added the 2023 form for the SD but for the tax rate, the link to the tax table is most recent document

2024-06-24 01:59 UTC, MaxGhenis commented
could you confirm standard deduction and rates aren't in the legal code? if so please leave a comment

2024-06-24 11:33 UTC, PavelMakarchuk commented
> could you confirm standard deduction and rates aren't in the legal code? if so please leave a comment

Found the legal code

2024-06-24 12:39 UTC, MaxGhenis requested changes
it looks like the legal code doesn't yet reflect this bill's passage. please leave a comment in each reference noting this.

2024-06-24 12:39 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/hi/tax/income/deductions/standard/amount.yaml
> +    href: https://data.capitol.hawaii.gov/sessions/session2024/bills/HB2404_CD1_.HTM
wrong link?

2024-06-24 12:53 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/hi/tax/income/deductions/standard/amount.yaml
> +    href: https://data.capitol.hawaii.gov/sessions/session2024/bills/HB2404_CD1_.HTM
yep, changed

2024-06-24 20:28 UTC, MaxGhenis approved these changes

2024-06-24 22:52 UTC, MaxGhenis approved these changes

2024-06-25 01:14 UTC, merged