EITC Policy Parameters
PolicyEngine/policyengine-us pull request #4697
Opened 2024-06-27 04:53 UTC by yuantian0204

fixes #4675

2024-06-27 12:40 UTC, MaxGhenis commented
Skip the Illinois ones which are covered in #4685

@PavelMakarchuk in the future let's make issues more specific to states to avoid doubling up work

2024-06-28 12:34 UTC, PavelMakarchuk requested changes

2024-06-28 12:34 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/il/tax/income/credits/eitc/match.yaml
run a git pull upstream master and remove these changes

2024-06-28 12:34 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ok/tax/income/credits/refundable.yaml
> +    href: https://oklahoma.gov/content/dam/ok/en/tax/documents/forms/individuals/current/511-EIC.pdf
add pdf page

2024-06-28 12:34 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/il/tax/income/credits/eitc/match.yaml
need to add a changelog_entry.yaml file

2024-07-01 19:17 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Oklahoma EITC Refundability
```suggestion
    - Oklahoma EITC refundability.
```

2024-07-01 19:20 UTC, PavelMakarchuk approved these changes

2024-07-01 19:29 UTC, MaxGhenis approved these changes

2024-07-01 20:56 UTC, merged