Create a is_wic_eligible file
PolicyEngine/policyengine-us pull request #4753
Opened 2024-07-19 00:04 UTC by hua7450

Fixes #4744

2024-07-19 12:55 UTC, PavelMakarchuk approved these changes

2024-07-19 20:15 UTC, MaxGhenis requested changes

2024-07-19 20:15 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/usda/wic/wic.yaml
>  - name: Income-eligible and categorically eligible but not at nutritional risk.
update test names

2024-07-20 17:05 UTC, MaxGhenis requested changes
@PavelMakarchuk  is the standard to leave off the is_ and just do wic_eligible?

2024-07-20 17:05 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/usda/wic/wic.yaml
> +- name: Households that are in breastfeeding category are elgible, check uprating.
```suggestion
- name: Eligible breastfeeding individuals. Verifies uprating.
```

2024-07-21 05:29 UTC, PavelMakarchuk commented
> @PavelMakarchuk is the standard to leave off the is_ and just do wic_eligible?

We have used both in the past, for benefit programs we have used `is_x_eligible` in the past but I think the following structure could be good to adapt:
`is_x_eligible` - person level eligibility 
`x_eligible` - TaxUnit/SpmUnit/Household level eligibility

2024-07-23 03:16 UTC, MaxGhenis approved these changes
Could you elaborate on the rationale for that naming convention in https://github.com/PolicyEngine/policyengine-us/issues/4771?

Merging and we can adopt a standard in the future.

2024-07-23 03:16 UTC, merged