Tax Counseling for the Elderly eligibility
PolicyEngine/policyengine-us pull request #4770
Opened 2024-07-22 20:02 UTC by vrathi101

Fixes #4751

2024-07-22 20:09 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/tce/is_tce_eligible.py
would we want to incorporate this into the head start PR?

2024-07-22 20:11 UTC, vrathi101 commented on policyengine_us/variables/gov/irs/tce/is_tce_eligible.py
> would we want to incorporate this into the head start PR?

i don't think so(?), not exactly related

2024-07-23 15:34 UTC, PavelMakarchuk commented
@MaxGhenis how would we want to incorporate this into the net income tree?

2024-07-23 16:39 UTC, MaxGhenis commented
Not until we attach values

2024-07-23 20:06 UTC, vrathi101 commented
@PavelMakarchuk should we leave it as this then?

2024-07-23 23:06 UTC, PavelMakarchuk approved these changes

2024-07-23 23:08 UTC, PavelMakarchuk requested changes
Could you take a look through [this](https://www.irs.gov/pub/irs-pdf/p1101.pdf) manual, there might be some income limits

2024-07-23 23:24 UTC, vrathi101 commented
> Could you take a look through [this](https://www.irs.gov/pub/irs-pdf/p1101.pdf) manual, there might be some income limits

none mentioned, most of the manual talks about how to operate the program (similar to head start)

2024-07-24 00:03 UTC, MaxGhenis approved these changes

2024-07-24 00:03 UTC, merged