Cap Pell Grant at the cost of attendance
PolicyEngine/policyengine-us pull request #4785
Opened 2024-07-24 17:58 UTC by CalebPena

fixes #4784

2024-07-24 19:02 UTC, PavelMakarchuk approved these changes

2024-07-24 19:02 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    fixed: Cap the Pell Grant amount at the cost of attendence
```suggestion
    fixed: 
       - Cap the Pell Grant amount at the cost of attendance.
```

2024-07-24 19:13 UTC, MaxGhenis requested changes

2024-07-24 19:13 UTC, MaxGhenis commented on changelog_entry.yaml
> +       - Cap the Pell Grant amount at the cost of attendance.
```suggestion
      - Cap the Pell Grant amount at the cost of attendance.
```

2024-07-24 19:13 UTC, MaxGhenis commented on policyengine_us/variables/gov/ed/pell_grant/pell_grant.py
> +            [0, min_(coa, p.amount.max), amount],
could amount ever exceed coa?

capping as the very final step could be safer if so

2024-07-24 20:07 UTC, MaxGhenis approved these changes

2024-07-24 20:10 UTC, merged

2024-07-25 17:12 UTC, CalebPena commented
@MaxGhenis when will these changes be reflected in the household API?

2024-07-25 18:25 UTC, PavelMakarchuk commented
> @MaxGhenis when will these changes be reflected in the household API?

The changes should already be reflected in the API

2024-07-25 18:44 UTC, CalebPena commented
I am getting the expected result on app API, but I am still getting the old result on the household API.

2024-07-26 03:19 UTC, MaxGhenis commented
Should be up now