Indiana additional exemption amount for adopted children
PolicyEngine/policyengine-us pull request #4791
Opened 2024-07-25 14:42 UTC by vrathi101

Fixes #4789

2024-07-25 17:32 UTC, PavelMakarchuk requested changes

2024-07-25 17:32 UTC, PavelMakarchuk commented on policyengine_us/variables/household/demographic/person/is_adopted.py
Lets rather use `adopted_this_year` here

2024-07-25 17:32 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/exemptions/in_adoption_exemptions.py
> +class in_adoption_exemptions(Variable):
```suggestion
class in_adoption_exemption(Variable):
```

2024-07-25 17:32 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/exemptions/in_adoption_exemptions.py
> +    label = "Indiana adoption credit"
```suggestion
    label = "Indiana adoption exemption"
```

2024-07-25 17:32 UTC, PavelMakarchuk commented on changelog_entry.yaml
There also is a section which I interpret as "if the child is born this year they will get an increased $3,000 exemption amount" - did I misinterpret it?

2024-07-25 17:54 UTC, vrathi101 commented on changelog_entry.yaml
could u check the comment in the issue #4791, I'm not quite sure either but I assume it means if u weren't eligible the year before but you now are eligible ... i just don't understand the 1500 -> 3000 change, how would this work if the base amount of an additional exemption is not 1500? (like this adoption exemption)

2024-07-25 17:59 UTC, vrathi101 commented on policyengine_us/variables/household/demographic/person/is_adopted.py
def formula(person, period, parameters):
        is_adopted = person(“adopted_this_year”, period)
        node = period.last_year
        while node:
            is_adopted = is_adopted | person(“adopted_this_year”, node)
            node = node.last_year
        return is_adopted
        
 I originally used this logic for the formula but changed it back because I don't know how to set a stop year, it was throwing an error for a year of '999' not existing

2024-07-25 18:21 UTC, PavelMakarchuk commented on policyengine_us/variables/household/demographic/person/is_adopted.py
lets just the `adopted_this_year` in the main exemption and remove `is_adopted` for now - most adoption related programs are one time amounts for the year of adoption

2024-07-25 18:38 UTC, vrathi101 commented on policyengine_us/variables/household/demographic/person/is_adopted.py
going back to the issue convo then, wouldn't we need to check:
if adopted_this_year, then 3000
elif is_adopted (not adopted this year but adopted an earlier year), then 1500?

2024-07-25 19:42 UTC, vrathi101 commented
since we have an in_additional_exemptions, and adopted_this_year provides an additinal 1500 dollar exemption (for a total of 3000), should I change the amount.yaml to 1500 so it doesn't overcount 1500 (because if amount.yaml for adoption exemption was 3000 then the total exemption would be 3000 + 1500)

2024-07-29 14:59 UTC, PavelMakarchuk commented
> since we have an in_additional_exemptions, and adopted_this_year provides an additinal 1500 dollar exemption (for a total of 3000), should I change the amount.yaml to 1500 so it doesn't overcount 1500 (because if amount.yaml for adoption exemption was 3000 then the total exemption would be 3000 + 1500)

What does the legal code state? Is it an additional $1,500 or is it a separate amount of $3,000? Lets make the adjustment based on that

2024-08-01 14:19 UTC, PavelMakarchuk requested changes

2024-08-01 14:19 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/exemptions/in_adoption_exemption.py
> +        )
```suggestion
        adopted_this_year =  person("adopted_this_year", period)
        is_qualifying_adopted_dependent_child = 
            is_qualifying_dependent_child & adopted_this_year
        return tax_unit.sum(
            is_qualifying_adopted_dependent_child *  p.amount
        )
```

2024-08-01 14:19 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/exemptions/adoption/amount.yaml
> +  unit: /1
```suggestion
  unit: currency-USD
```

2024-08-01 14:19 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/exemptions/in_adoption_exemption.py
but then we need to make sure that we dont give a qualifying dependent child 4,500 as in 3,000 for the new exemption and 1,500 for the dependent exemption

2024-08-01 14:38 UTC, vrathi101 commented on policyengine_us/variables/gov/states/in/tax/income/exemptions/in_adoption_exemption.py
the legal code says 3000 exemption amount so I left the parameter file as is, I capped the exemption amount in the variable so we don't overcount

2024-08-02 05:05 UTC, PavelMakarchuk requested changes

2024-08-02 05:05 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/exemptions/adoption/amount.yaml
> +description: Indiana provides this additional exemption amount for eligible adopted dependents.
```suggestion
description: Indiana provides an additional exemption amount for eligible adopted dependents of this amount.
```

2024-08-02 05:05 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/exemptions/adoption/amount.yaml
> +  label: Indiana exemptions additional amount for eligible adopted dependents
```suggestion
  label: Indiana adopted children exemption additional amount
```

2024-08-02 05:05 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/exemptions/adoption/amount.yaml
> +      href: https://www.in.gov/dor/tax-forms/2023-individual-income-tax-forms/
could we add one more tax form reference to show that the value was always 3,000

2024-08-02 05:05 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/exemptions/in_adoption_exemption.py
But we want to make sure that a child who is receiving `in_adoption_exemption` for the year does not also receive `in_additional_exemptions`

2024-08-02 13:13 UTC, vrathi101 commented on policyengine_us/variables/gov/states/in/tax/income/exemptions/in_adoption_exemption.py
> But we want to make sure that a child who is receiving `in_adoption_exemption` for the year does not also receive `in_additional_exemptions`

right that's what capping the variable does no? do we have a way to just exclude a diff variable altogether? because both the additional exemption and adoption exemption have the same eligibility criteria

2024-08-02 15:38 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/exemptions/in_adoption_exemption.py
I see, you are right, this is the way to go!

2024-08-02 15:39 UTC, PavelMakarchuk approved these changes

2024-08-02 17:55 UTC, MaxGhenis approved these changes

2024-08-02 17:55 UTC, merged