TCE eligibility
PolicyEngine/policyengine-us pull request #4826
Opened 2024-07-31 19:32 UTC by shuyu7zhan

Fixes #4823

2024-08-01 13:43 UTC, PavelMakarchuk requested changes

2024-08-01 13:43 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/tce/eligibility/age_limit.yaml
> +  unit: 1/
```suggestion
  unit: year
```

2024-08-01 13:43 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/tce/eligibility/age_limit.yaml
> +  label: TCE Program Age Limit
```suggestion
  label: TCE program age limit
```

2024-08-01 13:43 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/tce/tce_eligible.py
> +        is_eligible_age = person("age", period) >= p.age_limit
```suggestion
        age = person("age", period
        return age >= p.age_limit
```

2024-08-01 13:43 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/tce/tce_eligible.py
> +class tce_eligible(Variable):
```suggestion
class is_tce_eligible(Variable):
```

2024-08-01 13:43 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/tce/tce_eligible.py
> +    label = "Eligible for the TCE program"
```suggestion
    label = "Eligible Person for the TCE program"
```

2024-08-01 13:43 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - IRS TCE Program Eligibility.
```suggestion
    - IRS TCE Program eligibility.
```

2024-08-01 14:23 UTC, vrathi101 commented
https://github.com/PolicyEngine/policyengine-us/issues/4751

2024-08-02 00:13 UTC, PavelMakarchuk commented
Duplicate of #4751

2024-08-02 00:13 UTC, closed without merging