Massachusetts Emergency Aid to the Elderly, Disabled and Children (EAEDC)
PolicyEngine/policyengine-us pull request #4870
Opened 2024-08-14 05:26 UTC by hua7450

# Fixes1712

2024-08-15 13:59 UTC, PavelMakarchuk requested changes

2024-08-15 13:59 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/age_threshold.yaml
> +  label: Massachusetts EAEDA elderly age
```suggestion
  label: Massachusetts EAEDA elderly age threshold
```

2024-08-15 13:59 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/age_threshold.yaml
> +description: Massachusetts requires household have at least one elderly over is age for the Emergency Aid to the Elderly, Disabled and Children program.
```suggestion
description: Massachusetts limits the Emergency Aid to the Elderly, Disabled and Children program to households with at least one person above this age threshold.
```

2024-08-15 14:01 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/income/ma_eaedc_net_income.py
> +        dependent_care_expense = add(spm_unit, period,["child_support_expense"])
care_expenses

2024-08-15 14:01 UTC, hua7450 commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/income/ma_eaedc_net_income.py
> +        dependent_care_expense = add(spm_unit, period,["child_support_expense"])
Do we  dependent_care_expense in system? (care_expenses)

2024-08-19 13:58 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/income/ma_eaedc_income_limit.py
> +
create a class:
```
class ma_eadc_living_arrange(Variable):
    value_type = Enum
    entity = SPMUnit
    possible_values = MassachusettsEAEDCLivingArrangement
    default_value = MassachusettsEAEDCLivingArrangement.NONE
    definition_period = YEAR
    label = 
    defined_for = StateCode.MA

2024-08-19 13:58 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/income/ma_eaedc_income_limit.py
> +class ma_eaedc_income_limit(Variable):
make this a separate file

2024-08-22 13:43 UTC, hua7450 commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/income/ma_eaedc_disabled_earned_income.py
> +    entity = SPMUnit
person level

2024-08-22 13:53 UTC, hua7450 commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/income/ma_eaedc_earned_income.py
> +    entity = SPMUnit
person

2024-08-29 13:56 UTC, PavelMakarchuk requested changes

2024-08-29 13:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/income/ma_eaedc_disabled_earned_income.py
> +    label = "Massachusetts EAEDC disabled earned income"
```suggestion
    label = "Massachusetts EAEDC earned income of a disabled person"
```

2024-08-29 13:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/income/ma_eaedc_total_earned_income.py
> +class ma_eaedc_total_earned_income(Variable):
```suggestion
class ma_eaedc_no_disabled_earned_income(Variable):
```

2024-08-29 13:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/income/ma_eaedc_earned_income.py
> +class ma_eaedc_earned_income(Variable):
```suggestion
class ma_eaedc_total_earned_income(Variable):
```

2024-08-29 13:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/income/ma_eaedc_total_earned_income.py
> +    adds = ["ma_eaedc_earned_income"]
make a formula and lets do the same as in disabled income just with `~disabled & ~dependent`

2024-08-29 13:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/ma_eaedc_dependent_care_deduction.py
> +        meets_age_limit = age < 18
lets parametrize this

2024-08-29 13:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_dependent_care_deduction_eligible.py
> +    unit = USD
```suggestion
```

2024-08-29 13:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_disabled_income_eligible.py
> +    unit = USD
```suggestion
```

2024-08-29 13:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_assets_eligible.py
> +    unit = USD
```suggestion
```

2024-08-29 13:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_age_eligible.py
> +    unit = USD
```suggestion
```

2024-08-29 13:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/income/ma_eaedc_disabled_earned_income.py
> +        disabled = person("is_disabled", period)
add a is_dependent condition

2025-01-13 02:35 UTC, MaxGhenis commented
Can we complete this given its importance to MyFriendBen, or should we start with a new PR?

2025-01-16 14:52 UTC, PavelMakarchuk requested changes

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/standard_assistance/increment.yaml
> +  unit: currency-USD
```suggestion
  unit: currency-USD
  period: year
```

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/standard_assistance/increment.yaml
> +description: For additional household members, each will increase standard_assistance by this amount.
```suggestion
description: Massachusetts increases the standard assistance for each additional household member by this amount, based on the living arrangement, under the Emergency Aid to the Elderly Disabled and Children program.
```

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/standard_assistance/increment.yaml
> +  unit: currency-USD
period in yaml files

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/standard_assistance/base.yaml
> +  unit: /1
```suggestion
  unit: currency-USD
```

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/standard_assistance/base.yaml
> +description: Massachusetts assign these values as the standard_assistance for households size of 1.
```suggestion
description: Massachusetts provides the following standard assistance amount, based on living arrangements under the Emergency Aid to the Elderly Disabled and Children program.
```

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/standard_assistance/base.yaml
> +  unit: /1
if monthly, add period: month

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/income/ma_eaedc_standard_assistance.py
> +        p1 = p.base[living_arrangement]
if we change the parameter to monthly, then use `MONTHS_IN_YEAR`

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/assets/limit.yaml
> +  type: single_amount
```suggestion
```

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/assets/limit.yaml
> +  amount_unit: currency-USD
```suggestion
  unit: currency-USD
  period: year
```

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/assets/limit.yaml
> +  threshold_period: year
```suggestion
```

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/deductions/dependent_care/maximum_expense.yaml
> +  # the legal code said this amount per child
```suggestion
  # Legal code provides amount per child
```

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/deductions/income_disregards/amount.yaml
> +  period: year
```suggestion
  period: month
```

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/income/disabled_cap.yaml
> +  period: year
```suggestion
  period: month
```

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/deductions/work_related_expense.yaml
> +  period: year
```suggestion
  period: month
```

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_eligible.py
> +    unit = USD
```suggestion
```

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_eligible.py
> +    label = "Eligible for Massachusetts EAEDC"
```suggestion
    label = "Eligible for the Massachusetts EAEDC"
```

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_financially_eligible.py
> +    unit = USD
```suggestion
```

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/ma_eaedc.py
could you add this to the `household_state_benefits.yaml`

2025-01-16 14:52 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/assets/list.yaml
lets rename this to `sources.yaml`

2025-01-19 15:29 UTC, PavelMakarchuk requested changes

2025-01-19 15:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/assets/limit.yaml
> +  type: single_amount
Still need to adjust

2025-01-19 15:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/deductions/dependent_care/age_threshold.yaml
> +  unit: age
```suggestion
  unit: year
```

2025-01-19 15:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/deductions/dependent_care/maximum_expense.yaml
> +description: Massachusetts provides this deduction amount in dependent care expense for Emergency Aid to the Elderly, Disabled and Children program.
```suggestion
description: Massachusetts provides this deduction amount of dependent care expenses for Emergency Aid to the Elderly, Disabled and Children program, based on the child age.
```

2025-01-19 15:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/deductions/income_disregards/months.yaml
> +  period: month
```suggestion
  period: year
```

2025-01-19 15:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/income/disabled_cap.yaml
> +description: Massachusetts limits disabled peoople's income to this amount for the Emergency Aid to the Elderly, Disabled and Children program.
```suggestion
description: Massachusetts limits the Emergency Aid to the Elderly, Disabled and Children program to disabled filers with income below this threshold. 
```

2025-01-19 15:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/income/disabled_cap.yaml
lets call this `disabled_limit.yaml`

2025-01-19 15:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/standard_assistance/base.yaml
> +  label: Massachusetts EAEDC standard_assistance base
```suggestion
  label: Massachusetts EAEDC standard assistance base 
```

2025-01-19 15:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/standard_assistance/increment.yaml
> +  2022-01-01: 0 #or 72.8
What does the OR stand for?

2025-01-19 15:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/standard_assistance/increment.yaml
> +  label: Massachusetts EAEDC standard_assistance increment
```suggestion
  label: Massachusetts EAEDC standard assistance additional 
```

2025-01-19 15:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/standard_assistance/base.yaml
lets make an `amount` folder with the files:
`base.yaml`
`additional.yaml`

2025-01-19 15:29 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_assets_eligible.py
> +        countable_assets = add(spm_unit, period, ["ma_eaedc_assets"])
```suggestion
        countable_assets = spm_unit("ma_eaedc_assets", period)
```

2025-01-19 15:29 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_assets_eligible.py
> +        countable_assets = add(spm_unit, period, ["ma_eaedc_assets"])
we can just do this if `ma_eaedc_assets` is spm unit level

2025-01-19 15:29 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_assets_eligible.py
> +class ma_eaedc_assets_eligible(Variable):
```suggestion
class ma_eaedc_asset_limit_eligible(Variable):
```

2025-01-19 15:29 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_disabled_income_eligible.py
Do we check this for the entire unit or just for the Disabled filers?

2025-01-19 15:29 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_disabled_income_eligible.py
If we want to do an spm unit level check then we need to add a `spm_unit.any` to the return 

Or change this to be a person level variable

2025-01-19 15:29 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_disabled_income_eligible.py
This is breaking the git test

2025-01-23 14:45 UTC, PavelMakarchuk requested changes

2025-01-23 14:45 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/income/me_eaedc_no_disabled_earned_income.py
> +class ma_eaedc_no_disabled_earned_income(Variable):
```suggestion
class ma_eaedc_non_disabled_earned_income(Variable):
```

2025-01-23 14:45 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_disabled_income_eligible.py
> +        )
```suggestion
        disabled_income = add(spm_unit, period, ["ma_eaedc_disabled_earned_income"])
        return disabled_income < p.disabled_limit
```

2025-01-23 14:45 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_disabled_income_eligible.py
> +        person = spm_unit.members
```suggestion
```

2025-02-03 13:35 UTC, PavelMakarchuk requested changes

2025-02-03 13:35 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/age_threshold.yaml
> +description: Massachusetts limits the Emergency Aid to the Elderly, Disabled and Children program to households with at least one person above this age threshold.
```suggestion
description: Massachusetts limits the Emergency Aid to the Elderly, Disabled and Children program to households with at least one person at or above this age threshold. 
```

right?

2025-02-03 13:35 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/assets/limit.yaml
> +description: Massachusetts limits the assets to this amount under the Emergency Aid to the Elderly, Disabled and Children program, for living arrangements E.
```suggestion
description: Massachusetts limits the assets to this amount under the Emergency Aid to the Elderly, Disabled and Children program, for individuals in living arrangement E.
```

2025-02-03 13:35 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/deductions/dependent_care/age_threshold.yaml
> +description: Massachusetts limits the Emergency Aid to the Elderly, Disabled and Children program to households with at least one person above this age threshold.
This defines a dependent right? 

Can we re-frame this dependent age threshold and add a parameter for the 19 year olds for are stundents

2025-02-03 13:35 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/deductions/dependent_care/maximum_expense.yaml
> +description: Massachusetts provides this deduction amount of dependent care expenses for Emergency Aid to the Elderly, Disabled and Children program, based on the child age.
```suggestion
description: Massachusetts provides this dependent care expense deduction amount under the Emergency Aid to the Elderly, Disabled and Children program, based on the child age.
```

2025-02-03 13:35 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/deductions/dependent_care/maximum_expense.yaml
we also should also add a partial deduction amount based on weekly hours worked:
![image](https://github.com/user-attachments/assets/333aa7bf-a11d-4c43-97b4-09f65cae64f4)

Two parameters one for younger and one for older

2025-02-03 15:06 UTC, PavelMakarchuk requested changes

2025-02-03 15:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/deductions/dependent_care/age_threshold.yaml
> +description: Massachusetts limits the Emergency Aid to the Elderly, Disabled and Children program to households with at least one person above this age threshold.
```suggestion
description: Massachusetts defines a dependent as a person under this age threshold under the Emergency Aid to the Elderly, Disabled and Children program. 
```

2025-02-03 15:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/deductions/dependent_care/age_threshold.yaml
> +  label: Massachusetts EAEDA elderly age threshold
```suggestion
  label: Massachusetts EAEDA elderly dependent age threshold
```

2025-02-03 20:31 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/age_threshold.yaml
> +description: Massachusetts limits the Emergency Aid to the Elderly, Disabled and Children program to households with at least one person above this age threshold.
`this age or older` let's please use this phrasing for age-related parameters

2025-02-03 20:31 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/deductions/dependent_care/age_threshold.yaml
> +  label: Massachusetts EAEDA elderly age threshold
Not EAEDC?

2025-02-13 14:27 UTC, PavelMakarchuk requested changes
Last formatting comments

2025-02-13 14:27 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_disabled_income_eligible.py
> +    label = "Disabled person's income eligible for the Massachusetts EAEDC"
```suggestion
    label = "Disability income eligibility for the Massachusetts EAEDC"
```

2025-02-13 14:27 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_financially_eligible.py
> +class ma_eaedc_financially_eligible(Variable):
```suggestion
class ma_eaedc_income_eligible(Variable):
```

2025-02-13 14:27 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/eligibility/ma_eaedc_financially_eligible.py
> +    label = "Financially eligible for the Massachusetts EAEDC "
```suggestion
    label = "Eligible for the Massachusetts EAEDC based on income"
```

2025-02-13 14:27 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/income/ma_eaedc_disabled_earned_income.py
> +    label = "Massachusetts EAEDC earned income of a disabled person"
```suggestion
    label = "Massachusetts EAEDC earned income of each disabled person"
```

2025-02-13 14:27 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/income/me_eaedc_non_disabled_earned_income.py
> +            * ~dependent
is this specifically for non-dependents? Or any non-disabled person

2025-02-13 14:27 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/ma_eaedc.py
> +    adds = ["ma_eaedc_standard_assistance"]
```suggestion
    # Program value can not be less than 0
    # due to the eligibility requirements 
    adds = ["ma_eaedc_standard_assistance"]
```

Right?

2025-02-13 14:27 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ma/dta/tcap/eaedc/ma_eaedc_assets.py
> +class ma_eaedc_assets(Variable):
```suggestion
class ma_eaedc_countable_assets(Variable):
```

2025-03-03 17:43 UTC, MaxGhenis commented
Per our chat just now, please align the disabled earned income test logic closer to the regs. We also need to populate the household type enum though could be in a separate PR.

2025-03-06 17:56 UTC, hua7450 commented
Here is what I did in the last commit:
 1. Restructured eligibility logic - created ma_eaedc_disabled_dependent_criteria_met variable
 2. Renamed ma_eaedc_disabled_eligible to ma_eaedc_head_is_disabled for clarity
 3. Refactored income calculation by extracting logic into separate ma_eaedc_earned_net_income variable
 4. Fixed vectorization in test files to return arrays instead of scalars
 5. Added new test cases to cover the updated functionality

2025-03-11 21:03 UTC, MaxGhenis requested changes
please apply this feedback throughout

2025-03-11 21:03 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/deductions/dependent_care/maximum_deductions/older.yaml
> +description: Massachusetts provides this dependent care expense deduction amount under the Emergency Aid to the Elderly, Disabled and Children program, based on the child age.
```suggestion
description: Massachusetts provides this dependent care expense deduction amount under the Emergency Aid to the Elderly, Disabled and Children program, based on the child's age.
```

2025-03-11 21:03 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/deductions/work_related_expense.yaml
> +description: Massachusetts provides this deduction amount in work-related expense for Emergency Aid to the Elderly, Disabled and Children program.
```suggestion
description: Massachusetts deducts up to this amount in work-related expenses for the Emergency Aid to the Elderly, Disabled and Children program.
```

2025-03-11 21:44 UTC, hua7450 commented on policyengine_us/parameters/gov/states/ma/dta/tcap/eaedc/README.md
Yes https://www.law.cornell.edu/regulations/massachusetts/106-CMR-701-050

2025-03-20 17:48 UTC, MaxGhenis commented
Looks like we're adding the dependent care deduction already but just adding some info from Jenn Superka:

> I’m following up on the question about whether EAEDC applicants can deduct child care expenses in determining eligibility. Pavel, you had pointed out that the regs were recently updated, which I found (EAEDC was under 106 CMR 320, now it’s combined with TAFDC under 704). According to [106 CMR 704.500](https://www.mass.gov/doc/106-cmr-704-transitional-cash-assistance-program-financial-eligibility/download): Calculation of Grant Amount (and the [DTA website](https://www.mass.gov/info-details/how-to-calculate-eaedc-benefits)), when calculating eligibility for EAEDC, child care expenses are an allowable deduction.
> As you noted, there is a provision in 106 CMR 704.275(B) that states that an EAEDC applicant who meets the provisions of 106 CMR 704.285(C) is not eligible for the dependent care deduction. But there is no subsection C in 704.285.
> I reached out to one of our contacts in MA to ask about this missing provision, but it looks to me that the child care deduction is allowed.

2025-03-27 17:31 UTC, PavelMakarchuk approved these changes

2025-03-28 14:49 UTC, MaxGhenis reviewed
@PavelMakarchuk and I just discussed making this monthly

2025-04-01 13:44 UTC, merged