Add NC Tanf
PolicyEngine/policyengine-us pull request #4954
Opened 2024-08-27 00:32 UTC by myang1010

Fixes [#891](https://github.com/PolicyEngine/policyengine-us/issues/891)

2024-08-27 01:03 UTC, PavelMakarchuk requested changes
Thank you for filing! mostly formatting suggestions at this point

2024-08-27 01:03 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nc/ncdhhs/tanf/need_standard/main.yaml
> +description: North Carolina TANF need standard by number of household members.
```suggestion
description: North Carolina account for the following TANF need standard, dependent on the number of household members.
```

2024-08-27 01:03 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nc/ncdhhs/tanf/need_standard/monthly_allowed_difference.yaml
> +description: North Carolina TANF need standard monthly allowed income and need difference.
```suggestion
description: North Carolina limits the TANF program to filers with income excess over the need standard under the following amount.
```

2024-08-27 01:03 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nc/ncdhhs/tanf/need_standard/monthly_allowed_difference.yaml
> +description: North Carolina TANF need standard monthly allowed income and need difference.
right?

2024-08-27 01:03 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/nc/ncdhhs/tanf/nc_tanf_countable_earned_income_need.yaml
could we add some more test for edge cases? E.g. en enrolled person etc.

2024-08-27 01:03 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/nc/ncdhhs/tanf/nc_tanf_countable_earned_income_need.yaml
same for other unit tests

2024-08-27 01:03 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nc/ncdhhs/tanf/nc_tanf.py
> +        payment_percentage = 0.5
we should make this a policy parameter as well

2024-08-27 06:22 UTC, myang1010 reviewed
Thanks Pavel for the review. I've incorporated the suggestions and corrected one logic error. Also, left two comments below and would like to know your thoughts.

2024-08-27 20:47 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nc/ncdhhs/tanf/nc_tanf_child_eligible.py
> +        is_18 = person("age", period) == 18
We might want to create a general parameter for the 18 years in the `is_person_demographic_tanf_eligible` file but it is ok to replicate here

2024-08-27 20:49 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nc/ncdhhs/tanf/nc_tanf_income_eligible.py
> +        ) / MONTHS_IN_YEAR / household_size < monthly_allowed_difference
I think the easiest way is to separate each of the calculation steps:
monthly_reduced_need_standard = reduced_need_standard / MONTHS_IN_YEAR
....

2024-08-27 20:50 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nc/ncdhhs/tanf/nc_demographic_tanf_eligible.py
> +    adds = ["nc_tanf_child_eligible"]
remove the adds here

2024-08-28 09:13 UTC, PavelMakarchuk requested changes

2024-08-28 09:13 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nc/ncdhhs/tanf/income/earned.yaml
> +# need to confirm
remove if confirmed

2024-08-28 09:13 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nc/ncdhhs/tanf/income/earned.yaml
> +# need to confirm
same below

2024-08-28 09:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nc/ncdhhs/tanf/income/nc_tanf_countable_earned_income_need.py
> +            max_(gross_earnings - annual_flat_exclusion, 0),
```suggestion
        # For new enrollees, Colorado applies only a flat exclusion.
        flat_reduced_earnings =  max_(gross_earnings - annual_flat_exclusion, 0)
# For enrolled participants, Colorado applies only a percent exclusion.
        percent_reduced_earnings =   gross_earnings * (1 - p.percent)
        return where(
            tanf_enrolled,
            percent_reduced_earnings,
            flat_reduced_earnings)
```

2024-08-28 09:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nc/ncdhhs/tanf/nc_tanf_income_eligible.py
> +            >= monthly_allowed_difference * MONTHS_IN_YEAR
```suggestion
        need_standard_fraction = reduced_need_standard / household_size
        difference_threshold = monthly_allowed_difference * MONTHS_IN_YEAR
        return need_standard_fraction >= difference_threshold
```

2024-08-28 09:13 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nc/ncdhhs/tanf/nc_tanf_need_standard.py
> +        capped_people = min_(people, 14).astype(int)
we should parameterize the 14 as well here

2024-08-28 11:40 UTC, MaxGhenis commented
Could you remove the parameter placeholders? We limit parameters to values in the law. Instead, you can create variables without formulas, e.g. for the earned income exclusion.

2024-08-29 15:29 UTC, PavelMakarchuk requested changes

2024-08-29 15:29 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nc/ncdhhs/tanf/nc_tanf_need_standard.py
> +        # Calculate additional people beyond the maximum in tables.
```suggestion
        household_size = spm_unit("spm_unit_size", period)
        # Get household size list
        household_size_list = list(map(int, (p.main)))
        # Get the maximun number of people defined in the tables.
        max_standard_household_size = max(household_size_list)
        # Cap them at the maximum specified in the tables.
        capped_household_size = min_(people, max_people_on_file).astype(int)
        # Calculate additional people beyond the maximum in tables.
```

2024-08-29 15:29 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/nc/ncdhhs/tanf/nc_tanf_need_standard.yaml
could you add a test for size 1 and 14 - just for edge case pruposes

2024-08-29 15:29 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nc/ncdhhs/tanf/nc_demographic_tanf_eligible.py
> +        eligible = person("is_child", period)
```suggestion
        is_child = person("is_child", period)
```

2024-08-29 15:29 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nc/ncdhhs/tanf/nc_demographic_tanf_eligible.py
> +    label = "NC Demographic eligibility for TANF"
```suggestion
    label = "North Carolina Demographic eligibility for TANF"
```

2024-08-29 15:29 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nc/ncdhhs/tanf/nc_tanf.py
> +        return max_((need_standard - income) * payment_percentage, 0)
```suggestion
        reduced_need_standard = max_(need_standard - income, 0)
        return reduced_need_standard * payment_percentage
```

2024-08-29 15:29 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nc/ncdhhs/tanf/income/nc_tanf_countable_earned_income.py
> +    definition_period = YEAR
```suggestion
    definition_period = YEAR
    defined_for = StateCode.NC 
```

2024-08-29 15:29 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nc/ncdhhs/tanf/income/nc_tanf_countable_earned_income.py
> +    definition_period = YEAR
can we add this to all vars that are not defined fro an eligibility variable, just to minimize the computation for other states

2024-08-29 15:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nc/ncdhhs/tanf/need_standard/monthly_allowed_difference.yaml
rename to `average_reduced_need_standard_thresold.yaml`

2024-08-29 15:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nc/ncdhhs/tanf/need_standard/monthly_allowed_difference.yaml
> +description: North Carolina uses this threshold amount to determine if a filer is qualified for the TANF program.
```suggestion
description: North Carolina limits the TANF program to filers with an average need standard of each household member, reduced by income, of this amount.
```

2024-08-29 15:29 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nc/ncdhhs/tanf/need_standard/monthly_allowed_difference.yaml
> +  label: North Carolina TANF monthly eligible threshold
```suggestion
  label: North Carolina TANF average need standard threshold
```

2024-08-29 15:31 UTC, PavelMakarchuk commented
Should be the last batch of format adjustments, thank you @myang1010

2024-08-29 22:49 UTC, PavelMakarchuk approved these changes

2024-09-04 00:02 UTC, MaxGhenis requested changes
Some of these suggestions will apply to other parts of the code.

By the way, I got some of these suggestions from Claude, where I uploaded the program document and used https://gh-stitcher.streamlit.app to compare to this PR. [Here's the exchange.](https://gist.github.com/MaxGhenis/741f8509421f0fe56034319ac70f9679)

2024-09-04 00:02 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/nc/ncdhhs/tanf/nc_tanf_income_eligible.py
> +        reduced_need_standard = max_(need_standard - income, 0)
create a separate policyengine variable for this since it's used both here and in nc_tanf

2024-09-04 03:46 UTC, myang1010 commented on policyengine_us/variables/gov/states/nc/ncdhhs/tanf/nc_demographic_tanf_eligible.py
> +
Our current definition of `is_child`, "return person("age", period) < 18" meets NC's definition of child. Do I still need to make it policy parameter?

2024-09-04 04:20 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/nc/ncdhhs/tanf/nc_demographic_tanf_eligible.py
> +
Yes - if a jurisdiction defines a policy parameter we add it as its own parameter. This lets us model changes within their purview.

2024-09-05 16:47 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/states/nc/ncdhhs/tanf/nc_tanf_integration.yaml
rename integration.yaml

@PavelMakarchuk could you take a look at the cause for these test failures?

2024-09-05 19:54 UTC, myang1010 commented on policyengine_us/tests/policy/baseline/gov/states/nc/ncdhhs/tanf/nc_tanf_integration.yaml
Okay, rename the file to "integration.yaml".
Thanks @PavelMakarchuk , `make install` helps and unblocked me from testing in my local!

2024-09-05 23:55 UTC, MaxGhenis approved these changes

2024-09-05 23:55 UTC, merged