Kansas Additional Exemption for Disabled Veterans 2023
PolicyEngine/policyengine-us pull request #5052
Opened 2024-09-10 15:44 UTC by hua7450

Fixes #4969

2024-09-11 00:39 UTC, PavelMakarchuk requested changes

2024-09-11 00:39 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ks/tax/income/exemptions/veterans_matched.yaml
Lets rename to `in_effect.yaml`

2024-09-11 00:39 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/ks/tax/income/exemptions/ks_exemptions.yaml
> +    ks_disabled_veteran
need value

2024-09-11 00:39 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ks/tax/income/exemptions/disabled_veteran/ks_disabled_veteran_exemptions.py
> +        return p.veterans_matched * adds(tax_unit, period, ["ks_disabled_veteran_exemptions_person"])
separate into two lines

2024-09-11 21:06 UTC, PavelMakarchuk requested changes

2024-09-11 21:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ks/tax/income/exemptions/disabled_veteran/ks_disabled_veteran_exemptions.py
lets just make one file:
`ks_disabled_veterans_exemption_eligible_person` which checks for veteran status and disability - and then add it together in the main exemption file

2024-09-12 10:00 UTC, PavelMakarchuk requested changes

2024-09-13 11:01 UTC, PavelMakarchuk requested changes

2024-09-13 11:01 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ks/tax/income/exemptions/amount/disabled_veteran.yaml
> +    href: https://www.ksrevenue.gov/pdf/k-4023.pdf#page=1
```suggestion
    href: https://www.ksrevenue.gov/pdf/k-4023.pdf#page=2
```

2024-09-20 13:18 UTC, PavelMakarchuk requested changes

2024-09-20 13:18 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ks/tax/income/exemptions/ks_disabled_veteran_exemptions_person.py
> +    unit = USD
```suggestion
    value_type = bool
    entity = Person
    label = "Eligible person for the Kansas disabled veteran exemption"
```

2024-09-20 13:18 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ks/tax/income/exemptions/in_effect.yaml
My mistake here, 
we should have
`base.yaml` - base exemptions amount 
disabled_veteran folder with files:
`base.yaml`
`in_effect.yaml`

2024-09-20 13:18 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ks/tax/income/exemptions/amount/base.yaml
> +description: Kansas provides this exemption amount for each person in a filing unit.
```suggestion
description: Kansas provides the following exemption amount for each person in a filing unit.
```

2024-09-20 13:18 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ks/tax/income/exemptions/amount/disabled_veteran.yaml
> +description: Kansas provides this exemption amount for disabled veterans.
```suggestion
description: Kansas provides the following exemption amount for disabled veterans.
```

2024-09-24 23:22 UTC, PavelMakarchuk commented on policyengine_us/variables/household/demographic/person/is_veteran.py
@MaxGhenis 
we have been using `veterans_benefits > 0` for the determination of whether the person is a veteran or not, I think adding a bool variable would be appropriate given how we handle other situations like parent etc. 
thoughts? 

@hua7450 if confirmed
could we add a formula to check if `veterans_benefits > 0` and file an issue to consolidate in the rest of the repo

2024-10-15 02:47 UTC, PavelMakarchuk approved these changes
Minor format

2024-10-15 02:47 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ks/tax/income/exemptions/disabled_veteran/base.yaml
> +description: Kansas provides the following exemption amount for disabled veterans.
```suggestion
description: Kansas provides the following exemption amount for each disabled veteran.
```

2024-10-15 02:47 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ks/tax/income/exemptions/ks_disabled_veteran_exemptions_person.py
> +    unit = USD
```suggestion
```

2024-10-15 03:14 UTC, MaxGhenis approved these changes

2024-10-15 03:15 UTC, merged