Oklahoma Military Retirement Benefit Exclusion 2022
PolicyEngine/policyengine-us pull request #5076
Opened 2024-09-13 19:39 UTC by hua7450

Fixes #5017

2024-09-13 19:41 UTC, hua7450 commented on policyengine_us/parameters/gov/states/ok/tax/income/agi/subtractions/military_retirement/amount.yaml
> +description: Oklahoma limit on military retirement benefit AGI subtraction per person.
How should I name this parameter? It's neither a maximum amount nor a minimum amount.

2024-09-17 00:02 UTC, PavelMakarchuk approved these changes
LGTM after this change

2024-09-17 00:02 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/ok/tax/income/agi/subtractions/military_retirement/rate.yaml
> +description: Oklahoma excludes this percent of the military retirement benefits.
```suggestion
description: Oklahoma excludes this percentage of military retirement benefits under the retirement benefit subtraction.
```

2024-09-27 19:35 UTC, MaxGhenis requested changes

2024-09-27 19:35 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ok/tax/income/ok_agi_subtractions.py
> +        return oasdi + capped_pension + military_retirement_exclusion
please make this a list parameter, and put the capped pension subtraction into a new variable

2024-09-28 03:37 UTC, MaxGhenis approved these changes

2024-09-28 03:37 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ok/tax/income/subtractions/ok_pension_subtraction.py
> +    label = "Oklahoma AGI subtractions from federal AGI"
```suggestion
    label = "Oklahoma pension subtraction"
```

2024-09-28 03:37 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ok/tax/income/subtractions/ok_pension_subtraction.py
> +        capped_pension = tax_unit.sum(min_(p.pension_limit, pensions))
delete next line
```suggestion
        return tax_unit.sum(min_(p.pension_limit, pensions))
```

2024-09-29 23:26 UTC, merged