North Carolina Military Retirement Deduction 2022
PolicyEngine/policyengine-us pull request #5077
Opened 2024-09-13 20:16 UTC by vrathi101

Fixes #5015

2024-09-13 21:06 UTC, PavelMakarchuk requested changes

2024-09-13 21:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nc/tax/income/deductions/deductions.yaml
> +    -
```suggestion
    - nc_military_retirement_deduction
```

2024-09-13 21:06 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/nc/tax/income/deductions/military_retirement/minimum_years.yaml
> +  unit: /1
```suggestion
  unit: years
```

2024-09-13 21:06 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/nc/tax/income/deductions/military_retirement/nc_military_retirement_deduction_eligible.py
> +    unit = USD
```suggestion
```

2024-09-18 11:16 UTC, PavelMakarchuk approved these changes

2024-09-19 01:17 UTC, MaxGhenis commented on policyengine_us/variables/household/demographic/person/is_medically_retired.py
Does this seem sufficiently different from `is_permanently_and_totally_disabled` or `is_permanently_disabled_veteran` to require a new variable?

2024-09-23 16:47 UTC, vrathi101 commented on policyengine_us/variables/household/demographic/person/is_medically_retired.py
> Does this seem sufficiently different from `is_permanently_and_totally_disabled` or `is_permanently_disabled_veteran` to require a new variable?

i guess not actually, I will use the `is_permanently_disabled_veteran` variable instead

2024-09-30 16:55 UTC, MaxGhenis approved these changes

2024-09-30 17:02 UTC, merged