Indiana National Guard and Reserve Pay Deduction 2023
PolicyEngine/policyengine-us pull request #5082
Opened 2024-09-16 15:26 UTC by srilareddy

Fixes #5031

2024-09-16 16:03 UTC, PavelMakarchuk requested changes

2024-09-16 16:03 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Indiana National Guard and Reserve Pay Deduction 2023
```suggestion
    - Indiana National Guard and Reserve Pay Deduction 2023.
```

2024-09-16 16:03 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/deductions/deductions.yaml
> +description: List of standard deductions applicable to Indiana taxpayers.
```suggestion
description: Indiana provides the following deductions.
```

2024-09-16 16:03 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/deductions/deductions.yaml
> +    - tax_unit_taxable_social_security  # includes railroad retirement benefits
move comment to new line in 2021 and 2023

2024-09-16 16:03 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/deductions/deductions.yaml
> +
```suggestion
    - title: Indiana General Assembly Legal Code Taxation Title 6 
     href: http://iga.in.gov/legislative/laws/2021/ic/titles/006#6-3
 
```

2024-09-16 23:53 UTC, PavelMakarchuk approved these changes

2024-09-19 02:35 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/in/tax/income/deductions/deductions.yaml
> +    - salt_refund_last_year
could you cite subsections for each of these in comments?

2024-10-21 06:51 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/deductions/deductions.yaml
> +    # IT-40 Booklet-(621), pg. 22
IC 6-3-2-4 (b)

2024-10-21 06:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/deductions/deductions.yaml
> +    # IT-40 Booklet 2023, pg.17
IC 6-8-5-1

2024-10-21 06:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/deductions/deductions.yaml
> +    # IT-40 Booklet 2023, pg.17
IC 6-8-5-1

2024-10-21 07:01 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/deductions/deductions.yaml
> +    # IT-40 Booklet 2023, pg.17
IC 6-3.1-19-1

2024-12-24 12:45 UTC, MaxGhenis approved these changes

2024-12-24 12:45 UTC, merged