Fixes #5004
PolicyEngine/policyengine-us pull request #5107
Opened 2024-09-20 02:05 UTC by srilareddy

Fixes #5004

2024-09-24 20:56 UTC, PavelMakarchuk requested changes

2024-09-24 20:56 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/household/income/spm_unit/spm_unit_broadband_subsidy.yaml
> +    spm_unit_broadband_subsidy: 2
```suggestion
```

Dont need to add another test - one baseline unit test is fine - there is no significant other edge case to test

2024-09-24 20:56 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/household/income/spm_unit/spm_unit_broadband_subsidy.yaml
> +- name: Otherwise sum ACP 1, EBB 1
```suggestion
- name: Baseline subsidy test with relevant inputs
```

2024-09-24 20:56 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +      -Remove lifeline varibale from spm_unit_broadband_subsidy.
```suggestion
      - Remove lifeline variable from spm_unit_broadband_subsidy.
```

2024-09-24 20:56 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +      -Modified tests for spm_unit_broadband_subsidy.
```suggestion
      - Modified tests for spm_unit_broadband_subsidy.
```

2024-09-26 21:53 UTC, PavelMakarchuk approved these changes

2024-09-26 22:02 UTC, MaxGhenis approved these changes

2024-09-27 20:12 UTC, merged