change is_widowed to is_surviving_spouse
PolicyEngine/policyengine-us pull request #5108
Opened 2024-09-20 15:01 UTC by samantharudra

Fixes #4710

2024-09-24 13:05 UTC, PavelMakarchuk requested changes

2024-09-24 13:05 UTC, PavelMakarchuk commented on policyengine_us/variables/household/demographic/tax_unit/surviving_spouse_eligible.py
You should be able to search in the codespace

2024-12-04 15:50 UTC, MaxGhenis requested changes

2024-12-04 15:50 UTC, MaxGhenis commented on policyengine_us/variables/household/demographic/tax_unit/surviving_spouse_eligible.py
also label and documentation

2024-12-04 15:50 UTC, MaxGhenis commented on policyengine_us/variables/household/demographic/tax_unit/surviving_spouse_eligible.py
> +        widowed_head = tax_unit.any(is_head & is_surviving_spouse)
and elsewhere
```suggestion
        surviving_spouse_head = tax_unit.any(is_head & is_surviving_spouse)
```

2025-01-09 16:04 UTC, MaxGhenis commented
How's this going?

2025-01-31 15:43 UTC, PavelMakarchuk commented
Duplicate of #5540

2025-01-31 15:43 UTC, closed without merging