Apply the TCJA mortgage interest deduction limits
PolicyEngine/policyengine-us pull request #5129
Opened 2024-09-25 12:50 UTC by PavelMakarchuk

Fixes #5128

2024-09-25 13:41 UTC, MaxGhenis requested changes
The US caps the mortgage value to which interest is applied, not the interest itself. It's also based on the year of purchase not tax year. 

We can't model this today so could we change the logic to deduct the full value of a new variable for deductible mortgage interest? Keep the policy parameter but don't apply it. Check us-data too.

2024-09-27 19:12 UTC, MaxGhenis commented
still need to update the description and the variable names - `mortgage_interest` implies total

2024-09-30 02:43 UTC, PavelMakarchuk commented
> still need to update the description and the variable names - `mortgage_interest` implies total

adjusted

2024-09-30 12:33 UTC, MaxGhenis commented on policyengine_us/parameters/gov/irs/deductions/itemized/interest/mortgage/cap.yaml
> +description: IRS limits the total home mortgage value to this amount, based on filing status under the mortgage interest deduction.
```suggestion
description: The IRS allows an itemized deduction for interest paid on mortgages up to this amount, based on filing status.
```

2024-12-04 21:37 UTC, MaxGhenis approved these changes

2024-12-04 21:37 UTC, merged