Fix 2024 SNAP parameters based on SNAP Screener
PolicyEngine/policyengine-us pull request #5146
Opened 2024-09-26 20:57 UTC by hua7450

Fixes #5115

2024-09-26 21:19 UTC, hua7450 commented
Still a draft, detailed differences in this [doc](https://docs.google.com/document/d/1xX6RtIQ7LGFtZYOReG-CUWvhKHE7hxkYX_fJMgpiU1w/edit).

2024-10-05 16:07 UTC, vrathi101 commented
@hua7450 is this pr supposed to fix old values (FY 2023 and before) or update parameters with FY2024. If its the former, the dates should be fixed from `2024-10-01` to `2023-10-01` and if its the latter most of the states are missing updated values as shown in https://www.fns.usda.gov/snap/eligibility/deduction/standard-utility-allowances

2024-10-06 06:35 UTC, hua7450 commented
> @hua7450 is this pr supposed to fix old values (FY 2023 and before) or update parameters with FY2024. If its the former, the dates should be fixed from `2024-10-01` to `2023-10-01` and if its the latter most of the states are missing updated values as shown in https://www.fns.usda.gov/snap/eligibility/deduction/standard-utility-allowances

It’s the later. I have updated all the 2024 values in the utility folder. Those states that did not have 2024 values have the same values as they have in 2023. 

2024-10-06 15:36 UTC, vrathi101 commented
> > @hua7450 is this pr supposed to fix old values (FY 2023 and before) or update parameters with FY2024. If its the former, the dates should be fixed from `2024-10-01` to `2023-10-01` and if its the latter most of the states are missing updated values as shown in https://www.fns.usda.gov/snap/eligibility/deduction/standard-utility-allowances
> 
> It’s the later. I have updated all the 2024 values in the utility folder. Those states that did not have 2024 values have the same values as they have in 2023.

ok, in that case aren't you missing a ton of values, 
for example in water utilities: Alaska = 57, colorado = 69, delaware = 99, DC = 88, etc. or am I misunderstanding?
![image](https://github.com/user-attachments/assets/d6af4193-38a1-4e9c-a73e-18465a70045f)

2024-10-08 18:48 UTC, hua7450 commented
> > > @hua7450 is this pr supposed to fix old values (FY 2023 and before) or update parameters with FY2024. If its the former, the dates should be fixed from `2024-10-01` to `2023-10-01` and if its the latter most of the states are missing updated values as shown in https://www.fns.usda.gov/snap/eligibility/deduction/standard-utility-allowances
> > 
> > 
> > It’s the later. I have updated all the 2024 values in the utility folder. Those states that did not have 2024 values have the same values as they have in 2023.
> 
> ok, in that case aren't you missing a ton of values, for example in water utilities: Alaska = 57, colorado = 69, delaware = 99, DC = 88, etc. or am I misunderstanding? I circled some examples but there are a bunch more <img alt="Screenshot 2024-10-06 at 10 38 33 AM" width="593" src="https://private-user-images.githubusercontent.com/72925608/373959655-1e651506-6364-4684-9d71-88422a8303f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTM1NTAsIm5iZiI6MTcyODQxMzI1MCwicGF0aCI6Ii83MjkyNTYwOC8zNzM5NTk2NTUtMWU2NTE1MDYtNjM2NC00Njg0LTlkNzEtODg0MjJhODMwM2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE4NDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ODVkZDkzOTM4ZjY3NzM5MzRkMWFiYWRmMTZlMjBhZmJiZDI1MWFjN2NhZDcwMGRjYmFjYTc2MjM5NzY5NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tLwkxs02ww7E-g0yBi6aC5pmlmRRONwFd2tktT0zRVM">

Yes, I will double-check and add more to it.

2024-10-13 23:48 UTC, hua7450 commented
@vrathi101 I just checked, I think you are looking at the Excel sheet for FY 2025, USDA recently updated the Excel sheet for utility in October. That's why the values you see are different from mine.

2024-10-15 16:14 UTC, vrathi101 commented
> @vrathi101 I just checked, I think you are looking at the Excel sheet for FY 2025, USDA recently updated the Excel sheet for utility in October. That's why the values you see are different from mine. ![image](https://private-user-images.githubusercontent.com/113824411/376079435-f415810e-f386-456d-bc6b-ba6ee1b84660.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDkxMzgsIm5iZiI6MTcyOTAwODgzOCwicGF0aCI6Ii8xMTM4MjQ0MTEvMzc2MDc5NDM1LWY0MTU4MTBlLWYzODYtNDU2ZC1iYzZiLWJhNmVlMWI4NDY2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxNjEzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzljMTc0ODlhMjc3MzgxYWZlZGI2ODBjNWJiMTY1OWNhYjQ4YzlmZThmNDBkMmQ0MzAyNTZiNjcxNjNiMDRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RdumEdcNb__5mlblKkt-mlyroWG-iQo5s5zl9Z3pd4g)

i see, my bad for that

2024-10-21 13:40 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/hhs/tanf/non_cash/income_limit/gross.yaml
> +MO:
can we add pre-2024 values as well?

2024-10-22 19:10 UTC, hua7450 commented on policyengine_us/parameters/gov/hhs/tanf/non_cash/requires_all_for_hheod.yaml
> +#  2024-07-02: false
The NaN trick did not work; this line is the only problem causing error.

2024-10-23 05:57 UTC, PavelMakarchuk requested changes

2024-10-23 05:57 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/hhs/tanf/non_cash/requires_all_for_hheod.yaml
> +#  2024-07-02: false
```suggestion
ID:
  2020-07-01: `x` 
  2024-07-02: false
```

2024-10-23 05:57 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/hhs/tanf/non_cash/requires_all_for_hheod.yaml
> +#  2024-07-02: false
We need a value there instead of x or have the false parameter start earlier

2024-10-23 19:19 UTC, vrathi101 requested changes

2024-10-23 19:19 UTC, vrathi101 commented on policyengine_us/parameters/gov/usda/snap/income/deductions/utility/single/phone.yaml
> +    href: https://www.fns.usda.gov/sites/default/files/resource-files/snap-sua-table-fy24-032624.xlsx
This link doesn't work for me (the FY 2024 one). Could you fix this and for all other files

2024-11-07 16:02 UTC, DTrim99 commented on policyengine_us/parameters/gov/hhs/tanf/non_cash/income_limit/gross.yaml
Add reference: https://www.fns.usda.gov/snap/broad-based-categorical-eligibility

2024-11-12 14:55 UTC, DTrim99 approved these changes

2024-12-01 02:06 UTC, MaxGhenis commented
@PavelMakarchuk could you please review?

2025-04-06 14:53 UTC, closed without merging

2025-05-01 16:06 UTC, PavelMakarchuk approved these changes

2025-05-01 16:09 UTC, MaxGhenis approved these changes

2025-05-01 16:09 UTC, MaxGhenis approved these changes