Create new structure for Indiana dependent exemptions
PolicyEngine/policyengine-us pull request #5224
Opened 2024-10-14 17:07 UTC by samantharudra

Fixes #5223

2024-10-25 14:56 UTC, PavelMakarchuk requested changes

2024-10-25 14:56 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - Added more tests.
```suggestion
    - Separate Indiana dependent exemptions.
```

2024-10-25 14:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/exemptions/base/amount.yaml
> +    - title: 2023 IT-40 Income Tax Form Instruction Booklet, pg. 30
also an href (hyperlink)

2024-10-25 14:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/exemptions/base/amount.yaml
> +    - title: 2023 IT-40 Income Tax Form Instruction Booklet, pg. 30
```suggestion
```

2024-10-25 14:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/exemptions/base/amount.yaml
> +    - title: 2023 IT-40 Income Tax Form Instruction Booklet, pg. 30
Dont need the same reference multiple times

2024-10-25 14:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/exemptions/base/dependent.yaml
> +  label: Indiana exemptions base amount - dependent
```suggestion
  label: Indiana dependent exemptions amount 
```

2024-10-25 14:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/exemptions/base/dependent.yaml
> +    - title: 2023 IT-40 Income Tax Form Instruction Booklet, pg. 30
```suggestion
```

2024-10-25 14:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/exemptions/base/dependent.yaml
> +      href: http://iga.in.gov/legislative/laws/2021/ic/titles/006#6-3-1-3.5
could you double check that all references show the number

2024-10-25 14:56 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/in/tax/income/exemptions/base/dependent.yaml
> +description: Indiana provides this base exemption amount for dependent.
```suggestion
description: Indiana provides this base exemption amount for each dependent.
```

2024-10-25 14:56 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/in/tax/income/exemptions/in_base_exemptions.yaml
> +    ga_exemptions: 2_000
need to test in_base_exemptions

2024-10-25 14:56 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/in/tax/income/exemptions/in_base_exemptions.yaml
> +    tax_unit_dependents: 0
could you create also some tests with available dependents

2024-10-25 14:56 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/in/tax/income/exemptions/in_base_exemptions.py
> +
delete white space

2024-10-25 14:58 UTC, PavelMakarchuk commented
To run the test:
```
policyengine-core test ./policyengine_us/tests/policy/baseline/gov/states/in/tax/income/exemptions/in_base_exemptions.yaml
```

2024-10-29 20:28 UTC, PavelMakarchuk requested changes

2024-10-29 20:28 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +
```suggestion

```

2024-10-29 20:28 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +
We should only have one empty line which starts all the way on the left

2024-10-31 18:56 UTC, MaxGhenis requested changes

2024-10-31 18:56 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/in/tax/income/exemptions/in_base_exemptions.py
> +        total_base = unit_without_dependents * non_dependent_exemptions
Please rename `base/amount` to `base/filer`. Also please avoid adding new Python variables that only rename parameters, as the absence of `p.` makes it less obvious that it's a parameter.
```suggestion
        total_base = unit_without_dependents * p.base.filer
```

2024-10-31 18:56 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/in/tax/income/exemptions/in_base_exemptions.py
Please split the formula into these components for clarity. In general we try to apply this in cases where the formula ends in a summation.
```suggestion
    adds = ["in_base_filer_exemptions", "in_base_dependents_exemptions"]
```

2024-10-31 18:56 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/in/tax/income/exemptions/base/dependent.yaml
> +    - title: IC 6-3-1-3.5 "Adjusted gross income" (a)(3)-(4)
(3) is the filer amount not dependent.
```suggestion
    - title: IC 6-3-1-3.5 "Adjusted gross income" (a)(4)
```

2024-11-21 02:06 UTC, closed without merging

2024-11-21 02:06 UTC, PavelMakarchuk commented
Not needed due to #5353