Change `_lsr` to `_behavioral_response`
PolicyEngine/policyengine-us pull request #5286
Opened 2024-10-31 07:24 UTC by Mshuning

Fixes #5258

2024-10-31 14:38 UTC, PavelMakarchuk requested changes

2024-10-31 14:38 UTC, PavelMakarchuk commented on policyengine_us/variables/household/income/person/weekly_hours_worked.py
> +            income_effect = person(
could you add some unit tests for anything that is not covered here?

2024-10-31 17:23 UTC, PavelMakarchuk commented
We will need to make some adjustments once #5287 merged

2024-11-01 03:53 UTC, Mshuning commented
> We will need to make some adjustments once #5287 merged

is it already been merged?

2024-11-04 14:05 UTC, PavelMakarchuk requested changes
Revert the changes unrelated to the PR - it seems like there have been some merge confliacts

2024-11-04 14:05 UTC, PavelMakarchuk commented on CHANGELOG.md
> -## [1.137.3] - 2024-11-01 16:53:33
add back

2024-11-04 14:05 UTC, PavelMakarchuk commented on CHANGELOG.md
> -[1.137.3]: https://github.com/PolicyEngine/policyengine-us/compare/1.137.2...1.137.3
add back

2024-11-04 14:05 UTC, PavelMakarchuk commented on changelog.yaml
> -- bump: patch
add back

2024-11-04 14:05 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/states/co/tax/income/credits/sales_tax_refund/amount/amount.yaml
> +  2023-01-01: 661
change back

2024-11-04 14:05 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/states/co/tax/income/credits/sales_tax_refund/co_sales_tax_refund.yaml
> -
add back

2024-11-04 14:05 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/il/tax/income/exemptions/il_personal_exemption.py
> -from policyengine_us.variables.gov.states.il.tax.income.exemptions.il_personal_exemption_eligibility_status import (
change back

2024-12-24 22:02 UTC, PavelMakarchuk commented
Duplicate of #5321

2024-12-24 22:02 UTC, closed without merging