Los Angeles County Infant Supplement and Expectant Parent Payment
PolicyEngine/policyengine-us pull request #5320
Opened 2024-11-11 00:03 UTC by PavelMakarchuk

Fixes #5319

2024-11-11 04:55 UTC, MaxGhenis requested changes
Shouldn't we make all these monthly?

Could you cite the WIC (legal code) pointed to in the pdf doc? In particular I'm unclear on the definition of infant here.

Also check some typos in descriptions

2024-11-11 23:03 UTC, PavelMakarchuk commented
> Shouldn't we make all these monthly?
> 
> Could you cite the WIC (legal code) pointed to in the pdf doc? In particular I'm unclear on the definition of infant here.
> 
> Also check some typos in descriptions

Refactored to monthly and added the infant definition

2024-11-12 02:30 UTC, MaxGhenis commented on policyengine_us/parameters/gov/local/ca/la/dss/expectant_parent_payment/amount.yaml
> +description: The California Department of Social Services provides the following Expectant Parent Payment amount, based on pregnancy months.
`based on` usually for breakdowns
```suggestion
description: The California Department of Social Services provides the following Expectant Parent Payment. 
```

2024-11-12 02:39 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ca/infant/age_limit.yaml
> +description: California defines infants as children below this age threshold.
the formula does `<=` though, and the test says 1 is eligible

2024-11-12 02:39 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/local/ca/la/dss/infant_supplement/ca_la_infant_supplement.yaml
> +- name: Eligble household with one infant, not in group home
```suggestion
- name: Eligible household with one infant, not in group home
```

2024-11-12 02:40 UTC, MaxGhenis commented on policyengine_us/variables/gov/local/ca/la/dss/expectant_parent_payment/ca_la_expectant_parent_payment.py
> +
right? or [] around?
```suggestion
    adds = "gov.local.ca.la.dss.expectant_parent_payment.amount"
```

2024-11-12 02:41 UTC, MaxGhenis commented on policyengine_us/variables/gov/local/ca/la/dss/infant_supplement/ca_la_infant_supplement.py
> +        eligble = household.any(eligible_person)
```suggestion
        eligible = household.any(eligible_person)
```

2024-11-12 15:10 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/local/ca/la/dss/expectant_parent_payment/ca_la_expectant_parent_payment.py
> +
Forgot about the [] - works here

2024-11-12 16:39 UTC, PavelMakarchuk commented
> please point to the WIC where relevant https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=WIC&sectionNum=11465.
> 
> I think some of this is actually dependent on other policy parameters around foster care

If referring to the amounts - I am not sure which other program WIC refers to - I have added the legal code to the relevant sections

2024-11-13 03:21 UTC, MaxGhenis approved these changes

2024-11-13 03:21 UTC, MaxGhenis commented on policyengine_us/variables/gov/local/ca/la/dss/infant_supplement/ca_la_infant_supplement_eligible_infant.py
> +        age = person("age", period)
```suggestion
```

2024-11-13 03:22 UTC, MaxGhenis commented on policyengine_us/variables/gov/local/ca/la/dss/infant_supplement/ca_la_infant_supplement_eligible_infant.py
> +        p = parameters(period).gov.local.ca
```suggestion
```

2024-11-13 16:46 UTC, merged