Remove CBO elasticities toggle
PolicyEngine/policyengine-us pull request #5347
Opened 2024-11-19 17:22 UTC by vrathi101

Fixes #5310

2024-11-19 22:45 UTC, PavelMakarchuk approved these changes

2024-11-19 22:51 UTC, MaxGhenis requested changes
Could you also add unit tests while here to appease the codecov?

2024-11-19 22:51 UTC, MaxGhenis commented on policyengine_us/variables/gov/simulation/labor_supply_response/labor_supply_response.py
Also change unit to "/1" (substitution too)

```suggestion
        adds = ["gov.simulation.labor_supply_responses.elasticities.income"]
```

2024-12-04 15:48 UTC, MaxGhenis commented
Friendly ping

2024-12-04 20:08 UTC, vrathi101 commented
> Friendly ping

Me and @PavelMakarchuk were working through how to write the unit tests for `labor_supply_response.py` because of some input issues with the class structure

2024-12-04 20:16 UTC, PavelMakarchuk commented
> > Friendly ping
> 
> Me and @PavelMakarchuk were working through issues with how to write the unit tests for `labor_supply_response.py` because of some input issues with the class structure

@MaxGhenis Yes I would file a separate issue to add testing for labor supply related variables as we can't seem to accommodate the `requires_computation_after` metadata

2024-12-04 22:05 UTC, MaxGhenis approved these changes

2024-12-04 22:06 UTC, MaxGhenis requested changes
please fix the unit of the elasticities per my previous comment

2024-12-04 23:26 UTC, MaxGhenis commented
Responses should stay USD, elasticities are /1

2024-12-05 15:47 UTC, merged