Arkansas 2023 low income tax tables for hoh and surviving spouse filers
PolicyEngine/policyengine-us pull request #5361
Opened 2024-11-24 20:08 UTC by PavelMakarchuk

Fixes #5360

2024-11-26 16:38 UTC, DTrim99 approved these changes
Parameters look correct.

2024-12-01 02:03 UTC, MaxGhenis requested changes
Please add this statutory reference which indicates uprating (and add uprating): https://law.justia.com/codes/arkansas/title-26/subtitle-5/chapter-51/subchapter-3/section-26-51-301/

2024-12-01 02:03 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ar/tax/income/rates/low_income_tax_tables/surviving_spouse/no_or_one_dependent.yaml
Typo in label

Add comment to the legal code indicating it's the value for (I think) 2020

2024-12-01 16:38 UTC, MaxGhenis approved these changes

2024-12-01 16:39 UTC, merged