Liwenxin491/issue5158
PolicyEngine/policyengine-us pull request #5370
Opened 2024-11-26 01:58 UTC by liwenxin491

2023 Optional sales tax tables

2024-11-26 16:17 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.yaml
> +Alabama:
```suggestion
AL:
```

2024-11-26 16:17 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.yaml
> +Alabama:
need to make all state code the abbreviations

2024-11-26 16:17 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.yaml
> +    60_000: 685
```suggestion
    1: 365
    2: 490
    3: 551
    4: 602
    5: 646
    6: 685
```

2024-11-26 16:19 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.yaml
> +    60_000: 685
We will need to denominate those as integers and then create a ENUM variable which determines that 
0-$20,000 = 1
$20,000 - $40,000 = 2
etc...

2024-12-12 15:43 UTC, PavelMakarchuk requested changes

2024-12-12 15:43 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.py
The enum should just determine which income bracket (1 through 19) the household is in 

If income is 0 to 20,000 -> 1 
if income is 20,001 to 40,000 -> 2

Etc.

2024-12-12 15:43 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.py
The actual sales tax value is determined separately in a different file

2024-12-12 15:43 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.py
Follow the exact same format from `filing_status.py` 

Or from any other `value_type = Enum`

2024-12-24 06:53 UTC, PavelMakarchuk requested changes

2024-12-24 06:53 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.py
could we write a unit test?

2024-12-24 06:53 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.py
> +    1 = "0"
```suggestion
    Zero = "ZERO"
```

2024-12-24 06:53 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.py
> +    1 = "0"
and others

2024-12-24 06:53 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.py
> +class StateSalesTax(Enum):
```suggestion
class StateSalesTaxIncomeBracket(Enum):
```

2024-12-24 06:53 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.py
> +class state_sales_tax(Variable):
```suggestion
class state_sales_tax_income_bracket(Variable):
```

2024-12-24 06:53 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.py
> +    possible_values = StateSalesTax
```suggestion
    possible_values = StateSalesTaxIncomeBracket
```

2024-12-24 06:53 UTC, PavelMakarchuk commented on changelog_entry.yaml
add changelog

2025-01-06 17:25 UTC, liwenxin491 commented on policyengine_us/variables/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.py
> +    1 = "0"
Do I change the level name in the yaml from 1 to "ONE" as well?

2025-01-21 00:59 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.yaml
> +  - state_code
need to add two other breakdown categories

2025-01-21 00:59 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.yaml
> +    1: 365
each value needs a period to start - see other breakdown parameters

2025-01-21 00:59 UTC, PavelMakarchuk commented on changelog_entry.yaml
> +    - 2023 Optional State Sales Tax
```suggestion
    - Optional State Sales Tax rates.
```

2025-01-21 01:04 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.yaml
> +    1: 365
```suggestion
    1: 
        2023-01-01: 365
```

2025-01-21 01:07 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.yaml
> +    ONE: 365
```suggestion
    ONE: 
          2023-01-01: 365
```

2025-01-21 01:08 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.yaml
> +  - state_code
```suggestion
  - state_code
  - range(1, 6)
  - state_sales_tax_income_bracket
```

2025-01-21 01:10 UTC, PavelMakarchuk commented on policyengine_us/parameters/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.yaml
> +  - state_code
then use `clip(unit, 1, 6)` in the formula

2025-01-21 01:11 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax.yaml
need to adjust `state_sales_tax.py`

2025-01-21 01:14 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/irs/deductions/itemized/salt_and_real_estate/state_sales_tax_income_bracket.py
> +    possible_values = StateSalesTaxIncomeBracket
```suggestion
    possible_values = StateSalesTaxIncomeBracket
    default_value = StateSalesTaxIncomeBracket.One
```

2025-01-24 03:21 UTC, MaxGhenis approved these changes

2025-01-24 16:55 UTC, merged