Puerto Rico Low Income Credit
PolicyEngine/policyengine-us pull request #5396
Opened 2024-12-10 18:27 UTC by PavelMakarchuk

Fixes #5395

2024-12-10 20:16 UTC, MaxGhenis commented on policyengine_us/parameters/gov/territories/pr/tax/income/credits/low_income/additional/income_limit.yaml
> +description: Puerto Rico limits the compensatory tax credit for low-income pensioners to filers with pension income below this limit.
disagree - what does `pensioner` mean? filer seems clearer

2025-01-10 14:25 UTC, MaxGhenis requested changes
couple initial questions but adding @DTrim99 for a more full review

2025-01-10 14:25 UTC, MaxGhenis commented on policyengine_us/parameters/gov/territories/pr/tax/income/credits/low_income/additional/amount.yaml
> +description: Puerto Rico provides the following compensatory tax credit amount for low-income pensioners.
```suggestion
description: Puerto Rico provides a compensatory tax credit of this amount for low-income pensioners.
```

2025-01-10 14:25 UTC, MaxGhenis commented on policyengine_us/parameters/gov/territories/pr/tax/income/credits/low_income/additional/amount.yaml
could unify with income_limit as a scale parameter

2025-01-10 14:25 UTC, MaxGhenis commented on policyengine_us/parameters/gov/territories/pr/tax/income/credits/low_income/age_threshold.yaml
> +description: Puerto Rico limits the low income tax credit to filers below this age threshold.
below? it says `has attained`

2025-01-14 17:24 UTC, DTrim99 approved these changes

2025-01-16 16:11 UTC, MaxGhenis requested changes

2025-01-16 16:11 UTC, MaxGhenis commented on policyengine_us/parameters/gov/territories/pr/tax/income/credits/low_income/income_limit/one_eligible_person.yaml
unify this with two_eligible_people with a scale parameter

2025-01-16 16:11 UTC, MaxGhenis commented on policyengine_us/variables/gov/territories/pr/tax/income/credits/low_income/pr_low_income_credit.py
> +        eligible_people = tax_unit.sum(eligible_person)
Irrelevant with `pr_low_income_credit_eligible_people` but for future reference this can combine the two statements:
```python
        eligible_people = add(tax_unit, period, ["pr_low_income_credit_eligible_person"])
```

2025-01-16 16:11 UTC, MaxGhenis commented on policyengine_us/variables/gov/territories/pr/tax/income/credits/low_income/pr_low_income_credit_eligible_person.py
Do we need to know who in the tax unit is eligible? If not, change this to `pr_low_income_credit_eligible_people` and make it tax unit-level. If we do, add another variable for this which adds it, since we aggregate to the tax unit in two places so can reduce code duplication this way.

2025-01-16 16:11 UTC, MaxGhenis commented on policyengine_us/variables/gov/territories/pr/tax/income/credits/low_income/pr_low_income_credit_eligible.py
> +
Per the other suggestion to add this variable (nonzero values evaluate to true)
```suggestion
    defined_for = "pr_low_income_credit_eligible_people"

```

2025-01-16 16:11 UTC, MaxGhenis commented on policyengine_us/variables/gov/territories/pr/tax/income/credits/low_income/pr_low_income_credit_eligible.py
> +        return where(eligible_people > 0, income <= income_limit, False)
Also for future reference, if we did need both conditions please do this instead:
```python
    meets_income_test = income <= income_limit
    return (eligible_people > 0) & meets_income_test
```
```suggestion
        return income <= income_limit
```

2025-01-16 19:38 UTC, MaxGhenis requested changes

2025-01-16 19:38 UTC, MaxGhenis commented on policyengine_us/tests/policy/baseline/gov/territories/pr/tax/income/credits/low_income/pr_compensatory_low_income_credit.yaml
> +# - name: Eligible person
delete or reactivate

2025-01-16 19:46 UTC, PavelMakarchuk commented on policyengine_us/tests/policy/baseline/gov/territories/pr/tax/income/credits/low_income/pr_compensatory_low_income_credit.yaml
> +# - name: Eligible person
reactivated

2025-01-17 04:08 UTC, MaxGhenis approved these changes

2025-01-17 04:08 UTC, merged