California CAPI (Cash Assistance Program for Immigrants)
PolicyEngine/policyengine-us pull request #5420
Opened 2024-12-27 04:59 UTC by PavelMakarchuk

Fixes #5416

2024-12-27 20:55 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ca/cdss/state_supplement/ca_state_supplement_payment_standard.py
need to make sure that people who are ineligible dont get the state supplement amount accounted for in CAPI

2025-01-01 06:10 UTC, MaxGhenis requested changes

2025-01-01 06:10 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/cdss/state_supplement/ca_state_supplement_payment_standard.py
> +    label = "California CAPI payment standard"
SSI state supplement right?

2025-01-01 06:10 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/cdss/state_supplement/ca_state_supplement_payment_standard.py
> +        # Total amount
could we make this an `adds` of these pieces instead to break up the long formula?

2025-01-01 06:10 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/cdss/state_supplement/ca_state_supplement_payment_standard.py
> +        head_or_spouse = head | spouse
Doesn't look like you need head and spouse separately
```suggestion
        head_or_spouse = person("is_tax_unit_head_or_spouse", period)
```

2025-01-01 06:10 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/cdss/capi/ca_capi_resources.py
> +        vehicle_value_threshold = parameters(
break up with a `p` statement

2025-01-03 03:50 UTC, MaxGhenis approved these changes

2025-01-03 03:50 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/cdss/state_supplement/payment_standard/ca_state_supplement_food_allowance.py
> +        is_aged = age >= p.aged_or_disabled.age_threshold
make this its own variable since it's duplicated in ca_state_supplement_aged_disabled_amount

2025-01-03 03:50 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/cdss/state_supplement/payment_standard/ca_state_supplement_aged_disabled_amount.py
> +        blind_amount = where(is_married, blind_married_amount, p.blind.single)
break this and aged_disabled_amount into separate variables, then call this variable aged_blind_disabled_amount

2025-01-03 03:50 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/cdss/state_supplement/payment_standard/ca_state_supplement_food_allowance.py
> +
Make this a new variable equal to `(aged_disabled_count > 0) & ~ living_arrangements_allow_for_food_preparation`
```suggestion
    defined_for = "ca_state_supplement_food_allowance_eligible"

```

2025-01-03 03:50 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/cdss/state_supplement/payment_standard/ca_state_supplement_medical_care_facility_amount.py
> +        medical_care_facility_count = spm_unit.sum(is_in_medical_care_facility)
can skip above
```suggestion
        medical_care_facility_count = add(spm_unit, ["ca_in_medical_care_facility"])
```

2025-01-03 03:50 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/cdss/state_supplement/payment_standard/ca_state_supplement_food_allowance.py
> +        food_allowance_amount = select(
This will work after the defined_for change. Note is_married is a bool.
```suggestion
        return where(is_married & (aged_disabled_count == 2), p.allowance.food.married, p.allowance.food.single)
```

2025-01-03 03:50 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/ca_in_medical_care_facility.py
Let's make this and `in_out_of_home_care_facility` non-California-specific, move to the general household folder. Could you also confirm they should be person- rather than household-level?

2025-01-03 03:50 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ca/cdss/capi/payment_standard_offset/couple.yaml
> +description: California reduces the SSI/SSP payment standard by this amount for couples under the CAPI program.
Generally avoid acronyms in descriptions (keep in labels)
```suggestion
description: California reduces the Supplemental Security Income / State Supplemental Payment payment standard by this amount for couples when calculating the Cash Assistance Program for Immigrants.
```

2025-01-03 03:50 UTC, MaxGhenis commented on policyengine_us/variables/household/demographic/spm_unit/spm_unit_is_married.py
> +        filing_status_type = filing_status.possible_values
Nit but we use this standard
```suggestion
        filing_statuses = filing_status.possible_values
```

2025-01-03 03:51 UTC, MaxGhenis requested changes
meant to request changes

2025-01-06 00:21 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ca/ca_in_medical_care_facility.py
![image](https://github.com/user-attachments/assets/2f2ff38d-cd17-4eb3-80e4-05b4c9d6f8a2)

The language in the [legal code](https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=WIC&sectionNum=12200) suggests to me that the criteria is evaluated for each recipient individually as opposed to the household as a whole

2025-01-06 04:26 UTC, MaxGhenis requested changes

2025-01-06 04:26 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/cdss/state_supplement/payment_standard/ca_state_supplement_blind_amount.py
> +        head_or_spouse = person("is_tax_unit_head_or_spouse", period)
no action needed but filed for reference: https://github.com/PolicyEngine/policyengine-us/issues/5439

2025-01-06 04:26 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/cdss/state_supplement/payment_standard/ca_state_supplement_aged_disabled_amount.py
> +    defined_for = StateCode.CA
This will eval to true if >0, improving performance
```suggestion
    defined_for = "ca_state_supplement_aged_disabled_count"
```

2025-01-06 04:26 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/cdss/state_supplement/payment_standard/ca_state_supplement_aged_disabled_amount.py
> +        is_married = spm_unit("spm_unit_is_married", period)
Don't need this since it's based on count among head+spouse

2025-01-06 04:26 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/cdss/state_supplement/payment_standard/ca_state_supplement_aged_disabled_amount.py
> +        ).gov.states.ca.cdss.state_supplement.payment_standard
```suggestion
        ).gov.states.ca.cdss.state_supplement.payment_standard.aged_or_disabled.amount
```

2025-01-06 04:26 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/cdss/state_supplement/payment_standard/ca_state_supplement_aged_disabled_amount.py
> +        return select(
```suggestion
        return where(aged_disabled_count > 1, p.married, p.single)
```

2025-01-06 04:26 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ca/cdss/capi/resources/vehicle_value_threshold.yaml
Can we rename this `vehicle/disregard.yaml`? I think clearer than threshold.

2025-01-06 04:26 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ca/cdss/capi/resources/vehicle_value_threshold.yaml
> +description: California counts the value of a car over this threshold as resources for the Cash Assistance Program for Immigrants.
```suggestion
description: California counts the value of a vehicle exceeding this threshold as resources for the Cash Assistance Program for Immigrants.
```

2025-01-06 04:26 UTC, MaxGhenis commented on policyengine_us/parameters/gov/states/ca/cdss/capi/resources/vehicle_value_threshold.yaml
> +  label: California CAPI resource limit car value threshold
```suggestion
  label: California CAPI vehicle value disregard
```

2025-01-06 04:26 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ca/cdss/capi/ca_capi_resources.py
> +
Could you make another variable for the vehicle?
```suggestion
    adds = ["ssi_countable_resources", "ca_capi_countable_vehicle_value"]
```

2025-01-07 03:54 UTC, MaxGhenis approved these changes

2025-01-07 03:54 UTC, merged