Adjust the ia_alternate_tax_unit formula to avoid using np.inf
PolicyEngine/policyengine-us pull request #5425
Opened 2024-12-30 18:51 UTC by PavelMakarchuk

Fixes #5424

2025-01-01 06:14 UTC, MaxGhenis requested changes

2025-01-01 06:14 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ia/tax/income/alternate_tax/ia_alternate_tax_eligible.py
> +        is_single = filing_status == filing_status.possible_values.SINGLE
```suggestion
        return filing_status ~= filing_status.possible_values.SINGLE
```

2025-01-01 06:14 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ia/tax/income/alternate_tax/ia_alternate_tax_eligible.py
> +        return where(is_single, False, True)
don't need this anymore but fyi you could do `return ~is_single`

2025-01-03 04:04 UTC, MaxGhenis commented on policyengine_us/variables/gov/states/ia/tax/income/alternate_tax/ia_alternate_tax_eligible.py
> +        is_single = filing_status == filing_status.possible_values.SINGLE
did this not work?

2025-01-03 15:31 UTC, PavelMakarchuk commented on policyengine_us/variables/gov/states/ia/tax/income/alternate_tax/ia_alternate_tax_eligible.py
> +        is_single = filing_status == filing_status.possible_values.SINGLE
Worked with a small adjustment

2025-01-03 16:28 UTC, MaxGhenis approved these changes

2025-01-03 16:28 UTC, merged